/* tslint:disable */
/* eslint-disable */
/**
 * Wahlvorstand Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0-SNAPSHOT
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface WahlvorstandDTO
 */
export interface WahlvorstandDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandDTO
     */
    'wahlbezirkID'?: string;
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandDTO
     */
    'anwesenheitBeginn'?: string;
    /**
     * 
     * @type {Array<WahlvorstandsmitgliedDTO>}
     * @memberof WahlvorstandDTO
     */
    'wahlvorstandsmitglieder'?: Array<WahlvorstandsmitgliedDTO>;
}
/**
 * 
 * @export
 * @interface WahlvorstandWriteDTO
 */
export interface WahlvorstandWriteDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandWriteDTO
     */
    'anwesenheitBeginn'?: string;
    /**
     * 
     * @type {Array<WahlvorstandsmitgliedDTO>}
     * @memberof WahlvorstandWriteDTO
     */
    'wahlvorstandsmitglieder'?: Array<WahlvorstandsmitgliedDTO>;
}
/**
 * 
 * @export
 * @interface WahlvorstandsmitgliedDTO
 */
export interface WahlvorstandsmitgliedDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandsmitgliedDTO
     */
    'identifikator'?: string;
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandsmitgliedDTO
     */
    'familienname'?: string;
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandsmitgliedDTO
     */
    'vorname'?: string;
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandsmitgliedDTO
     */
    'funktion'?: WahlvorstandsmitgliedDTOFunktionEnum;
    /**
     * 
     * @type {string}
     * @memberof WahlvorstandsmitgliedDTO
     */
    'funktionsname'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof WahlvorstandsmitgliedDTO
     */
    'anwesend'?: boolean;
}

export const WahlvorstandsmitgliedDTOFunktionEnum = {
    W: 'W',
    Sb: 'SB',
    Swb: 'SWB',
    Ssb: 'SSB',
    B: 'B'
} as const;

export type WahlvorstandsmitgliedDTOFunktionEnum = typeof WahlvorstandsmitgliedDTOFunktionEnum[keyof typeof WahlvorstandsmitgliedDTOFunktionEnum];

/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * WahlvorstandControllerApi - axios parameter creator
 * @export
 */
export const WahlvorstandControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden des Wahlvorstandes
         * @param {string} wahlbezirkID 
         * @param {boolean} [forceupdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlvorstand: async (wahlbezirkID: string, forceupdate?: boolean, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getWahlvorstand', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/wahlvorstand/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            if (forceupdate != null) {
                localVarHeaderParameter['forceupdate'] = typeof forceupdate === 'string'
                    ? forceupdate
                    : JSON.stringify(forceupdate);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisieren des Wahlvorstandes
         * @param {string} wahlbezirkID 
         * @param {WahlvorstandWriteDTO} wahlvorstandWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlvorstand: async (wahlbezirkID: string, wahlvorstandWriteDTO: WahlvorstandWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postWahlvorstand', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'wahlvorstandWriteDTO' is not null or undefined
            assertParamExists('postWahlvorstand', 'wahlvorstandWriteDTO', wahlvorstandWriteDTO)
            const localVarPath = `/businessActions/wahlvorstand/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wahlvorstandWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahlvorstandControllerApi - functional programming interface
 * @export
 */
export const WahlvorstandControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahlvorstandControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden des Wahlvorstandes
         * @param {string} wahlbezirkID 
         * @param {boolean} [forceupdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahlvorstand(wahlbezirkID: string, forceupdate?: boolean, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WahlvorstandDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahlvorstand(wahlbezirkID, forceupdate, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlvorstandControllerApi.getWahlvorstand']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisieren des Wahlvorstandes
         * @param {string} wahlbezirkID 
         * @param {WahlvorstandWriteDTO} wahlvorstandWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWahlvorstand(wahlbezirkID: string, wahlvorstandWriteDTO: WahlvorstandWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WahlvorstandDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postWahlvorstand(wahlbezirkID, wahlvorstandWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlvorstandControllerApi.postWahlvorstand']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahlvorstandControllerApi - factory interface
 * @export
 */
export const WahlvorstandControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahlvorstandControllerApiFp(configuration)
    return {
        /**
         * Laden des Wahlvorstandes
         * @param {string} wahlbezirkID 
         * @param {boolean} [forceupdate] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlvorstand(wahlbezirkID: string, forceupdate?: boolean, options?: RawAxiosRequestConfig): AxiosPromise<WahlvorstandDTO> {
            return localVarFp.getWahlvorstand(wahlbezirkID, forceupdate, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisieren des Wahlvorstandes
         * @param {string} wahlbezirkID 
         * @param {WahlvorstandWriteDTO} wahlvorstandWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlvorstand(wahlbezirkID: string, wahlvorstandWriteDTO: WahlvorstandWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<WahlvorstandDTO> {
            return localVarFp.postWahlvorstand(wahlbezirkID, wahlvorstandWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahlvorstandControllerApi - object-oriented interface
 * @export
 * @class WahlvorstandControllerApi
 * @extends {BaseAPI}
 */
export class WahlvorstandControllerApi extends BaseAPI {
    /**
     * Laden des Wahlvorstandes
     * @param {string} wahlbezirkID 
     * @param {boolean} [forceupdate] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlvorstandControllerApi
     */
    public getWahlvorstand(wahlbezirkID: string, forceupdate?: boolean, options?: RawAxiosRequestConfig) {
        return WahlvorstandControllerApiFp(this.configuration).getWahlvorstand(wahlbezirkID, forceupdate, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisieren des Wahlvorstandes
     * @param {string} wahlbezirkID 
     * @param {WahlvorstandWriteDTO} wahlvorstandWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlvorstandControllerApi
     */
    public postWahlvorstand(wahlbezirkID: string, wahlvorstandWriteDTO: WahlvorstandWriteDTO, options?: RawAxiosRequestConfig) {
        return WahlvorstandControllerApiFp(this.configuration).postWahlvorstand(wahlbezirkID, wahlvorstandWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



