### init Sth
POST {{ WLS_EAI_SERVICE_URL }}/initData/wahltage
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahltagInitRequests": [
    {
      "beschreibung": "Wahltag 1.1",
      "nummer": "1",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "name": "OBW",
          "wahlart": "OBW",
          "stimmzettelgebietInitOptions": [
            {
              "name": "szg w1.1",
              "nummer": "100",
              "stimmzettelgebietsart": "SB",
              "wahlbezirkOptions": [
                {
                  "nummer": "wbz 100_1",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 100_2",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 100_3",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                }
              ],
              "wahlvorschlagInitOptions": {
                "kandidatenMaxCount": 5,
                "kandidatenMinCount": 5,
                "wahlvorschlaegeMinCount": 5,
                "wahlvorschlaegeMaxCount": 5
              }
            },
            {
              "name": "szg w1.2",
              "nummer": "101",
              "stimmzettelgebietsart": "SB",
              "wahlbezirkOptions": [
                {
                  "nummer": "wbz 101_1",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 101_2",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 101_3",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                }
              ],
              "wahlvorschlagInitOptions": {
                "kandidatenMaxCount": 0,
                "kandidatenMinCount": 0,
                "wahlvorschlaegeMinCount": 0,
                "wahlvorschlaegeMaxCount": 0
              }
            }
          ]
        }
      ]
    },
    {
      "beschreibung": "Wahltag 1.2",
      "nummer": "2",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "wahlart": "SRW",
          "name": "Stadtratswahl",
          "stimmzettelgebietInitOptions": [
            {
              "name": "szg w2.1",
              "nummer": "200",
              "stimmzettelgebietsart": "SB",
              "wahlbezirkOptions": [
                {
                  "nummer": "wbz 200_1",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 200_2",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 200_3",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                }
              ],
              "wahlvorschlagInitOptions": {
                "kandidatenMaxCount": 0,
                "kandidatenMinCount": 0,
                "wahlvorschlaegeMinCount": 0,
                "wahlvorschlaegeMaxCount": 0
              }
            },
            {
              "name": "szg w2.2",
              "nummer": "201",
              "stimmzettelgebietsart": "SB",
              "wahlbezirkOptions": [
                {
                  "nummer": "wbz 201_1",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 201_2",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 201_3",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                }
              ],
              "wahlvorschlagInitOptions": {
                "kandidatenMaxCount": 0,
                "kandidatenMinCount": 0,
                "wahlvorschlaegeMinCount": 0,
                "wahlvorschlaegeMaxCount": 0
              }
            }
          ]
        }
      ]
    },
    {
      "beschreibung": "Wahltag 1.3",
      "nummer": "3",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "name": "Bezirksausschusswahl",
          "wahlart": "BZW",
          "stimmzettelgebietInitOptions": [
            {
              "name": "szg w3.1",
              "nummer": "300",
              "stimmzettelgebietsart": "SB",
              "wahlbezirkOptions": [
                {
                  "nummer": "wbz 300_1",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 300_2",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 300_3",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                }
              ],
              "wahlvorschlagInitOptions": {
                "kandidatenMaxCount": 0,
                "kandidatenMinCount": 0,
                "wahlvorschlaegeMinCount": 0,
                "wahlvorschlaegeMaxCount": 0
              }
            },
            {
              "name": "szg w3.2",
              "nummer": "301",
              "stimmzettelgebietsart": "SB",
              "wahlbezirkOptions": [
                {
                  "nummer": "wbz 301_1",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 301_2",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                },
                {
                  "nummer": "wbz 301_3",
                  "a1": 0,
                  "a2": 0,
                  "a3": 0,
                  "wahlbezirkArt": "UWB"
                }
              ],
              "wahlvorschlagInitOptions": {
                "kandidatenMaxCount": 0,
                "kandidatenMinCount": 0,
                "wahlvorschlaegeMinCount": 0,
                "wahlvorschlaegeMaxCount": 0
              }
            }
          ]
        }
      ]
    }
  ]
}
