### init Sth
POST {{ WLS_EAI_SERVICE_URL }}/initData/wahltage
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahltagInitRequests": [
    {
      "beschreibung": "Wahltag 1.1",
      "nummer": "1",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "name": "OBW",
          "wahlart": "OBW",
          "stimmzettelgebietInitOptions": [
            {
              "name": "szg w1.1",
              "nummer": "100",
              "stimmzettelgebietsart": "SG",
              "randomWahlbezirke": {
                "a1": {
                  "min": 10,
                  "max": 20
                },
                "a2": {
                  "min": 10,
                  "max": 20
                },
                "a3": {
                  "min": 10,
                  "max": 20
                },
                "uwb": {
                  "min": 20,
                  "max": 20
                },
                "bwb": {
                  "min": 10,
                  "max": 20
                }
              },
              "wahlvorschlagInitOptions": {
                "kandidatenMinCount": 1,
                "kandidatenMaxCount": 1,
                "wahlvorschlaegeMinCount": 5,
                "wahlvorschlaegeMaxCount": 5
              }
            }
          ]
        }
      ]
    },
    {
      "beschreibung": "Wahltag 1.2",
      "nummer": "2",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "wahlart": "SRW",
          "name": "Stadtratswahl",
          "stimmzettelgebietInitOptions": [
            {
              "name": "szg w2.1",
              "nummer": "200",
              "stimmzettelgebietsart": "SG",
              "randomWahlbezirke": {
                "a1": {
                  "min": 10,
                  "max": 20
                },
                "a2": {
                  "min": 10,
                  "max": 20
                },
                "a3": {
                  "min": 10,
                  "max": 20
                },
                "uwb": {
                  "min": 20,
                  "max": 20
                },
                "bwb": {
                  "min": 10,
                  "max": 20
                }
              },
              "wahlvorschlagInitOptions": {
                "kandidatenMinCount": 40,
                "kandidatenMaxCount": 80,
                "wahlvorschlaegeMinCount": 10,
                "wahlvorschlaegeMaxCount": 10
              }
            }
          ]
        }
      ]
    },
    {
      "beschreibung": "Wahltag 1.3",
      "nummer": "3",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "name": "Bezirksausschusswahl",
          "wahlart": "BZW",
          "randomStimmzettelgebiete": {
            "stimmzettelgebietsart": "SB",
            "count": {
              "min": 25,
              "max": 25
            },
            "randomWahlbezirke": {
              "a1": {
                "min": 10,
                "max": 20
              },
              "a2": {
                "min": 10,
                "max": 20
              },
              "a3": {
                "min": 10,
                "max": 20
              },
              "uwb": {
                "min": 20,
                "max": 20
              },
              "bwb": {
                "min": 10,
                "max": 20
              }
            },
            "wahlvorschlagInitOptions": {
              "kandidatenMaxCount": 5,
              "kandidatenMinCount": 7,
              "wahlvorschlaegeMinCount": 3,
              "wahlvorschlaegeMaxCount": 7
            }
          }
        }
      ]
    }
  ]
}

