### init BZW
POST {{ WLS_EAI_SERVICE_URL }}/initData/wahltage
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahltagInitRequests": [
    {
      "beschreibung": "BZW",
      "nummer": "3",
      "wahltag": "2026-01-01",
      "wahlInitOptions": [
        {
          "name": "Bezirksausschusswahl",
          "wahlart": "BZW",
          "randomStimmzettelgebiete": {
            "stimmzettelgebietsart": "SB",
            "count": {
              "min": 25,
              "max": 25
            },
            "randomWahlbezirke": {
              "a1": {
                "min": 10,
                "max": 20
              },
              "a2": {
                "min": 10,
                "max": 20
              },
              "a3": {
                "min": 10,
                "max": 20
              },
              "uwb": {
                "min": 20,
                "max": 20
              },
              "bwb": {
                "min": 10,
                "max": 20
              }
            },
            "wahlvorschlagInitOptions": {
              "kandidatenMaxCount": 5,
              "kandidatenMinCount": 7,
              "wahlvorschlaegeMinCount": 3,
              "wahlvorschlaegeMaxCount": 7
            }
          }
        }
      ]
    }
  ]
}

