### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorschlaege | user wls_all_uwb
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/28039463-3d3d-4ce5-acc1-0bef931a4409/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorschlaege | user wls_all_bwb
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/28039463-3d3d-4ce5-acc1-0bef931a4409/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorschlaege with non existing 'wahlID' and 'wahlbezirkID' not found
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/wahlID_X/wahlbezirkID_X
Authorization: Bearer {{$auth.token("auth-service")}}


### GET Wahlvorschlaegeliste | user wls_all_uwb
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/28039463-3d3d-4ce5-acc1-0bef931a4409/liste?forDate=2026-01-01
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorschlaegeliste | user wls_all_bwb
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/28039463-3d3d-4ce5-acc1-0bef931a4409/liste?forDate=2026-01-01
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorschlaegeliste for non existing 'wahlID' not found
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/wahlID_X/liste?forDate=2026-01-01
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorschlaegeliste for non existing 'forDate'not found
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/00000000-0000-0000-0000-000000000001/liste?forDate=2024-10-11
Authorization: Bearer {{$auth.token("auth-service")}}


### GET Referendumvorlagen | user wls_all_uwb
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/referendum/28039463-3d3d-4ce5-acc1-0bef931a4409/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Referendumvorlagen | user wls_all_bwb
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/referendum/28039463-3d3d-4ce5-acc1-0bef931a4409/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Referendumvorlagen for non existing 'wahlID' not found
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/referendum/wahlID_X/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Referendumvorlagen for non existing 'wahlbezirkID' not found
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/referendum/28039463-3d3d-4ce5-acc1-0bef931a4409/wahlbezirkID_X
Authorization: Bearer {{$auth.token("auth-service")}}