### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorstand wbz1
GET {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende?wahlbezirkID=00000000-0000-0000-0000-000000000001
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorstand wbz2
GET {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende?wahlbezirkID=00000000-0000-0000-0000-000000000002
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorstand wbz3
GET {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende?wahlbezirkID=00000000-0000-0000-0000-000000000003
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorstand wbz4
GET {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende?wahlbezirkID=00000000-0000-0000-0000-000000000004
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Wahlvorstand not found
GET {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende?wahlbezirkID=00000000-9999-0000-0000-000000000000
Authorization: Bearer {{$auth.token("auth-service")}}

### PUT Update Wahlvorstand wbz4
PUT {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende/anwesenheit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "00000000-0000-0000-0000-000000000004",
  "anwesenheitBeginn": "2024-06-14T19:01:12.456",
  "mitglieder": [
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000001"
    },
    {
      "anwesend": false,
      "identifikator": "00000000-0000-0000-0004-000000000002"
    },
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000003"
    },
    {
      "anwesend": false,
      "identifikator": "00000000-0000-0000-0004-000000000004"
    },
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000005"
    }
  ]
}

### PUT Update - bezirkID fehlt
PUT {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende/anwesenheit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "anwesenheitBeginn": "2024-06-14T19:01:12.456",
  "mitglieder": [
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000001"
    },
    {
      "anwesend": false,
      "identifikator": "00000000-0000-0000-0004-000000000002"
    },
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000003"
    },
    {
      "anwesend": false,
      "identifikator": "00000000-0000-0000-0004-000000000004"
    },
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000005"
    }
  ]
}

### PUT Update - anwesenheitBeginn fehlt
PUT {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende/anwesenheit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "00000000-0000-0000-0000-000000000004",
  "mitglieder": [
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000001"
    },
    {
      "anwesend": false,
      "identifikator": "00000000-0000-0000-0004-000000000002"
    },
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000003"
    },
    {
      "anwesend": false,
      "identifikator": "00000000-0000-0000-0004-000000000004"
    },
    {
      "anwesend": true,
      "identifikator": "00000000-0000-0000-0004-000000000005"
    }
  ]
}

### PUT Update - Identifikator fehlt
PUT {{ WLS_EAI_SERVICE_URL }}/wahlvorstaende/anwesenheit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "00000000-0000-0000-0000-000000000004",
  "anwesenheitBeginn": "2024-06-14T19:01:12.456",
  "mitglieder": [
    {
      "anwesend": true
    }
  ]
}