### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST Create - Set Wahlbeteiligung
POST {{ WLS_EAI_SERVICE_URL }}/wahlbeteiligung
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlID": "wahlID1",
  "wahlbezirkID": "00000000-0000-0000-0000-000000000001",
  "anzahlWaehler": 150,
  "meldeZeitpunkt": "2024-07-18T09:10:31.179Z"
}

### POST Create - Error: Set Wahlbeteiligung without wahlID
POST {{ WLS_EAI_SERVICE_URL }}/wahlbeteiligung
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlID": "",
  "wahlbezirkID": "00000000-0000-0000-0000-000000000001",
  "anzahlWaehler": 150,
  "meldeZeitpunkt": "2024-07-18T09:10:31.179Z"
}

### POST Create - Error: Set Wahlbeteiligung without wahlbezirkID
POST {{ WLS_EAI_SERVICE_URL }}/wahlbeteiligung
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlID": "wahlID1",
  "wahlbezirkID": "",
  "anzahlWaehler": 150,
  "meldeZeitpunkt": "2024-07-18T09:10:31.179Z"
}

### POST Create - Error: Set Wahlbeteiligung without meldeZeitpunkt
POST {{ WLS_EAI_SERVICE_URL }}/wahlbeteiligung
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlID": "wahlID1",
  "wahlbezirkID": "00000000-0000-0000-0000-000000000001",
  "anzahlWaehler": 150,
  "meldeZeitpunkt": ""
}