POST {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

password = test &
grant_type = password &
client_secret = top-secret &
client_id = wls &
username = wls_all

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}

### get userinfo with auth_token
GET {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/userinfo
Authorization: {{ token_type }} {{ auth_token }}

### GET Wahlvorschlaege
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/wahlID_007/wahlbezirkID_007
Authorization: {{ token_type }} {{ auth_token }}

### GET Wahlvorschlaege not found
GET {{ WLS_EAI_SERVICE_URL }}/vorschlaege/wahl/wahlID_4711/wahlbezirkID_4711
Authorization: {{ token_type }} {{ auth_token }}
