POST http://localhost:8100/auth/realms/wls_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

password = test &
grant_type = password &
client_secret = top-secret &
client_id = wls &
username = wls_all

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}

### get userinfo with auth_token
GET http://localhost:8100/auth/realms/wls_realm/protocol/openid-connect/userinfo
Authorization: {{ token_type }} {{ auth_token }}

### GET wbzID-1/1
GET http://localhost:39150/businessActions/waehlerverzeichnis/wbzID-1/1
Authorization: {{ token_type }} {{ auth_token }}

### GET wbzID-1/2
GET http://localhost:39150/businessActions/waehlerverzeichnis/wbzID-1/2
Authorization: {{ token_type }} {{ auth_token }}

### POST wbzID-1/1
POST http://localhost:39150/businessActions/waehlerverzeichnis/wbzID-1/1
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "verzeichnisLagVor": true,
  "berichtigungVorBeginnDerAbstimmung": true,
  "nachtraeglicheBerichtigung": true,
  "mitteilungUeberUngueltigeWahlscheineErhalten": true
}

### POST wbzID-1/2
POST http://localhost:39150/businessActions/waehlerverzeichnis/wbzID-1/2
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "verzeichnisLagVor": false,
  "berichtigungVorBeginnDerAbstimmung": false,
  "nachtraeglicheBerichtigung": true,
  "mitteilungUeberUngueltigeWahlscheineErhalten": true
}