server:
  ssl:
    key-store: file:../stack/cert/keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: springboot
    enabled: true
  servlet:
    session:
      timeout: 259200
      tracking-modes: 'cookie'
      cookie:
        max-age: -1
        http-only: true
        secure: true
        same-site: none
        # domain: "kubernetes.docker.internal"
        # path: "/"
