spring:
  application.name: @project.artifactId@
  banner.location: banner.txt
  profiles:
    group:
      dummy.clients:
        - dummy.ldap
      local:
        - plainTextLogging
      standalone:
        - db-h2
        - dummy.clients
        - dummy.nobezirkid.check
  flyway:
    locations:
      - classpath:db/migrations/{vendor}
  h2.console.enabled: false
  session:
    jdbc:
      table-name: SPRING_SESSION

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all

server:
  shutdown: "graceful"
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  max-http-request-header-size: 32KB
  servlet:
    session:
      timeout: 259200
      tracking-modes: 'cookie'
      cookie:
        max-age: -1
        http-only: true
        secure: false

# Config for spring actuator endpoints
management:
  server.port: ${server.port}
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
      path-mapping:
        prometheus: metrics
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
  info:
    env:
      enabled: true
info.application.name: @project.artifactId@
info.application.version: @project.version@

service:
  config:
    crypto:
      encryptionPrefix: "ENCRYPTED:"
    maxLoginAttempts: 5
    clients:
      infomanagement:
        basepath: http://localhost:8201
        configkey:
          welcomeMessage: WILLKOMMENSTEXT
          fruehesterLogin: FRUEHESTE_LOGIN_UHRZEIT
          spaetesterLogin: SPAETESTE_LOGIN_UHRZEIT
        dateformat: dd.MM.yyyy HH:mm
    falscheLoginZeitstrafe: 10
    ldap:
      userDn:
      userDnPassword:
      contextSource:
      userSearchBase: ou=people
      userSearchFilter: uid={0}
    loginCheckMessage: notInActiveElectionDay
    oauth2:
      clients:
        wahllokalgui:
          id: wls
        admingui:
          id: admingui

    welcomemessage:
      default: "Willkommen zur Wahl!"
    user:
      anzahlPinBloecke: 4
      countCharsPrefix: 6
      countNumbersPin: 4
      csv:
        eol: "\r\n"
      authority:
        wahlvorstand: WLS_WAHLVORSTAND
      prefixChars: "23456789abcdefghjkmnpqrstuvwxyz"
  info:
    oid: AUTH-SERVICE