

server:
  port: 8100
  servlet:
    context-path: /uaa

service:
  config:
    crypto:
      key: "please change me"
    oauth2:
      jwk:
        rsa:
          init:
            seed: change_me

management:
  endpoints:
    access:
      default: read_only # Required for local debugging via JMX+RMI, additionally might have to set -Djava.rmi.server.hostname=localhost as JVM arguments
