# only values that differ from default are listed here
reviews:
  high_level_summary_placeholder: ''
  auto_title_placeholder: ''
  poem: false
  changed_files_summary: false
  sequence_diagrams: false
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  auto_review:
    auto_incremental_review: false
  tools:
    shellcheck:
      enabled: false
    ruff:
      enabled: false
    markdownlint:
      enabled: false
    github-checks:
      enabled: false
    languagetool:
      enabled: false
    biome:
      enabled: false
    hadolint:
      enabled: false
    swiftlint:
      enabled: false
    phpstan:
      enabled: false
    golangci-lint:
      enabled: false
    yamllint:
      enabled: false
    gitleaks:
      enabled: false
    checkov:
      enabled: false
    detekt:
      enabled: false
    eslint:
      enabled: false
    rubocop:
      enabled: false
    buf:
      enabled: false
    regal:
      enabled: false
    actionlint:
      enabled: false
    pmd:
      enabled: false
    cppcheck:
      enabled: false
    semgrep:
      enabled: false
    circleci:
      enabled: false
chat:
  auto_reply: false
knowledge_base:
  learnings:
    scope: local
  issues:
    scope: local
  pull_requests:
    scope: local
