spring:
  datasource:
    username: wls_briefwahl_service
    password: secret
    url: jdbc:postgresql://localhost:5432/wls_briefwahl_service
  flyway:
    enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true

