-- ${flyway:timestamp}
/*
Wenn wir das System in dem Zustand bringen wollen, dass die Benutzer keine Daten angelegt haben, aber
die Wahleinrichtung via Admintool nicht erneut stattfinden soll, müssen wir alles löschen außer:
AWERTE.

 */
TRUNCATE TABLE AUSDRUCK;
TRUNCATE TABLE BEGRUENDUNG;
TRUNCATE TABLE EINGENOMMENEWAHLSCHEINE;
TRUNCATE TABLE ERGEBNISSAMMLUNG;
TRUNCATE TABLE ERGEBNISSE;
TRUNCATE TABLE STATUS;
TRUNCATE TABLE STIMMZETTEL;
TRUNCATE TABLE STIMMZETTELUMSCHLAEGE;
TRUNCATE TABLE VERMERK;
TRUNCATE TABLE WAHLSCHEINE;
TRUNCATE TABLE STIMMABGABEVERMERKE;
TRUNCATE TABLE BEDENKLICHESTIMMZETTELERFASSUNG;
TRUNCATE TABLE BEDENKLICHERSTIMMZETTEL;