### get user
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Broadcast Message for user wls_komw_uwb + wls_komw_bwb
POST {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/broadcast
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkIDs": [
    "9899cae4-df9a-4ffc-a940-f20cf2280171",
    "9081145c-dc16-4a9b-8255-5c49ddb98c14"
  ],
  "nachricht": "Hallo welt"
}

### Get message | user wls_komw_uwb
GET {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/getMessage/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

> {%
    client.global.set("nachrichtID", response.body.oid);
%}


### Get message | user wls_komw_bwb
GET {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/getMessage/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

> {%
    client.global.set("nachrichtID", response.body.oid);
%}

### Delete lastest | (get message oid from GET request) | user wls_komw_uwb + wls_komw_bwb
POST  {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/messageRead/{{nachrichtID}}
Authorization: Bearer {{$auth.token("auth-service")}}

