### get user "wls_all"
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Broadcast Message for wbz-1 and wbz-2
POST {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/broadcast
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkIDs": [
    "wbz-1",
    "wbz-2"
  ],
  "nachricht": "Hallo welt"
}

###
POST {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/broadcast
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkIDs": [
    "wbz-1",
    "wbz-3"
  ],
  "nachricht": "grüß gott"
}

### Get message for wbz-1
GET {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/getMessage/wbz-1
Authorization: Bearer {{$auth.token("auth-service")}}

> {%
    client.global.set("nachrichtID", response.body.oid);
    client.global.set("wbzID", response.body.wahlbezirkID);
%}

### Get message for wbz-2
GET {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/getMessage/{{wbzID}}
Authorization: Bearer {{$auth.token("auth-service")}}

### Get message for wbz-x
GET {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/getMessage/wbz-x
Authorization: Bearer {{$auth.token("auth-service")}}

### Delete lastest for wbz-1
POST  {{ WLS_BROADCAST_SERVICE_URL }}/businessActions/messageRead/{{nachrichtID}}
Authorization: Bearer {{$auth.token("auth-service")}}

