-- ${flyway:timestamp}
/*
Wenn wir das System in dem Zustand bringen wollen, dass die Benutzer keine Daten angelegt haben, aber
die Wahleinrichtung via Admintool nicht erneut stattfinden soll, müssen wir alle Tabellen leeren:

 */

TRUNCATE TABLE BWVORBEREITUNG_URNEN;
TRUNCATE TABLE BRIEFWAHLVORBEREITUNG;
TRUNCATE TABLE EROEFFNUNGSUHRZEIT;
TRUNCATE TABLE FORTSETZUNGSUHRZEIT;
TRUNCATE TABLE UNTERBRECHUNGSUHRZEIT;
TRUNCATE TABLE URNENWAHLSCHLIESSUNGSUHRZEIT;
TRUNCATE TABLE UWVORBEREITUNG_URNEN;
TRUNCATE TABLE URNENWAHLVORBEREITUNG;
TRUNCATE TABLE WAEHLERVERZEICHNIS;


