### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### get konfiguration WILLKOMMENSTEXT
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfiguration/WILLKOMMENSTEXT
Authorization: Bearer {{$auth.token("auth-service")}}

### POST konfiguration WILLKOMMENSTEXT
POST {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfiguration/WILLKOMMENSTEXT
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wert": "neuer Willkommenstext",
  "beschreibung": "neuer Beschreibung",
  "standardwert": "neuer Standardwert"
}

### get konfiguration FRUEHESTE_EROEFFNUNGSZEIT
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfiguration/FRUEHESTE_EROEFFNUNGSZEIT
Authorization: Bearer {{$auth.token("auth-service")}}

### get KENNBUCHSTABEN
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/kennbuchstaben
Authorization: Bearer {{$auth.token("auth-service")}}

### get wilkommenstext as anonymous
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfigurationUnauthorized/WILLKOMMENSTEXT