### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### get konfigurierter Wahltag
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfigurierterWahltag
Authorization: Bearer {{$auth.token("auth-service")}}

### get konfigurierte Wahltage
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfigurierteWahltage
Authorization: Bearer {{$auth.token("auth-service")}}

### post konfigurierter Wahltag EU-Wahl-24
POST {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfigurierterWahltag
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahltag": "2024-06-09",
  "wahltagID": "euwahl24",
  "wahltagStatus": "AKTIV",
  "nummer": "nummer"
}

### POST konfigurierter Wahltag BTW-21
POST {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfigurierterWahltag
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahltag": "2021-09-26",
  "wahltagID": "BTW-21",
  "wahltagStatus": "AKTIV",
  "nummer": "nummer2"
}

### DELETE konfigurierter Wahltag BTW-21
DELETE {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/konfigurierterWahltag/BTW-21
Authorization: Bearer {{$auth.token("auth-service")}}

### check is aktive
GET {{ WLS_INFOMANAGEMENT_SERVICE_URL }}/businessActions/loginCheck/BTW-21