/* tslint:disable */
/* eslint-disable */
/**
 * Broadcast Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BroadcastMessageDTO
 */
export interface BroadcastMessageDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof BroadcastMessageDTO
     */
    'wahlbezirkIDs': Array<string>;
    /**
     * 
     * @type {string}
     * @memberof BroadcastMessageDTO
     */
    'nachricht': string;
}
/**
 * 
 * @export
 * @interface MessageDTO
 */
export interface MessageDTO {
    /**
     * 
     * @type {string}
     * @memberof MessageDTO
     */
    'oid': string;
    /**
     * 
     * @type {string}
     * @memberof MessageDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof MessageDTO
     */
    'nachricht': string;
    /**
     * 
     * @type {string}
     * @memberof MessageDTO
     */
    'empfangsZeit': string;
}

/**
 * BroadcastControllerApi - axios parameter creator
 * @export
 */
export const BroadcastControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Bietet einen Endpunkt an, der eine Nachricht für alle Wahlbezirke(Wahllokale) bereitstellt.
         * @summary Nachricht an alle senden
         * @param {BroadcastMessageDTO} broadcastMessageDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        broadcast: async (broadcastMessageDTO: BroadcastMessageDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'broadcastMessageDTO' is not null or undefined
            assertParamExists('broadcast', 'broadcastMessageDTO', broadcastMessageDTO)
            const localVarPath = `/businessActions/broadcast`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(broadcastMessageDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Löscht die Nachricht mit der gegebenen ID, nachdem sie gelesen wurde. Es wird nur der dem entsprechenden Wahllokal zugewiesene Datenbankeintrag.
         * @summary Nachricht löschen
         * @param {string} nachrichtID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessage: async (nachrichtID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'nachrichtID' is not null or undefined
            assertParamExists('deleteMessage', 'nachrichtID', nachrichtID)
            const localVarPath = `/businessActions/messageRead/{nachrichtID}`
                .replace(`{${"nachrichtID"}}`, encodeURIComponent(String(nachrichtID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sucht nach der ältesten Nachricht für die gegebene Wahlbezirk-Id und gibt diese zurück.
         * @summary Letzte Nachricht lesen
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessage: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getMessage', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/getMessage/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BroadcastControllerApi - functional programming interface
 * @export
 */
export const BroadcastControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BroadcastControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Bietet einen Endpunkt an, der eine Nachricht für alle Wahlbezirke(Wahllokale) bereitstellt.
         * @summary Nachricht an alle senden
         * @param {BroadcastMessageDTO} broadcastMessageDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async broadcast(broadcastMessageDTO: BroadcastMessageDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.broadcast(broadcastMessageDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BroadcastControllerApi.broadcast']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Löscht die Nachricht mit der gegebenen ID, nachdem sie gelesen wurde. Es wird nur der dem entsprechenden Wahllokal zugewiesene Datenbankeintrag.
         * @summary Nachricht löschen
         * @param {string} nachrichtID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMessage(nachrichtID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMessage(nachrichtID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BroadcastControllerApi.deleteMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sucht nach der ältesten Nachricht für die gegebene Wahlbezirk-Id und gibt diese zurück.
         * @summary Letzte Nachricht lesen
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getMessage(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<MessageDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getMessage(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BroadcastControllerApi.getMessage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BroadcastControllerApi - factory interface
 * @export
 */
export const BroadcastControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BroadcastControllerApiFp(configuration)
    return {
        /**
         * Bietet einen Endpunkt an, der eine Nachricht für alle Wahlbezirke(Wahllokale) bereitstellt.
         * @summary Nachricht an alle senden
         * @param {BroadcastMessageDTO} broadcastMessageDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        broadcast(broadcastMessageDTO: BroadcastMessageDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.broadcast(broadcastMessageDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Löscht die Nachricht mit der gegebenen ID, nachdem sie gelesen wurde. Es wird nur der dem entsprechenden Wahllokal zugewiesene Datenbankeintrag.
         * @summary Nachricht löschen
         * @param {string} nachrichtID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteMessage(nachrichtID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMessage(nachrichtID, options).then((request) => request(axios, basePath));
        },
        /**
         * Sucht nach der ältesten Nachricht für die gegebene Wahlbezirk-Id und gibt diese zurück.
         * @summary Letzte Nachricht lesen
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getMessage(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<MessageDTO> {
            return localVarFp.getMessage(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BroadcastControllerApi - object-oriented interface
 * @export
 * @class BroadcastControllerApi
 * @extends {BaseAPI}
 */
export class BroadcastControllerApi extends BaseAPI {
    /**
     * Bietet einen Endpunkt an, der eine Nachricht für alle Wahlbezirke(Wahllokale) bereitstellt.
     * @summary Nachricht an alle senden
     * @param {BroadcastMessageDTO} broadcastMessageDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastControllerApi
     */
    public broadcast(broadcastMessageDTO: BroadcastMessageDTO, options?: RawAxiosRequestConfig) {
        return BroadcastControllerApiFp(this.configuration).broadcast(broadcastMessageDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Löscht die Nachricht mit der gegebenen ID, nachdem sie gelesen wurde. Es wird nur der dem entsprechenden Wahllokal zugewiesene Datenbankeintrag.
     * @summary Nachricht löschen
     * @param {string} nachrichtID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastControllerApi
     */
    public deleteMessage(nachrichtID: string, options?: RawAxiosRequestConfig) {
        return BroadcastControllerApiFp(this.configuration).deleteMessage(nachrichtID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sucht nach der ältesten Nachricht für die gegebene Wahlbezirk-Id und gibt diese zurück.
     * @summary Letzte Nachricht lesen
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BroadcastControllerApi
     */
    public getMessage(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return BroadcastControllerApiFp(this.configuration).getMessage(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }
}



