package de.muenchen.oss.wahllokalsystem.briefwahlservice.common.beanstandetewahlbriefe;

public enum Zurueckweisungsgrund {
    ZUGELASSEN, SCHEIN_UNGUELTIG, KEIN_ORIGINAL_SCHEIN, UNTERSCHRIFT_FEHLT, UMSCHLAG_FEHLT, LOSE_STIMMZETTEL, WAHLBRIEF_UND_UMSCHLAG_OFFEN, SCHEINE_UNGLEICH_UMSCHLAEGE, UMSCHLAG_NICHT_AMTLICH, UMSCHLAG_GEFAEHRDET_WAHLGEHEIMNIS, GEGENSTAND_IM_UMSCHLAG, NICHT_WAHLBERECHTIGT
}
