package de.muenchen.oss.wahllokalsystem.infomanagementservice.rest.konfiguration;

public enum KonfigurationKey {
    WLK_TIME_OUT,
    WILLKOMMENSTEXT,
    ABSCHLUSSTEXT,
    WAHLLOKALFINDER_URL,
    FRUEHESTE_LOGIN_UHRZEIT,
    SPAETESTE_LOGIN_UHRZEIT,
    FRUEHESTE_EROEFFNUNGSZEIT_UW,
    SPAETESTE_EROEFFNUNGSZEIT_UW,
    FRUEHESTE_SCHLIESSUNGSZEIT_UW,
    FRUEHESTE_EROEFFNUNGSZEIT_BW,
    SPAETESTE_EROEFFNUNGSZEIT_BW,
    FRUEHESTE_SCHLIESSUNGSZEIT_BW,
    MELDUNGSZEIT_WAHL_SCHLIESSEN,
    MELDUNGSZEIT_ANWESENHEIT_CHECK,
    KENNBUCHSTABEN,

    FRUEHESTE_EROEFFNUNGSZEIT,
    SPAETESTE_EROEFFNUNGSZEIT,
    FRUEHESTE_SCHLIESSUNGSZEIT
}
