### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### get wahleranzahl by wahlID and wahlbezirkID
GET {{ WLS_MONITORING_SERVICE_URL }}/businessActions/wahlbeteiligung/wahlID01/wahlbezirkID01
Authorization: Bearer {{$auth.token("auth-service")}}

### POST waehleranzahl
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/wahlbeteiligung/wahlID01/wahlbezirkID01
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlID": "wahlID01",
  "wahlbezirkID": "wahlbezirk01",
  "anzahlWaehler": 99,
  "uhrzeit": "2024-10-21T23:59:12.123"
}
