### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST lastSeen
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/lastSeen/wahlbezirkID01
Authorization: Bearer {{$auth.token("auth-service")}}

### POST lastSeen - parameter invalid, expected "Parameter unvollstaendig"
< {%
    request.variables.set("wahlbezirkID", "   ");
%}
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/lastSeen/{{wahlbezirkID}}
Authorization: Bearer {{$auth.token("auth-service")}}

### POST letzteAbmeldung
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/letzteAbmeldung/wahlbezirkID01
Authorization: Bearer {{$auth.token("auth-service")}}

### POST letzteAbmeldung - parameter invalid, expected "Parameter unvollstaendig"
< {%
    request.variables.set("wahlbezirkID", "   ");
%}
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/letzteAbmeldung/{{wahlbezirkID}}
Authorization: Bearer {{$auth.token("auth-service")}}

### POST schnellmeldungSendungsuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungSendungsuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST schnellmeldungSendungsuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungSendungsuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST schnellmeldungDruckuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungDruckuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}

### POST schnellmeldungDruckuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungDruckuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftSendungsuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftSendungsuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftSendungsuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftSendungsuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftDruckuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftDruckuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftDruckuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftDruckuhrzeit
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}
