### Get token wls_all
POST {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

password = test &
grant_type = password &
client_secret = top-secret &
client_id = wls &
username = wls_all

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}

### get userinfo with auth_token
GET {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/userinfo
Authorization: {{ token_type }} {{ auth_token }}

### POST lastSeen
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/lastSeen/wahlbezirkID01
Authorization: {{ token_type }} {{ auth_token }}

### POST lastSeen - parameter invalid, expected "Parameter unvollstaendig"
< {%
    request.variables.set("wahlbezirkID", "   ");
%}
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/lastSeen/{{wahlbezirkID}}
Authorization: {{ token_type }} {{ auth_token }}

### POST letzteAbmeldung
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/letzteAbmeldung/wahlbezirkID01
Authorization: {{ token_type }} {{ auth_token }}

### POST letzteAbmeldung - parameter invalid, expected "Parameter unvollstaendig"
< {%
    request.variables.set("wahlbezirkID", "   ");
%}
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/letzteAbmeldung/{{wahlbezirkID}}
Authorization: {{ token_type }} {{ auth_token }}

### POST schnellmeldungSendungsuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungSendungsuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST schnellmeldungSendungsuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungSendungsuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST schnellmeldungDruckuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungDruckuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}

### POST schnellmeldungDruckuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/schnellmeldungDruckuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftSendungsuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftSendungsuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftSendungsuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftSendungsuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "sendungsuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftDruckuhrzeit
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftDruckuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID01",
    "wahlbezirkID": "wahlbezirk01"
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}

### POST niederschriftDruckuhrzeit - parameter invalid, expected "Parameter unvollstaendig"
POST {{ WLS_MONITORING_SERVICE_URL }}/businessActions/niederschriftDruckuhrzeit
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "bezirkUndWahlID": {
    "wahlID": "",
    "wahlbezirkID": "   "
  },
  "druckuhrzeit": "2024-10-21T23:59:12.123"
}
