/* tslint:disable */
/* eslint-disable */
/**
 * Auth Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.9.0
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface OAuthServerSession {
    'username'?: string;
    'sessionId'?: string;
}
export interface OAuthServerSessions {
    'sessions'?: Array<OAuthServerSession>;
}
export interface ResolvedUrlDTO {
    'url': string;
}
export interface RoleMappingsDTO {
    'schriftfuehrung': string;
    'admin': string;
    'erfassungsteam': string;
}
export interface UserDTO {
    'username': string;
    'email'?: string;
    'userEnabled': boolean;
    'wahltagID'?: string;
    'wahltag'?: string;
    'wahlbezirkID'?: string;
    'wahlbezirkNummer'?: string;
    'wahlbezirksArt'?: UserDTOWahlbezirksArtEnum;
    'pin'?: string;
    'authorities': Array<string>;
    'wbid_wahlnummer'?: string;
    'teamID'?: string;
}

export const UserDTOWahlbezirksArtEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB',
} as const;

export type UserDTOWahlbezirksArtEnum = typeof UserDTOWahlbezirksArtEnum[keyof typeof UserDTOWahlbezirksArtEnum];

export interface WahllokalUserInfoDTO {
    'wahlbezirknummer'?: string;
    'wahltag'?: string;
    'wahlbezirkID'?: string;
    'wahlbezirksart'?: WahllokalUserInfoDTOWahlbezirksartEnum;
    'wbid_wahlnummer'?: string;
}

export const WahllokalUserInfoDTOWahlbezirksartEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB',
} as const;

export type WahllokalUserInfoDTOWahlbezirksartEnum = typeof WahllokalUserInfoDTOWahlbezirksartEnum[keyof typeof WahllokalUserInfoDTOWahlbezirksartEnum];

export interface WlsExceptionDTO {
    'category': WlsExceptionDTOCategoryEnum;
    'code': string;
    'service': string;
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I',
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * AuthServerControllerApi - axios parameter creator
 */
export const AuthServerControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogoutUrl: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/authserver/logouturl`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthServerControllerApi - functional programming interface
 */
export const AuthServerControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthServerControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLogoutUrl(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ResolvedUrlDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLogoutUrl(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuthServerControllerApi.getLogoutUrl']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuthServerControllerApi - factory interface
 */
export const AuthServerControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthServerControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLogoutUrl(options?: RawAxiosRequestConfig): AxiosPromise<ResolvedUrlDTO> {
            return localVarFp.getLogoutUrl(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuthServerControllerApi - object-oriented interface
 */
export class AuthServerControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getLogoutUrl(options?: RawAxiosRequestConfig) {
        return AuthServerControllerApiFp(this.configuration).getLogoutUrl(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * MainControllerApi - axios parameter creator
 */
export const MainControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hanelGetMapping: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/demo`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * MainControllerApi - functional programming interface
 */
export const MainControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MainControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async hanelGetMapping(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.hanelGetMapping(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MainControllerApi.hanelGetMapping']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MainControllerApi - factory interface
 */
export const MainControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MainControllerApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        hanelGetMapping(options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.hanelGetMapping(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * MainControllerApi - object-oriented interface
 */
export class MainControllerApi extends BaseAPI {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public hanelGetMapping(options?: RawAxiosRequestConfig) {
        return MainControllerApiFp(this.configuration).hanelGetMapping(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * RolesControllerApi - axios parameter creator
 */
export const RolesControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Lesen der Zuordnung technischer Rollenbezeichner zu fachlichen Rollen.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoleMappings: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/roles/mappings`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * RolesControllerApi - functional programming interface
 */
export const RolesControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RolesControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Lesen der Zuordnung technischer Rollenbezeichner zu fachlichen Rollen.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getRoleMappings(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<RoleMappingsDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRoleMappings(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolesControllerApi.getRoleMappings']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RolesControllerApi - factory interface
 */
export const RolesControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RolesControllerApiFp(configuration)
    return {
        /**
         * Lesen der Zuordnung technischer Rollenbezeichner zu fachlichen Rollen.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getRoleMappings(options?: RawAxiosRequestConfig): AxiosPromise<RoleMappingsDTO> {
            return localVarFp.getRoleMappings(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * RolesControllerApi - object-oriented interface
 */
export class RolesControllerApi extends BaseAPI {
    /**
     * Lesen der Zuordnung technischer Rollenbezeichner zu fachlichen Rollen.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getRoleMappings(options?: RawAxiosRequestConfig) {
        return RolesControllerApiFp(this.configuration).getRoleMappings(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * SessionControllerApi - axios parameter creator
 */
export const SessionControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Beenden einer Session.
         * @param {string} sessionID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        killSession: async (sessionID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sessionID' is not null or undefined
            assertParamExists('killSession', 'sessionID', sessionID)
            const localVarPath = `/oauthsessions/{sessionID}/invalidate`
                .replace('{sessionID}', encodeURIComponent(String(sessionID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Listet alle aktive Sessions auf.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listActiveSessions: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/oauthsessions/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SessionControllerApi - functional programming interface
 */
export const SessionControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SessionControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Beenden einer Session.
         * @param {string} sessionID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async killSession(sessionID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.killSession(sessionID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.killSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Listet alle aktive Sessions auf.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listActiveSessions(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OAuthServerSessions>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listActiveSessions(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SessionControllerApi.listActiveSessions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SessionControllerApi - factory interface
 */
export const SessionControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SessionControllerApiFp(configuration)
    return {
        /**
         * Beenden einer Session.
         * @param {string} sessionID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        killSession(sessionID: string, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.killSession(sessionID, options).then((request) => request(axios, basePath));
        },
        /**
         * Listet alle aktive Sessions auf.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listActiveSessions(options?: RawAxiosRequestConfig): AxiosPromise<OAuthServerSessions> {
            return localVarFp.listActiveSessions(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SessionControllerApi - object-oriented interface
 */
export class SessionControllerApi extends BaseAPI {
    /**
     * Beenden einer Session.
     * @param {string} sessionID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public killSession(sessionID: string, options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).killSession(sessionID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Listet alle aktive Sessions auf.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listActiveSessions(options?: RawAxiosRequestConfig) {
        return SessionControllerApiFp(this.configuration).listActiveSessions(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UserControllerApi - axios parameter creator
 */
export const UserControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Freischalten eines users.
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlockUser: async (username: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'username' is not null or undefined
            assertParamExists('unlockUser', 'username', username)
            const localVarPath = `/user/{username}/unlock`
                .replace('{username}', encodeURIComponent(String(username)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Liefert einen User.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        user: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/user`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UserControllerApi - functional programming interface
 */
export const UserControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UserControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Freischalten eines users.
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlockUser(username: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unlockUser(username, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserControllerApi.unlockUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Liefert einen User.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async user(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.user(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UserControllerApi.user']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UserControllerApi - factory interface
 */
export const UserControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UserControllerApiFp(configuration)
    return {
        /**
         * Freischalten eines users.
         * @param {string} username 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlockUser(username: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unlockUser(username, options).then((request) => request(axios, basePath));
        },
        /**
         * Liefert einen User.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        user(options?: RawAxiosRequestConfig): AxiosPromise<UserDTO> {
            return localVarFp.user(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UserControllerApi - object-oriented interface
 */
export class UserControllerApi extends BaseAPI {
    /**
     * Freischalten eines users.
     * @param {string} username 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unlockUser(username: string, options?: RawAxiosRequestConfig) {
        return UserControllerApiFp(this.configuration).unlockUser(username, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Liefert einen User.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public user(options?: RawAxiosRequestConfig) {
        return UserControllerApiFp(this.configuration).user(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahllokalBenutzerControllerApi - axios parameter creator
 */
export const WahllokalBenutzerControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Generiert Wahllokalbenutzer zum angegebenen Wahltag. Für jeden Benutzer der angelegt werden soll, muss eine WahllokalUserInfo im Body vorhanden sein. Als Antwort wird eine CSV-Liste mit den generierten Benutzernamen zurückgegeben.
         * @param {string} wahltagID 
         * @param {Array<WahllokalUserInfoDTO>} wahllokalUserInfoDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAndExportWahllokalBenutzer: async (wahltagID: string, wahllokalUserInfoDTO: Array<WahllokalUserInfoDTO>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('createAndExportWahllokalBenutzer', 'wahltagID', wahltagID)
            // verify required parameter 'wahllokalUserInfoDTO' is not null or undefined
            assertParamExists('createAndExportWahllokalBenutzer', 'wahllokalUserInfoDTO', wahllokalUserInfoDTO)
            const localVarPath = `/generateAndExportWahllokalbenutzer/{wahltagID}`
                .replace('{wahltagID}', encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wahllokalUserInfoDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Löscht alle Wahllokalbenutzer zum angegebenen Wahltag unwiederruflich.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWahllokalBenutzer: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('deleteWahllokalBenutzer', 'wahltagID', wahltagID)
            const localVarPath = `/deleteWahllokalbenutzer/{wahltagID}`
                .replace('{wahltagID}', encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Liefert einen CSV-String der alle Wahllokalbenutzernamen zum angegebenen Wahltag enthält.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportWahllokalBenutzer: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('exportWahllokalBenutzer', 'wahltagID', wahltagID)
            const localVarPath = `/exportWahllokalbenutzer/{wahltagID}`
                .replace('{wahltagID}', encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,*/*';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahllokalBenutzerControllerApi - functional programming interface
 */
export const WahllokalBenutzerControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahllokalBenutzerControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Generiert Wahllokalbenutzer zum angegebenen Wahltag. Für jeden Benutzer der angelegt werden soll, muss eine WahllokalUserInfo im Body vorhanden sein. Als Antwort wird eine CSV-Liste mit den generierten Benutzernamen zurückgegeben.
         * @param {string} wahltagID 
         * @param {Array<WahllokalUserInfoDTO>} wahllokalUserInfoDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createAndExportWahllokalBenutzer(wahltagID: string, wahllokalUserInfoDTO: Array<WahllokalUserInfoDTO>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createAndExportWahllokalBenutzer(wahltagID, wahllokalUserInfoDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalBenutzerControllerApi.createAndExportWahllokalBenutzer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Löscht alle Wahllokalbenutzer zum angegebenen Wahltag unwiederruflich.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWahllokalBenutzer(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWahllokalBenutzer(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalBenutzerControllerApi.deleteWahllokalBenutzer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Liefert einen CSV-String der alle Wahllokalbenutzernamen zum angegebenen Wahltag enthält.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportWahllokalBenutzer(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportWahllokalBenutzer(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalBenutzerControllerApi.exportWahllokalBenutzer']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahllokalBenutzerControllerApi - factory interface
 */
export const WahllokalBenutzerControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahllokalBenutzerControllerApiFp(configuration)
    return {
        /**
         * Generiert Wahllokalbenutzer zum angegebenen Wahltag. Für jeden Benutzer der angelegt werden soll, muss eine WahllokalUserInfo im Body vorhanden sein. Als Antwort wird eine CSV-Liste mit den generierten Benutzernamen zurückgegeben.
         * @param {string} wahltagID 
         * @param {Array<WahllokalUserInfoDTO>} wahllokalUserInfoDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createAndExportWahllokalBenutzer(wahltagID: string, wahllokalUserInfoDTO: Array<WahllokalUserInfoDTO>, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.createAndExportWahllokalBenutzer(wahltagID, wahllokalUserInfoDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Löscht alle Wahllokalbenutzer zum angegebenen Wahltag unwiederruflich.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWahllokalBenutzer(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteWahllokalBenutzer(wahltagID, options).then((request) => request(axios, basePath));
        },
        /**
         * Liefert einen CSV-String der alle Wahllokalbenutzernamen zum angegebenen Wahltag enthält.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportWahllokalBenutzer(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.exportWahllokalBenutzer(wahltagID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahllokalBenutzerControllerApi - object-oriented interface
 */
export class WahllokalBenutzerControllerApi extends BaseAPI {
    /**
     * Generiert Wahllokalbenutzer zum angegebenen Wahltag. Für jeden Benutzer der angelegt werden soll, muss eine WahllokalUserInfo im Body vorhanden sein. Als Antwort wird eine CSV-Liste mit den generierten Benutzernamen zurückgegeben.
     * @param {string} wahltagID 
     * @param {Array<WahllokalUserInfoDTO>} wahllokalUserInfoDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createAndExportWahllokalBenutzer(wahltagID: string, wahllokalUserInfoDTO: Array<WahllokalUserInfoDTO>, options?: RawAxiosRequestConfig) {
        return WahllokalBenutzerControllerApiFp(this.configuration).createAndExportWahllokalBenutzer(wahltagID, wahllokalUserInfoDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Löscht alle Wahllokalbenutzer zum angegebenen Wahltag unwiederruflich.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteWahllokalBenutzer(wahltagID: string, options?: RawAxiosRequestConfig) {
        return WahllokalBenutzerControllerApiFp(this.configuration).deleteWahllokalBenutzer(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Liefert einen CSV-String der alle Wahllokalbenutzernamen zum angegebenen Wahltag enthält.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportWahllokalBenutzer(wahltagID: string, options?: RawAxiosRequestConfig) {
        return WahllokalBenutzerControllerApiFp(this.configuration).exportWahllokalBenutzer(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }
}



