ALTER TABLE Wahldaten
    DROP CONSTRAINT FK_WD;
ALTER TABLE WAHLDATEN
    ADD CONSTRAINT NATURAL_ID UNIQUE (WAHLID, WAHLBEZIRKID, WAEHLERVERZEICHNISNUMMER);

DROP TABLE Stimmabgabevermerke;

ALTER TABLE Wahldaten RENAME TO Stimmabgabevermerke;

ALTER TABLE Vermerk RENAME COLUMN wahldatenID to stimmabgabevermerkeID;