export const MbwStepsEnum = {
  MBW_AUSZAEHLUNG_STIMMZETTEL: "MBW_AUSZAEHLUNG_STIMMZETTEL",
  MBW_STAPEL_E: "MBW_STAPEL_E",
  MBW_STAPEL_D_UNGUELTIG: "MBW_STAPEL_D_UNGUELTIG",
  MBW_STAPEL_A_AND_B: "MBW_STAPEL_A_AND_B",
  MBW_SCHNELLMELDUNG: "MBW_SCHNELLMELDUNG",
  MBW_STIMMZETTEL: "MBW_STIMMZETTEL",
  MBW_STAPEL_BC: "MBW_STAPEL_BC",
  MBW_NIEDERSCHRIFT: "MBW_NIEDERSCHRIFT",
  MBW_STIMMZETTEL_BESCHLUESSE: "MBW_STIMMZETTEL_BESCHLUESSE",
} as const;
export type MbwStepsEnum = (typeof MbwStepsEnum)[keyof typeof MbwStepsEnum];
