app:
  authServiceUri: https://kubernetes.docker.internal:8100

server:
  ssl:
    key-store: file:./../stack/cert/keystore.p12
    key-store-password: secret
    key-store-type: PKCS12
    key-alias: springboot

    trust-store: file:./../stack/cert/truststore.p12
    trust-store-password: changeit
    trust-store-type: PKCS12
    enabled: true
