/* tslint:disable */
/* eslint-disable */
/**
 * Monitoring Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.3.18-SNAPSHOT
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BezirkUndWahlID
 */
export interface BezirkUndWahlID {
    /**
     * 
     * @type {string}
     * @memberof BezirkUndWahlID
     */
    'wahlID': string;
    /**
     * 
     * @type {string}
     * @memberof BezirkUndWahlID
     */
    'wahlbezirkID': string;
}
/**
 * 
 * @export
 * @interface DruckdatenDTO
 */
export interface DruckdatenDTO {
    /**
     * 
     * @type {BezirkUndWahlID}
     * @memberof DruckdatenDTO
     */
    'bezirkUndWahlID': BezirkUndWahlID;
    /**
     * 
     * @type {string}
     * @memberof DruckdatenDTO
     */
    'druckuhrzeit': string;
}
/**
 * 
 * @export
 * @interface SendungsdatenDTO
 */
export interface SendungsdatenDTO {
    /**
     * 
     * @type {BezirkUndWahlID}
     * @memberof SendungsdatenDTO
     */
    'bezirkUndWahlID': BezirkUndWahlID;
    /**
     * 
     * @type {string}
     * @memberof SendungsdatenDTO
     */
    'sendungsuhrzeit': string;
}
/**
 * 
 * @export
 * @interface WaehleranzahlDTO
 */
export interface WaehleranzahlDTO {
    /**
     * 
     * @type {number}
     * @memberof WaehleranzahlDTO
     */
    'anzahlWaehler': number;
    /**
     * 
     * @type {string}
     * @memberof WaehleranzahlDTO
     */
    'uhrzeit': string;
}
/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * WaehleranzahlControllerApi - axios parameter creator
 * @export
 */
export const WaehleranzahlControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der zuvor gespeicherten Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlbeteiligung: async (wahlID: string, wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlID' is not null or undefined
            assertParamExists('getWahlbeteiligung', 'wahlID', wahlID)
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getWahlbeteiligung', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/wahlbeteiligung/{wahlID}/{wahlbezirkID}`
                .replace(`{${"wahlID"}}`, encodeURIComponent(String(wahlID)))
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern und Weiterleiten der Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {string} wahlID 
         * @param {WaehleranzahlDTO} waehleranzahlDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlbeteiligung: async (wahlbezirkID: string, wahlID: string, waehleranzahlDTO: WaehleranzahlDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postWahlbeteiligung', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'wahlID' is not null or undefined
            assertParamExists('postWahlbeteiligung', 'wahlID', wahlID)
            // verify required parameter 'waehleranzahlDTO' is not null or undefined
            assertParamExists('postWahlbeteiligung', 'waehleranzahlDTO', waehleranzahlDTO)
            const localVarPath = `/businessActions/wahlbeteiligung/{wahlID}/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)))
                .replace(`{${"wahlID"}}`, encodeURIComponent(String(wahlID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(waehleranzahlDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WaehleranzahlControllerApi - functional programming interface
 * @export
 */
export const WaehleranzahlControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WaehleranzahlControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der zuvor gespeicherten Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahlbeteiligung(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WaehleranzahlDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahlbeteiligung(wahlID, wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WaehleranzahlControllerApi.getWahlbeteiligung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern und Weiterleiten der Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {string} wahlID 
         * @param {WaehleranzahlDTO} waehleranzahlDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWahlbeteiligung(wahlbezirkID: string, wahlID: string, waehleranzahlDTO: WaehleranzahlDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postWahlbeteiligung(wahlbezirkID, wahlID, waehleranzahlDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WaehleranzahlControllerApi.postWahlbeteiligung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WaehleranzahlControllerApi - factory interface
 * @export
 */
export const WaehleranzahlControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WaehleranzahlControllerApiFp(configuration)
    return {
        /**
         * Laden der zuvor gespeicherten Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlbeteiligung(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<WaehleranzahlDTO> {
            return localVarFp.getWahlbeteiligung(wahlID, wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern und Weiterleiten der Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {string} wahlID 
         * @param {WaehleranzahlDTO} waehleranzahlDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlbeteiligung(wahlbezirkID: string, wahlID: string, waehleranzahlDTO: WaehleranzahlDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postWahlbeteiligung(wahlbezirkID, wahlID, waehleranzahlDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WaehleranzahlControllerApi - object-oriented interface
 * @export
 * @class WaehleranzahlControllerApi
 * @extends {BaseAPI}
 */
export class WaehleranzahlControllerApi extends BaseAPI {
    /**
     * Laden der zuvor gespeicherten Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
     * @param {string} wahlID 
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WaehleranzahlControllerApi
     */
    public getWahlbeteiligung(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return WaehleranzahlControllerApiFp(this.configuration).getWahlbeteiligung(wahlID, wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern und Weiterleiten der Wahlbeteiligung für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
     * @param {string} wahlbezirkID 
     * @param {string} wahlID 
     * @param {WaehleranzahlDTO} waehleranzahlDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WaehleranzahlControllerApi
     */
    public postWahlbeteiligung(wahlbezirkID: string, wahlID: string, waehleranzahlDTO: WaehleranzahlDTO, options?: RawAxiosRequestConfig) {
        return WaehleranzahlControllerApiFp(this.configuration).postWahlbeteiligung(wahlbezirkID, wahlID, waehleranzahlDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahllokalZustandControllerApi - axios parameter creator
 * @export
 */
export const WahllokalZustandControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Letzte Anwesenheit für das Team {teamID} des Wahlbezirks {wahlbezirkID}. Generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {string} wahlbezirkID 
         * @param {string} teamID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postLastSeen: async (wahlbezirkID: string, teamID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postLastSeen', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'teamID' is not null or undefined
            assertParamExists('postLastSeen', 'teamID', teamID)
            const localVarPath = `/businessActions/lastSeen`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (wahlbezirkID !== undefined) {
                localVarQueryParameter['wahlbezirkID'] = wahlbezirkID;
            }

            if (teamID !== undefined) {
                localVarQueryParameter['teamID'] = teamID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Empfängt die Request als Nachricht über die letzte Abmeldung für das Team {teamID} des Wahlbezirks {wahlbezirkID}, generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {string} wahlbezirkID 
         * @param {string} teamID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postLetzteAbmeldung: async (wahlbezirkID: string, teamID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postLetzteAbmeldung', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'teamID' is not null or undefined
            assertParamExists('postLetzteAbmeldung', 'teamID', teamID)
            const localVarPath = `/businessActions/letzteAbmeldung`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (wahlbezirkID !== undefined) {
                localVarQueryParameter['wahlbezirkID'] = wahlbezirkID;
            }

            if (teamID !== undefined) {
                localVarQueryParameter['teamID'] = teamID;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Empfängt die Daten über die Druckuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {DruckdatenDTO} druckdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postNiederschriftDruckuhrzeit: async (druckdatenDTO: DruckdatenDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'druckdatenDTO' is not null or undefined
            assertParamExists('postNiederschriftDruckuhrzeit', 'druckdatenDTO', druckdatenDTO)
            const localVarPath = `/businessActions/niederschriftDruckuhrzeit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(druckdatenDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Empfängt die Daten über die Sendungsuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {SendungsdatenDTO} sendungsdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postNiederschriftSendungsuhrzeit: async (sendungsdatenDTO: SendungsdatenDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendungsdatenDTO' is not null or undefined
            assertParamExists('postNiederschriftSendungsuhrzeit', 'sendungsdatenDTO', sendungsdatenDTO)
            const localVarPath = `/businessActions/niederschriftSendungsuhrzeit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendungsdatenDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Empfängt die Daten über die Druckuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {DruckdatenDTO} druckdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSchnellmeldungDruckuhrzeit: async (druckdatenDTO: DruckdatenDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'druckdatenDTO' is not null or undefined
            assertParamExists('postSchnellmeldungDruckuhrzeit', 'druckdatenDTO', druckdatenDTO)
            const localVarPath = `/businessActions/schnellmeldungDruckuhrzeit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(druckdatenDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Empfängt die Daten über die Sendungsuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {SendungsdatenDTO} sendungsdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSchnellmeldungSendungsuhrzeit: async (sendungsdatenDTO: SendungsdatenDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sendungsdatenDTO' is not null or undefined
            assertParamExists('postSchnellmeldungSendungsuhrzeit', 'sendungsdatenDTO', sendungsdatenDTO)
            const localVarPath = `/businessActions/schnellmeldungSendungsuhrzeit`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sendungsdatenDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahllokalZustandControllerApi - functional programming interface
 * @export
 */
export const WahllokalZustandControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahllokalZustandControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Letzte Anwesenheit für das Team {teamID} des Wahlbezirks {wahlbezirkID}. Generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {string} wahlbezirkID 
         * @param {string} teamID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postLastSeen(wahlbezirkID: string, teamID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postLastSeen(wahlbezirkID, teamID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalZustandControllerApi.postLastSeen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Empfängt die Request als Nachricht über die letzte Abmeldung für das Team {teamID} des Wahlbezirks {wahlbezirkID}, generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {string} wahlbezirkID 
         * @param {string} teamID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postLetzteAbmeldung(wahlbezirkID: string, teamID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postLetzteAbmeldung(wahlbezirkID, teamID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalZustandControllerApi.postLetzteAbmeldung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Empfängt die Daten über die Druckuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {DruckdatenDTO} druckdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postNiederschriftDruckuhrzeit(druckdatenDTO: DruckdatenDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postNiederschriftDruckuhrzeit(druckdatenDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalZustandControllerApi.postNiederschriftDruckuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Empfängt die Daten über die Sendungsuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {SendungsdatenDTO} sendungsdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postNiederschriftSendungsuhrzeit(sendungsdatenDTO: SendungsdatenDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postNiederschriftSendungsuhrzeit(sendungsdatenDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalZustandControllerApi.postNiederschriftSendungsuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Empfängt die Daten über die Druckuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {DruckdatenDTO} druckdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postSchnellmeldungDruckuhrzeit(druckdatenDTO: DruckdatenDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postSchnellmeldungDruckuhrzeit(druckdatenDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalZustandControllerApi.postSchnellmeldungDruckuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Empfängt die Daten über die Sendungsuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {SendungsdatenDTO} sendungsdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postSchnellmeldungSendungsuhrzeit(sendungsdatenDTO: SendungsdatenDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postSchnellmeldungSendungsuhrzeit(sendungsdatenDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahllokalZustandControllerApi.postSchnellmeldungSendungsuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahllokalZustandControllerApi - factory interface
 * @export
 */
export const WahllokalZustandControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahllokalZustandControllerApiFp(configuration)
    return {
        /**
         * Letzte Anwesenheit für das Team {teamID} des Wahlbezirks {wahlbezirkID}. Generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {string} wahlbezirkID 
         * @param {string} teamID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postLastSeen(wahlbezirkID: string, teamID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postLastSeen(wahlbezirkID, teamID, options).then((request) => request(axios, basePath));
        },
        /**
         * Empfängt die Request als Nachricht über die letzte Abmeldung für das Team {teamID} des Wahlbezirks {wahlbezirkID}, generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {string} wahlbezirkID 
         * @param {string} teamID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postLetzteAbmeldung(wahlbezirkID: string, teamID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postLetzteAbmeldung(wahlbezirkID, teamID, options).then((request) => request(axios, basePath));
        },
        /**
         * Empfängt die Daten über die Druckuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {DruckdatenDTO} druckdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postNiederschriftDruckuhrzeit(druckdatenDTO: DruckdatenDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postNiederschriftDruckuhrzeit(druckdatenDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Empfängt die Daten über die Sendungsuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {SendungsdatenDTO} sendungsdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postNiederschriftSendungsuhrzeit(sendungsdatenDTO: SendungsdatenDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postNiederschriftSendungsuhrzeit(sendungsdatenDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Empfängt die Daten über die Druckuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {DruckdatenDTO} druckdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSchnellmeldungDruckuhrzeit(druckdatenDTO: DruckdatenDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postSchnellmeldungDruckuhrzeit(druckdatenDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Empfängt die Daten über die Sendungsuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
         * @param {SendungsdatenDTO} sendungsdatenDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postSchnellmeldungSendungsuhrzeit(sendungsdatenDTO: SendungsdatenDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postSchnellmeldungSendungsuhrzeit(sendungsdatenDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahllokalZustandControllerApi - object-oriented interface
 * @export
 * @class WahllokalZustandControllerApi
 * @extends {BaseAPI}
 */
export class WahllokalZustandControllerApi extends BaseAPI {
    /**
     * Letzte Anwesenheit für das Team {teamID} des Wahlbezirks {wahlbezirkID}. Generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
     * @param {string} wahlbezirkID 
     * @param {string} teamID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahllokalZustandControllerApi
     */
    public postLastSeen(wahlbezirkID: string, teamID: string, options?: RawAxiosRequestConfig) {
        return WahllokalZustandControllerApiFp(this.configuration).postLastSeen(wahlbezirkID, teamID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Empfängt die Request als Nachricht über die letzte Abmeldung für das Team {teamID} des Wahlbezirks {wahlbezirkID}, generiert die Empfangs-Uhrzeit, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
     * @param {string} wahlbezirkID 
     * @param {string} teamID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahllokalZustandControllerApi
     */
    public postLetzteAbmeldung(wahlbezirkID: string, teamID: string, options?: RawAxiosRequestConfig) {
        return WahllokalZustandControllerApiFp(this.configuration).postLetzteAbmeldung(wahlbezirkID, teamID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Empfängt die Daten über die Druckuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
     * @param {DruckdatenDTO} druckdatenDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahllokalZustandControllerApi
     */
    public postNiederschriftDruckuhrzeit(druckdatenDTO: DruckdatenDTO, options?: RawAxiosRequestConfig) {
        return WahllokalZustandControllerApiFp(this.configuration).postNiederschriftDruckuhrzeit(druckdatenDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Empfängt die Daten über die Sendungsuhrzeit der Niederschrift, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
     * @param {SendungsdatenDTO} sendungsdatenDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahllokalZustandControllerApi
     */
    public postNiederschriftSendungsuhrzeit(sendungsdatenDTO: SendungsdatenDTO, options?: RawAxiosRequestConfig) {
        return WahllokalZustandControllerApiFp(this.configuration).postNiederschriftSendungsuhrzeit(sendungsdatenDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Empfängt die Daten über die Druckuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
     * @param {DruckdatenDTO} druckdatenDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahllokalZustandControllerApi
     */
    public postSchnellmeldungDruckuhrzeit(druckdatenDTO: DruckdatenDTO, options?: RawAxiosRequestConfig) {
        return WahllokalZustandControllerApiFp(this.configuration).postSchnellmeldungDruckuhrzeit(druckdatenDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Empfängt die Daten über die Sendungsuhrzeit der Schnellmeldung, packt diese in ein Wahllokalzustand-Objekt und leitet dieses weiter.
     * @param {SendungsdatenDTO} sendungsdatenDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahllokalZustandControllerApi
     */
    public postSchnellmeldungSendungsuhrzeit(sendungsdatenDTO: SendungsdatenDTO, options?: RawAxiosRequestConfig) {
        return WahllokalZustandControllerApiFp(this.configuration).postSchnellmeldungSendungsuhrzeit(sendungsdatenDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



