app:
  authServiceUri: http://host.docker.internal:8100

server:
  port: 8083
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sso
              uri: ${app.authServiceUri}/
              predicates:
                - Path=/api/sso/userinfo
              filters:
                - RewritePath=/api/sso/userinfo, /user
                - RemoveRequestHeader=Cookie
                - RemoveResponseHeader=Set-Cookie
            - id: auth-service
              uri: ${app.authServiceUri}/
              predicates:
                - Path=/api/auth-service/**
              filters:
                - RewritePath=/api/auth-service/(?<urlsegments>.*), /$\{urlsegments}
                - RemoveRequestHeader=Cookie
                - RemoveResponseHeader=Set-Cookie
            - id: basisdaten-service
              uri: http://host.docker.internal:8205/
              predicates:
                - Path=/api/basisdaten-service/**
              filters:
                - RewritePath=/api/basisdaten-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: briefwahl-service
              uri: http://host.docker.internal:8202/
              predicates:
                - Path=/api/briefwahl-service/**
              filters:
                - RewritePath=/api/briefwahl-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: broadcast-service
              uri: http://host.docker.internal:8200/
              predicates:
                - Path=/api/broadcast-service/**
              filters:
                - RewritePath=/api/broadcast-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: ergebnismeldung-service
              uri: http://host.docker.internal:8208/
              predicates:
                - Path=/api/ergebnismeldung-service/**
              filters:
                - RewritePath=/api/ergebnismeldung-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: infomanagement-service
              uri: http://host.docker.internal:8201/
              predicates:
                - Path=/api/infomanagement-service/**
              filters:
                - RewritePath=/api/infomanagement-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: monitoring-service
              uri: http://host.docker.internal:8206/
              predicates:
                - Path=/api/monitoring-service/**
              filters:
                - RewritePath=/api/monitoring-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: vorfaelleundvorkommnisse-service
              uri: http://host.docker.internal:8204/
              predicates:
                - Path=/api/vorfaelleundvorkommnisse-service/**
              filters:
                - RewritePath=/api/vorfaelleundvorkommnisse-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: wahlvorbereitung-service
              uri: http://host.docker.internal:8203/
              predicates:
                - Path=/api/wahlvorbereitung-service/**
              filters:
                - RewritePath=/api/wahlvorbereitung-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: wahlvorstand-service
              uri: http://host.docker.internal:8207/
              predicates:
                - Path=/api/wahlvorstand-service/**
              filters:
                - RewritePath=/api/wahlvorstand-service/(?<urlsegments>.*), /$\{urlsegments}
            # frontend has to be the last route to be sure it does not override other routes with path=/**
            - id: frontend
              uri: http://host.docker.internal:8400/
              predicates:
                - Path=/**
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${app.authServiceUri}/user
      client:
        provider:
          sso:
#            issuer-uri: https://auth.wls.host.docker.internal:58100/uaa
            jwk-set-uri: http://localhost:8100/uaa/oauth2/jwks
            authorization-uri: https://auth.wls.host.docker.internal:58100/uaa/oauth2/authorize
            token-uri: http://localhost:8100/uaa/oauth2/token
            user-info-uri: http://localhost:8100/uaa/userinfo
            user-name-attribute: "sub"
        registration:
          sso:
            provider: sso
            client-id: wls
            client-secret: top-secret
            scope: openid
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code

logging:
  include-application-group: false # disabled because application group is only relevant when deployed
  structured:
    format:
      console: # set to empty to disable structured logging locally
  level:
    root: INFO
    de.muenchen.oss.wahllokalsystem: DEBUG

management:
  endpoints:
    access:
      default: read_only # Required for local debugging via JMX+RMI, additionally might have to set -Djava.rmi.server.hostname=localhost as JVM arguments

ALLOWED_ORIGINS_PUBLIC: "*"
ALLOWED_ORIGINS_CLIENTS: "*"
CONFIG_MAP5XXTO400: false
