CREATE TABLE DSEStimmzettel (
    wahlbezirkID VARCHAR2(255) NOT NULL,
    wahlID VARCHAR2(255) NOT NULL,
    teamID VARCHAR2(255) NOT NULL,
    stimmzettelkennung NUMBER(10) NOT NULL,
    valid NUMBER(1) NOT NULL,
    invalideVotes NUMBER(10) NOT NULL,
    gueltigkeit VARCHAR2(255) NOT NULL,
    beschluss_pro NUMBER(10),
    beschluss_contra NUMBER(10),
    beschluss_text VARCHAR2(4000),
    CONSTRAINT pk_dse_stimmzettel PRIMARY KEY (wahlbezirkID, wahlID, teamID, stimmzettelkennung)
);

CREATE TABLE DSEBeschlussvormerkung (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR2(4000) NOT NULL,
    stimmzettel_wahlbezirkID VARCHAR2(255) NOT NULL,
    stimmzettel_wahlID VARCHAR2(255) NOT NULL,
    stimmzettel_teamID VARCHAR2(255) NOT NULL,
    stimmzettel_stimmzettelkennung NUMBER(10) NOT NULL,
    CONSTRAINT fk_dsebeschlussvormerkung_stimmzettel FOREIGN KEY (stimmzettel_wahlbezirkID, stimmzettel_wahlID, stimmzettel_teamID, stimmzettel_stimmzettelkennung)
        REFERENCES DSEStimmzettel (wahlbezirkID, wahlID, teamID, stimmzettelkennung)
);

CREATE TABLE DSEWahlvorschlag (
    id NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wahlvorschlagID VARCHAR2(255) NOT NULL,
    selected NUMBER(1) NOT NULL,
    stimmzettel_wahlbezirkID VARCHAR2(255) NOT NULL,
    stimmzettel_wahlID VARCHAR2(255) NOT NULL,
    stimmzettel_teamID VARCHAR2(255) NOT NULL,
    stimmzettel_stimmzettelkennung NUMBER(10) NOT NULL,
    CONSTRAINT fk_dsewahlvorschlag_stimmzettel FOREIGN KEY (stimmzettel_wahlbezirkID, stimmzettel_wahlID, stimmzettel_teamID, stimmzettel_stimmzettelkennung)
        REFERENCES DSEStimmzettel (wahlbezirkID, wahlID, teamID, stimmzettelkennung)
);

CREATE TABLE DSEKandidat (
    kandidatID VARCHAR2(255) NOT NULL,
    nennungsNummer NUMBER(10) NOT NULL,
    wahlvorschlag_id NUMBER(19) NOT NULL,
    discarded NUMBER(1) NOT NULL,
    votesByVoter NUMBER(10),
    invalidVotes NUMBER(10),
    votesByWahlvorschlag NUMBER(10),
    CONSTRAINT pk_dse_kandidat PRIMARY KEY (kandidatID, nennungsNummer),
    CONSTRAINT fk_dsekandidat_wahlvorschlag FOREIGN KEY (wahlvorschlag_id)
        REFERENCES DSEWahlvorschlag (id),
    CONSTRAINT uq_dsekandidat_per_wahlvorschlag UNIQUE (wahlvorschlag_id, kandidatID, nennungsNummer)
);
