ALTER TABLE KANDIDAT ADD identifikator2 VARCHAR(1024) NOT NULL;
UPDATE KANDIDAT SET KANDIDAT.identifikator2 = KANDIDAT.identifikator;
ALTER TABLE KANDIDAT DROP COLUMN identifikator;

ALTER TABLE KANDIDAT ADD identifikator VARCHAR(1024) NOT NULL;
UPDATE KANDIDAT SET KANDIDAT.identifikator = KANDIDAT.identifikator2;
ALTER TABLE KANDIDAT DROP COLUMN identifikator2;