/* tslint:disable */
/* eslint-disable */
/**
 * Basisdatenservice
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.6.1
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AsyncProgressDTO
 */
export interface AsyncProgressDTO {
    /**
     * 
     * @type {string}
     * @memberof AsyncProgressDTO
     */
    'forWahltag'?: string;
    /**
     * 
     * @type {string}
     * @memberof AsyncProgressDTO
     */
    'wahlNummer'?: string;
    /**
     * 
     * @type {string}
     * @memberof AsyncProgressDTO
     */
    'lastStartTime'?: string;
    /**
     * 
     * @type {string}
     * @memberof AsyncProgressDTO
     */
    'lastFinishTime'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AsyncProgressDTO
     */
    'wahlvorschlaegeLoadingActive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AsyncProgressDTO
     */
    'wahlvorschlaegeTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof AsyncProgressDTO
     */
    'wahlvorschlageFinished'?: number;
    /**
     * 
     * @type {string}
     * @memberof AsyncProgressDTO
     */
    'wahlvorschlaegeNext'?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AsyncProgressDTO
     */
    'referendumLoadingActive'?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AsyncProgressDTO
     */
    'referendumVorlagenTotal'?: number;
    /**
     * 
     * @type {number}
     * @memberof AsyncProgressDTO
     */
    'referendumVorlagenFinished'?: number;
    /**
     * 
     * @type {string}
     * @memberof AsyncProgressDTO
     */
    'referendumVorlagenNext'?: string;
}
/**
 * 
 * @export
 * @interface FarbeDTO
 */
export interface FarbeDTO {
    /**
     * 
     * @type {number}
     * @memberof FarbeDTO
     */
    'r': number;
    /**
     * 
     * @type {number}
     * @memberof FarbeDTO
     */
    'g': number;
    /**
     * 
     * @type {number}
     * @memberof FarbeDTO
     */
    'b': number;
}
/**
 * 
 * @export
 * @interface KandidatDTO
 */
export interface KandidatDTO {
    /**
     * 
     * @type {string}
     * @memberof KandidatDTO
     */
    'identifikator': string;
    /**
     * 
     * @type {string}
     * @memberof KandidatDTO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof KandidatDTO
     */
    'listenposition': number;
    /**
     * 
     * @type {boolean}
     * @memberof KandidatDTO
     */
    'direktkandidat': boolean;
    /**
     * 
     * @type {number}
     * @memberof KandidatDTO
     */
    'tabellenSpalteInNiederschrift': number;
    /**
     * 
     * @type {boolean}
     * @memberof KandidatDTO
     */
    'einzelbewerber': boolean;
    /**
     * 
     * @type {number}
     * @memberof KandidatDTO
     */
    'anzahlNennungen': number;
}
/**
 * 
 * @export
 * @interface KopfdatenDTO
 */
export interface KopfdatenDTO {
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'wahlID': string;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'gemeinde': string;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'stimmzettelgebietsart': KopfdatenDTOStimmzettelgebietsartEnum;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'stimmzettelgebietsnummer': string;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'stimmzettelgebietsname': string;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'wahlname': string;
    /**
     * 
     * @type {string}
     * @memberof KopfdatenDTO
     */
    'wahlbezirknummer': string;
    /**
     * 
     * @type {number}
     * @memberof KopfdatenDTO
     */
    'maximalErlaubteStimmenProWaehler'?: number;
}

export const KopfdatenDTOStimmzettelgebietsartEnum = {
    Sb: 'SB',
    Sg: 'SG',
    Sk: 'SK',
    Wk: 'WK'
} as const;

export type KopfdatenDTOStimmzettelgebietsartEnum = typeof KopfdatenDTOStimmzettelgebietsartEnum[keyof typeof KopfdatenDTOStimmzettelgebietsartEnum];

/**
 * 
 * @export
 * @interface ReferendumoptionDTO
 */
export interface ReferendumoptionDTO {
    /**
     * 
     * @type {string}
     * @memberof ReferendumoptionDTO
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof ReferendumoptionDTO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof ReferendumoptionDTO
     */
    'position'?: number;
}
/**
 * 
 * @export
 * @interface ReferendumvorlageDTO
 */
export interface ReferendumvorlageDTO {
    /**
     * 
     * @type {string}
     * @memberof ReferendumvorlageDTO
     */
    'wahlvorschlagID': string;
    /**
     * 
     * @type {number}
     * @memberof ReferendumvorlageDTO
     */
    'ordnungszahl': number;
    /**
     * 
     * @type {string}
     * @memberof ReferendumvorlageDTO
     */
    'kurzname': string;
    /**
     * 
     * @type {string}
     * @memberof ReferendumvorlageDTO
     */
    'frage': string;
    /**
     * 
     * @type {Set<ReferendumoptionDTO>}
     * @memberof ReferendumvorlageDTO
     */
    'referendumoptionen': Set<ReferendumoptionDTO>;
}
/**
 * 
 * @export
 * @interface ReferendumvorlagenDTO
 */
export interface ReferendumvorlagenDTO {
    /**
     * 
     * @type {string}
     * @memberof ReferendumvorlagenDTO
     */
    'stimmzettelgebietID': string;
    /**
     * 
     * @type {Set<ReferendumvorlageDTO>}
     * @memberof ReferendumvorlagenDTO
     */
    'referendumvorlage': Set<ReferendumvorlageDTO>;
}
/**
 * 
 * @export
 * @interface WahlDTO
 */
export interface WahlDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlDTO
     */
    'wahlID': string;
    /**
     * 
     * @type {string}
     * @memberof WahlDTO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof WahlDTO
     */
    'reihenfolge': number;
    /**
     * 
     * @type {number}
     * @memberof WahlDTO
     */
    'waehlerverzeichnisNummer': number;
    /**
     * 
     * @type {string}
     * @memberof WahlDTO
     */
    'wahltag': string;
    /**
     * 
     * @type {string}
     * @memberof WahlDTO
     */
    'wahlart': WahlDTOWahlartEnum;
    /**
     * 
     * @type {FarbeDTO}
     * @memberof WahlDTO
     */
    'farbe': FarbeDTO;
    /**
     * 
     * @type {string}
     * @memberof WahlDTO
     */
    'nummer'?: string;
    /**
     * 
     * @type {string}
     * @memberof WahlDTO
     */
    'kennzeichen': string;
}

export const WahlDTOWahlartEnum = {
    Baw: 'BAW',
    Beb: 'BEB',
    Btw: 'BTW',
    Bzw: 'BZW',
    Euw: 'EUW',
    Ltw: 'LTW',
    Mbw: 'MBW',
    Obw: 'OBW',
    Srw: 'SRW',
    Svw: 'SVW',
    Ve: 'VE'
} as const;

export type WahlDTOWahlartEnum = typeof WahlDTOWahlartEnum[keyof typeof WahlDTOWahlartEnum];

/**
 * 
 * @export
 * @interface WahlbezirkDTO
 */
export interface WahlbezirkDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkDTO
     */
    'wahltag': string;
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkDTO
     */
    'nummer': string;
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkDTO
     */
    'wahlbezirkart': WahlbezirkDTOWahlbezirkartEnum;
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkDTO
     */
    'wahlnummer': string;
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkDTO
     */
    'wahlID': string;
}

export const WahlbezirkDTOWahlbezirkartEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB'
} as const;

export type WahlbezirkDTOWahlbezirkartEnum = typeof WahlbezirkDTOWahlbezirkartEnum[keyof typeof WahlbezirkDTOWahlbezirkartEnum];

/**
 * 
 * @export
 * @interface WahltagDTO
 */
export interface WahltagDTO {
    /**
     * 
     * @type {string}
     * @memberof WahltagDTO
     */
    'wahltagID': string;
    /**
     * 
     * @type {string}
     * @memberof WahltagDTO
     */
    'wahltag': string;
    /**
     * 
     * @type {string}
     * @memberof WahltagDTO
     */
    'beschreibung'?: string;
    /**
     * 
     * @type {string}
     * @memberof WahltagDTO
     */
    'nummer'?: string;
}
/**
 * 
 * @export
 * @interface WahlvorschlaegeDTO
 */
export interface WahlvorschlaegeDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlvorschlaegeDTO
     */
    'wahlID': string;
    /**
     * 
     * @type {string}
     * @memberof WahlvorschlaegeDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof WahlvorschlaegeDTO
     */
    'stimmzettelgebietID': string;
    /**
     * 
     * @type {Set<WahlvorschlagDTO>}
     * @memberof WahlvorschlaegeDTO
     */
    'wahlvorschlaege': Set<WahlvorschlagDTO>;
}
/**
 * 
 * @export
 * @interface WahlvorschlagDTO
 */
export interface WahlvorschlagDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlvorschlagDTO
     */
    'identifikator': string;
    /**
     * 
     * @type {number}
     * @memberof WahlvorschlagDTO
     */
    'ordnungszahl': number;
    /**
     * 
     * @type {string}
     * @memberof WahlvorschlagDTO
     */
    'kurzname': string;
    /**
     * 
     * @type {boolean}
     * @memberof WahlvorschlagDTO
     */
    'erhaeltStimmen': boolean;
    /**
     * 
     * @type {Set<KandidatDTO>}
     * @memberof WahlvorschlagDTO
     */
    'kandidaten'?: Set<KandidatDTO>;
}
/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * AsyncProgressControllerApi - axios parameter creator
 * @export
 */
export const AsyncProgressControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Abrufen des Fortschrittes bei der Importierung der Wahltermindaten.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAsyncProgress: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/asyncProgress`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AsyncProgressControllerApi - functional programming interface
 * @export
 */
export const AsyncProgressControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AsyncProgressControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Abrufen des Fortschrittes bei der Importierung der Wahltermindaten.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAsyncProgress(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AsyncProgressDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAsyncProgress(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AsyncProgressControllerApi.getAsyncProgress']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AsyncProgressControllerApi - factory interface
 * @export
 */
export const AsyncProgressControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AsyncProgressControllerApiFp(configuration)
    return {
        /**
         * Abrufen des Fortschrittes bei der Importierung der Wahltermindaten.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAsyncProgress(options?: RawAxiosRequestConfig): AxiosPromise<AsyncProgressDTO> {
            return localVarFp.getAsyncProgress(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AsyncProgressControllerApi - object-oriented interface
 * @export
 * @class AsyncProgressControllerApi
 * @extends {BaseAPI}
 */
export class AsyncProgressControllerApi extends BaseAPI {
    /**
     * Abrufen des Fortschrittes bei der Importierung der Wahltermindaten.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AsyncProgressControllerApi
     */
    public getAsyncProgress(options?: RawAxiosRequestConfig) {
        return AsyncProgressControllerApiFp(this.configuration).getAsyncProgress(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * HandbuchControllerApi - axios parameter creator
 * @export
 */
export const HandbuchControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Abrufen des Handbuches einer Wahl für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {GetHandbuchWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHandbuch: async (wahltagID: string, wahlbezirksart: GetHandbuchWahlbezirksartEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('getHandbuch', 'wahltagID', wahltagID)
            // verify required parameter 'wahlbezirksart' is not null or undefined
            assertParamExists('getHandbuch', 'wahlbezirksart', wahlbezirksart)
            const localVarPath = `/businessActions/handbuch/{wahltagID}/{wahlbezirksart}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)))
                .replace(`{${"wahlbezirksart"}}`, encodeURIComponent(String(wahlbezirksart)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern eines Handbuches einer Wahl für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {SetHandbuchWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setHandbuch: async (wahltagID: string, wahlbezirksart: SetHandbuchWahlbezirksartEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('setHandbuch', 'wahltagID', wahltagID)
            // verify required parameter 'wahlbezirksart' is not null or undefined
            assertParamExists('setHandbuch', 'wahlbezirksart', wahlbezirksart)
            const localVarPath = `/businessActions/handbuch/{wahltagID}/{wahlbezirksart}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)))
                .replace(`{${"wahlbezirksart"}}`, encodeURIComponent(String(wahlbezirksart)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HandbuchControllerApi - functional programming interface
 * @export
 */
export const HandbuchControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HandbuchControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Abrufen des Handbuches einer Wahl für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {GetHandbuchWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getHandbuch(wahltagID: string, wahlbezirksart: GetHandbuchWahlbezirksartEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getHandbuch(wahltagID, wahlbezirksart, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HandbuchControllerApi.getHandbuch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern eines Handbuches einer Wahl für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {SetHandbuchWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setHandbuch(wahltagID: string, wahlbezirksart: SetHandbuchWahlbezirksartEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setHandbuch(wahltagID, wahlbezirksart, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HandbuchControllerApi.setHandbuch']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HandbuchControllerApi - factory interface
 * @export
 */
export const HandbuchControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HandbuchControllerApiFp(configuration)
    return {
        /**
         * Abrufen des Handbuches einer Wahl für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {GetHandbuchWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getHandbuch(wahltagID: string, wahlbezirksart: GetHandbuchWahlbezirksartEnum, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getHandbuch(wahltagID, wahlbezirksart, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern eines Handbuches einer Wahl für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {SetHandbuchWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setHandbuch(wahltagID: string, wahlbezirksart: SetHandbuchWahlbezirksartEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setHandbuch(wahltagID, wahlbezirksart, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HandbuchControllerApi - object-oriented interface
 * @export
 * @class HandbuchControllerApi
 * @extends {BaseAPI}
 */
export class HandbuchControllerApi extends BaseAPI {
    /**
     * Abrufen des Handbuches einer Wahl für eine bestimmte Wahlbezirksart
     * @param {string} wahltagID 
     * @param {GetHandbuchWahlbezirksartEnum} wahlbezirksart 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandbuchControllerApi
     */
    public getHandbuch(wahltagID: string, wahlbezirksart: GetHandbuchWahlbezirksartEnum, options?: RawAxiosRequestConfig) {
        return HandbuchControllerApiFp(this.configuration).getHandbuch(wahltagID, wahlbezirksart, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern eines Handbuches einer Wahl für eine bestimmte Wahlbezirksart
     * @param {string} wahltagID 
     * @param {SetHandbuchWahlbezirksartEnum} wahlbezirksart 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HandbuchControllerApi
     */
    public setHandbuch(wahltagID: string, wahlbezirksart: SetHandbuchWahlbezirksartEnum, options?: RawAxiosRequestConfig) {
        return HandbuchControllerApiFp(this.configuration).setHandbuch(wahltagID, wahlbezirksart, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetHandbuchWahlbezirksartEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB'
} as const;
export type GetHandbuchWahlbezirksartEnum = typeof GetHandbuchWahlbezirksartEnum[keyof typeof GetHandbuchWahlbezirksartEnum];
/**
 * @export
 */
export const SetHandbuchWahlbezirksartEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB'
} as const;
export type SetHandbuchWahlbezirksartEnum = typeof SetHandbuchWahlbezirksartEnum[keyof typeof SetHandbuchWahlbezirksartEnum];


/**
 * KopfdatenControllerApi - axios parameter creator
 * @export
 */
export const KopfdatenControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Kopfdaten für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKopfdaten: async (wahlID: string, wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlID' is not null or undefined
            assertParamExists('getKopfdaten', 'wahlID', wahlID)
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getKopfdaten', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/kopfdaten/{wahlID}/{wahlbezirkID}`
                .replace(`{${"wahlID"}}`, encodeURIComponent(String(wahlID)))
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KopfdatenControllerApi - functional programming interface
 * @export
 */
export const KopfdatenControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KopfdatenControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Kopfdaten für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKopfdaten(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KopfdatenDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKopfdaten(wahlID, wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KopfdatenControllerApi.getKopfdaten']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * KopfdatenControllerApi - factory interface
 * @export
 */
export const KopfdatenControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KopfdatenControllerApiFp(configuration)
    return {
        /**
         * Laden der Kopfdaten für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKopfdaten(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<KopfdatenDTO> {
            return localVarFp.getKopfdaten(wahlID, wahlbezirkID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * KopfdatenControllerApi - object-oriented interface
 * @export
 * @class KopfdatenControllerApi
 * @extends {BaseAPI}
 */
export class KopfdatenControllerApi extends BaseAPI {
    /**
     * Laden der Kopfdaten für die Wahl {wahlID} für den Wahlbezirk {wahlbezirkID}.
     * @param {string} wahlID 
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KopfdatenControllerApi
     */
    public getKopfdaten(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return KopfdatenControllerApiFp(this.configuration).getKopfdaten(wahlID, wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * NachlieferungsbezirkeControllerApi - axios parameter creator
 * @export
 */
export const NachlieferungsbezirkeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Abrufen, ob es sich beim Wahlbezirk um einen Nachlieferungsbezirk handelt
         * @param {string} wahltagID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isNachlieferungsbezirk: async (wahltagID: string, wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('isNachlieferungsbezirk', 'wahltagID', wahltagID)
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('isNachlieferungsbezirk', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/nachlieferungsbezirke/{wahltagID}/{wahlbezirkID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)))
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern der Liste an Nachlieferungsbezirken für einen bestimmten Wahltag. Eine bestehende Liste wird ersetzt.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setNachlieferungsbezirke: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('setNachlieferungsbezirke', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/nachlieferungsbezirke/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NachlieferungsbezirkeControllerApi - functional programming interface
 * @export
 */
export const NachlieferungsbezirkeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NachlieferungsbezirkeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Abrufen, ob es sich beim Wahlbezirk um einen Nachlieferungsbezirk handelt
         * @param {string} wahltagID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async isNachlieferungsbezirk(wahltagID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.isNachlieferungsbezirk(wahltagID, wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NachlieferungsbezirkeControllerApi.isNachlieferungsbezirk']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern der Liste an Nachlieferungsbezirken für einen bestimmten Wahltag. Eine bestehende Liste wird ersetzt.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setNachlieferungsbezirke(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setNachlieferungsbezirke(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NachlieferungsbezirkeControllerApi.setNachlieferungsbezirke']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NachlieferungsbezirkeControllerApi - factory interface
 * @export
 */
export const NachlieferungsbezirkeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NachlieferungsbezirkeControllerApiFp(configuration)
    return {
        /**
         * Abrufen, ob es sich beim Wahlbezirk um einen Nachlieferungsbezirk handelt
         * @param {string} wahltagID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isNachlieferungsbezirk(wahltagID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.isNachlieferungsbezirk(wahltagID, wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern der Liste an Nachlieferungsbezirken für einen bestimmten Wahltag. Eine bestehende Liste wird ersetzt.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setNachlieferungsbezirke(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setNachlieferungsbezirke(wahltagID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NachlieferungsbezirkeControllerApi - object-oriented interface
 * @export
 * @class NachlieferungsbezirkeControllerApi
 * @extends {BaseAPI}
 */
export class NachlieferungsbezirkeControllerApi extends BaseAPI {
    /**
     * Abrufen, ob es sich beim Wahlbezirk um einen Nachlieferungsbezirk handelt
     * @param {string} wahltagID 
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NachlieferungsbezirkeControllerApi
     */
    public isNachlieferungsbezirk(wahltagID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return NachlieferungsbezirkeControllerApiFp(this.configuration).isNachlieferungsbezirk(wahltagID, wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern der Liste an Nachlieferungsbezirken für einen bestimmten Wahltag. Eine bestehende Liste wird ersetzt.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof NachlieferungsbezirkeControllerApi
     */
    public setNachlieferungsbezirke(wahltagID: string, options?: RawAxiosRequestConfig) {
        return NachlieferungsbezirkeControllerApiFp(this.configuration).setNachlieferungsbezirke(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * ReferendumvorlagenControllerApi - axios parameter creator
 * @export
 */
export const ReferendumvorlagenControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Referendumsvorlagen des Wahllokals {wahlbezirkID} für eine Wahl {wahlID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReferendumvorlagen: async (wahlID: string, wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlID' is not null or undefined
            assertParamExists('getReferendumvorlagen', 'wahlID', wahlID)
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getReferendumvorlagen', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/referendumvorlagen/{wahlID}/{wahlbezirkID}`
                .replace(`{${"wahlID"}}`, encodeURIComponent(String(wahlID)))
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReferendumvorlagenControllerApi - functional programming interface
 * @export
 */
export const ReferendumvorlagenControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReferendumvorlagenControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Referendumsvorlagen des Wahllokals {wahlbezirkID} für eine Wahl {wahlID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getReferendumvorlagen(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ReferendumvorlagenDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReferendumvorlagen(wahlID, wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReferendumvorlagenControllerApi.getReferendumvorlagen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReferendumvorlagenControllerApi - factory interface
 * @export
 */
export const ReferendumvorlagenControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReferendumvorlagenControllerApiFp(configuration)
    return {
        /**
         * Laden der Referendumsvorlagen des Wahllokals {wahlbezirkID} für eine Wahl {wahlID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getReferendumvorlagen(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<ReferendumvorlagenDTO> {
            return localVarFp.getReferendumvorlagen(wahlID, wahlbezirkID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReferendumvorlagenControllerApi - object-oriented interface
 * @export
 * @class ReferendumvorlagenControllerApi
 * @extends {BaseAPI}
 */
export class ReferendumvorlagenControllerApi extends BaseAPI {
    /**
     * Laden der Referendumsvorlagen des Wahllokals {wahlbezirkID} für eine Wahl {wahlID}.
     * @param {string} wahlID 
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReferendumvorlagenControllerApi
     */
    public getReferendumvorlagen(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return ReferendumvorlagenControllerApiFp(this.configuration).getReferendumvorlagen(wahlID, wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UngueltigeWahlscheineControllerApi - axios parameter creator
 * @export
 */
export const UngueltigeWahlscheineControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Abrufen der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart. Kommen als Anhang im csv-Format mit den Spalten Nachname, Vorname und Nummer
         * @param {string} wahltagID 
         * @param {GetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUngueltigeWahlscheine: async (wahltagID: string, wahlbezirksart: GetUngueltigeWahlscheineWahlbezirksartEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('getUngueltigeWahlscheine', 'wahltagID', wahltagID)
            // verify required parameter 'wahlbezirksart' is not null or undefined
            assertParamExists('getUngueltigeWahlscheine', 'wahlbezirksart', wahlbezirksart)
            const localVarPath = `/businessActions/ungueltigews/{wahltagID}/{wahlbezirksart}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)))
                .replace(`{${"wahlbezirksart"}}`, encodeURIComponent(String(wahlbezirksart)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {SetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUngueltigeWahlscheine: async (wahltagID: string, wahlbezirksart: SetUngueltigeWahlscheineWahlbezirksartEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('setUngueltigeWahlscheine', 'wahltagID', wahltagID)
            // verify required parameter 'wahlbezirksart' is not null or undefined
            assertParamExists('setUngueltigeWahlscheine', 'wahlbezirksart', wahlbezirksart)
            const localVarPath = `/businessActions/ungueltigews/{wahltagID}/{wahlbezirksart}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)))
                .replace(`{${"wahlbezirksart"}}`, encodeURIComponent(String(wahlbezirksart)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UngueltigeWahlscheineControllerApi - functional programming interface
 * @export
 */
export const UngueltigeWahlscheineControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UngueltigeWahlscheineControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Abrufen der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart. Kommen als Anhang im csv-Format mit den Spalten Nachname, Vorname und Nummer
         * @param {string} wahltagID 
         * @param {GetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUngueltigeWahlscheine(wahltagID: string, wahlbezirksart: GetUngueltigeWahlscheineWahlbezirksartEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUngueltigeWahlscheine(wahltagID, wahlbezirksart, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UngueltigeWahlscheineControllerApi.getUngueltigeWahlscheine']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {SetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setUngueltigeWahlscheine(wahltagID: string, wahlbezirksart: SetUngueltigeWahlscheineWahlbezirksartEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setUngueltigeWahlscheine(wahltagID, wahlbezirksart, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UngueltigeWahlscheineControllerApi.setUngueltigeWahlscheine']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UngueltigeWahlscheineControllerApi - factory interface
 * @export
 */
export const UngueltigeWahlscheineControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UngueltigeWahlscheineControllerApiFp(configuration)
    return {
        /**
         * Abrufen der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart. Kommen als Anhang im csv-Format mit den Spalten Nachname, Vorname und Nummer
         * @param {string} wahltagID 
         * @param {GetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUngueltigeWahlscheine(wahltagID: string, wahlbezirksart: GetUngueltigeWahlscheineWahlbezirksartEnum, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.getUngueltigeWahlscheine(wahltagID, wahlbezirksart, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart
         * @param {string} wahltagID 
         * @param {SetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setUngueltigeWahlscheine(wahltagID: string, wahlbezirksart: SetUngueltigeWahlscheineWahlbezirksartEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setUngueltigeWahlscheine(wahltagID, wahlbezirksart, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UngueltigeWahlscheineControllerApi - object-oriented interface
 * @export
 * @class UngueltigeWahlscheineControllerApi
 * @extends {BaseAPI}
 */
export class UngueltigeWahlscheineControllerApi extends BaseAPI {
    /**
     * Abrufen der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart. Kommen als Anhang im csv-Format mit den Spalten Nachname, Vorname und Nummer
     * @param {string} wahltagID 
     * @param {GetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UngueltigeWahlscheineControllerApi
     */
    public getUngueltigeWahlscheine(wahltagID: string, wahlbezirksart: GetUngueltigeWahlscheineWahlbezirksartEnum, options?: RawAxiosRequestConfig) {
        return UngueltigeWahlscheineControllerApiFp(this.configuration).getUngueltigeWahlscheine(wahltagID, wahlbezirksart, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern der ungueltigen Wahlscheine eines Wahltages für eine bestimmte Wahlbezirksart
     * @param {string} wahltagID 
     * @param {SetUngueltigeWahlscheineWahlbezirksartEnum} wahlbezirksart 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UngueltigeWahlscheineControllerApi
     */
    public setUngueltigeWahlscheine(wahltagID: string, wahlbezirksart: SetUngueltigeWahlscheineWahlbezirksartEnum, options?: RawAxiosRequestConfig) {
        return UngueltigeWahlscheineControllerApiFp(this.configuration).setUngueltigeWahlscheine(wahltagID, wahlbezirksart, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetUngueltigeWahlscheineWahlbezirksartEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB'
} as const;
export type GetUngueltigeWahlscheineWahlbezirksartEnum = typeof GetUngueltigeWahlscheineWahlbezirksartEnum[keyof typeof GetUngueltigeWahlscheineWahlbezirksartEnum];
/**
 * @export
 */
export const SetUngueltigeWahlscheineWahlbezirksartEnum = {
    Uwb: 'UWB',
    Bwb: 'BWB'
} as const;
export type SetUngueltigeWahlscheineWahlbezirksartEnum = typeof SetUngueltigeWahlscheineWahlbezirksartEnum[keyof typeof SetUngueltigeWahlscheineWahlbezirksartEnum];


/**
 * WahlbezirkeControllerApi - axios parameter creator
 * @export
 */
export const WahlbezirkeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Liste der Wahlbezirke, die einem vorgegebenen Wahltag (Parameter wahltagID) entsprechen.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlbezirke: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('getWahlbezirke', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/wahlbezirke/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahlbezirkeControllerApi - functional programming interface
 * @export
 */
export const WahlbezirkeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahlbezirkeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Liste der Wahlbezirke, die einem vorgegebenen Wahltag (Parameter wahltagID) entsprechen.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahlbezirke(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WahlbezirkDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahlbezirke(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlbezirkeControllerApi.getWahlbezirke']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahlbezirkeControllerApi - factory interface
 * @export
 */
export const WahlbezirkeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahlbezirkeControllerApiFp(configuration)
    return {
        /**
         * Laden der Liste der Wahlbezirke, die einem vorgegebenen Wahltag (Parameter wahltagID) entsprechen.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlbezirke(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<WahlbezirkDTO>> {
            return localVarFp.getWahlbezirke(wahltagID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahlbezirkeControllerApi - object-oriented interface
 * @export
 * @class WahlbezirkeControllerApi
 * @extends {BaseAPI}
 */
export class WahlbezirkeControllerApi extends BaseAPI {
    /**
     * Laden der Liste der Wahlbezirke, die einem vorgegebenen Wahltag (Parameter wahltagID) entsprechen.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlbezirkeControllerApi
     */
    public getWahlbezirke(wahltagID: string, options?: RawAxiosRequestConfig) {
        return WahlbezirkeControllerApiFp(this.configuration).getWahlbezirke(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahlenControllerApi - axios parameter creator
 * @export
 */
export const WahlenControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Wahlen des Wahltages { wahltagID }.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlen: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('getWahlen', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/wahlen/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern einer Liste von Wahlen.
         * @param {string} wahltagID 
         * @param {Array<WahlDTO>} wahlDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlen: async (wahltagID: string, wahlDTO: Array<WahlDTO>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('postWahlen', 'wahltagID', wahltagID)
            // verify required parameter 'wahlDTO' is not null or undefined
            assertParamExists('postWahlen', 'wahlDTO', wahlDTO)
            const localVarPath = `/businessActions/wahlen/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wahlDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Setzt die Attribute Farbe, Reihenfolge und Waehlerverzeichnis der vorhandenen Wahlen auf die Standardwerte.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetWahlen: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/resetWahlen`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahlenControllerApi - functional programming interface
 * @export
 */
export const WahlenControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahlenControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Wahlen des Wahltages { wahltagID }.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahlen(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WahlDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahlen(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlenControllerApi.getWahlen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern einer Liste von Wahlen.
         * @param {string} wahltagID 
         * @param {Array<WahlDTO>} wahlDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWahlen(wahltagID: string, wahlDTO: Array<WahlDTO>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postWahlen(wahltagID, wahlDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlenControllerApi.postWahlen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Setzt die Attribute Farbe, Reihenfolge und Waehlerverzeichnis der vorhandenen Wahlen auf die Standardwerte.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async resetWahlen(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.resetWahlen(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlenControllerApi.resetWahlen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahlenControllerApi - factory interface
 * @export
 */
export const WahlenControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahlenControllerApiFp(configuration)
    return {
        /**
         * Laden der Wahlen des Wahltages { wahltagID }.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlen(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<Array<WahlDTO>> {
            return localVarFp.getWahlen(wahltagID, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern einer Liste von Wahlen.
         * @param {string} wahltagID 
         * @param {Array<WahlDTO>} wahlDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlen(wahltagID: string, wahlDTO: Array<WahlDTO>, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postWahlen(wahltagID, wahlDTO, options).then((request) => request(axios, basePath));
        },
        /**
         * Setzt die Attribute Farbe, Reihenfolge und Waehlerverzeichnis der vorhandenen Wahlen auf die Standardwerte.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        resetWahlen(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.resetWahlen(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahlenControllerApi - object-oriented interface
 * @export
 * @class WahlenControllerApi
 * @extends {BaseAPI}
 */
export class WahlenControllerApi extends BaseAPI {
    /**
     * Laden der Wahlen des Wahltages { wahltagID }.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlenControllerApi
     */
    public getWahlen(wahltagID: string, options?: RawAxiosRequestConfig) {
        return WahlenControllerApiFp(this.configuration).getWahlen(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern einer Liste von Wahlen.
     * @param {string} wahltagID 
     * @param {Array<WahlDTO>} wahlDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlenControllerApi
     */
    public postWahlen(wahltagID: string, wahlDTO: Array<WahlDTO>, options?: RawAxiosRequestConfig) {
        return WahlenControllerApiFp(this.configuration).postWahlen(wahltagID, wahlDTO, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Setzt die Attribute Farbe, Reihenfolge und Waehlerverzeichnis der vorhandenen Wahlen auf die Standardwerte.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlenControllerApi
     */
    public resetWahlen(options?: RawAxiosRequestConfig) {
        return WahlenControllerApiFp(this.configuration).resetWahlen(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahltageControllerApi - axios parameter creator
 * @export
 */
export const WahltageControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Liste der Wahltage, aufsteigend sortiert nach Wahltag-Datum und nicht länger als 3 Monate in der Vergangenheit.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahltage: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/wahltage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahltageControllerApi - functional programming interface
 * @export
 */
export const WahltageControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahltageControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Liste der Wahltage, aufsteigend sortiert nach Wahltag-Datum und nicht länger als 3 Monate in der Vergangenheit.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahltage(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<WahltagDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahltage(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahltageControllerApi.getWahltage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahltageControllerApi - factory interface
 * @export
 */
export const WahltageControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahltageControllerApiFp(configuration)
    return {
        /**
         * Laden der Liste der Wahltage, aufsteigend sortiert nach Wahltag-Datum und nicht länger als 3 Monate in der Vergangenheit.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahltage(options?: RawAxiosRequestConfig): AxiosPromise<Array<WahltagDTO>> {
            return localVarFp.getWahltage(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahltageControllerApi - object-oriented interface
 * @export
 * @class WahltageControllerApi
 * @extends {BaseAPI}
 */
export class WahltageControllerApi extends BaseAPI {
    /**
     * Laden der Liste der Wahltage, aufsteigend sortiert nach Wahltag-Datum und nicht länger als 3 Monate in der Vergangenheit.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahltageControllerApi
     */
    public getWahltage(options?: RawAxiosRequestConfig) {
        return WahltageControllerApiFp(this.configuration).getWahltage(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahltermindatenControllerApi - axios parameter creator
 * @export
 */
export const WahltermindatenControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Löscht die Wahltermindaten eines bestimmten Wahltags.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWahltermindaten: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('deleteWahltermindaten', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/wahltermindaten/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Triggert die Einrichtung der Wahltermindaten.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putWahltermindaten: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('putWahltermindaten', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/wahltermindaten/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahltermindatenControllerApi - functional programming interface
 * @export
 */
export const WahltermindatenControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahltermindatenControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Löscht die Wahltermindaten eines bestimmten Wahltags.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteWahltermindaten(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteWahltermindaten(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahltermindatenControllerApi.deleteWahltermindaten']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Triggert die Einrichtung der Wahltermindaten.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async putWahltermindaten(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putWahltermindaten(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahltermindatenControllerApi.putWahltermindaten']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahltermindatenControllerApi - factory interface
 * @export
 */
export const WahltermindatenControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahltermindatenControllerApiFp(configuration)
    return {
        /**
         * Löscht die Wahltermindaten eines bestimmten Wahltags.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteWahltermindaten(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteWahltermindaten(wahltagID, options).then((request) => request(axios, basePath));
        },
        /**
         * Triggert die Einrichtung der Wahltermindaten.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        putWahltermindaten(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.putWahltermindaten(wahltagID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahltermindatenControllerApi - object-oriented interface
 * @export
 * @class WahltermindatenControllerApi
 * @extends {BaseAPI}
 */
export class WahltermindatenControllerApi extends BaseAPI {
    /**
     * Löscht die Wahltermindaten eines bestimmten Wahltags.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahltermindatenControllerApi
     */
    public deleteWahltermindaten(wahltagID: string, options?: RawAxiosRequestConfig) {
        return WahltermindatenControllerApiFp(this.configuration).deleteWahltermindaten(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Triggert die Einrichtung der Wahltermindaten.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahltermindatenControllerApi
     */
    public putWahltermindaten(wahltagID: string, options?: RawAxiosRequestConfig) {
        return WahltermindatenControllerApiFp(this.configuration).putWahltermindaten(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahlvorschlaegeControllerApi - axios parameter creator
 * @export
 */
export const WahlvorschlaegeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Wahlvorschlaege des Wahllokals {wahlbezirkID} für die Wahl {wahlID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlvorschlaege: async (wahlID: string, wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlID' is not null or undefined
            assertParamExists('getWahlvorschlaege', 'wahlID', wahlID)
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getWahlvorschlaege', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/wahlvorschlaege/{wahlID}/{wahlbezirkID}`
                .replace(`{${"wahlID"}}`, encodeURIComponent(String(wahlID)))
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahlvorschlaegeControllerApi - functional programming interface
 * @export
 */
export const WahlvorschlaegeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahlvorschlaegeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Wahlvorschlaege des Wahllokals {wahlbezirkID} für die Wahl {wahlID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahlvorschlaege(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WahlvorschlaegeDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahlvorschlaege(wahlID, wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlvorschlaegeControllerApi.getWahlvorschlaege']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahlvorschlaegeControllerApi - factory interface
 * @export
 */
export const WahlvorschlaegeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahlvorschlaegeControllerApiFp(configuration)
    return {
        /**
         * Laden der Wahlvorschlaege des Wahllokals {wahlbezirkID} für die Wahl {wahlID}.
         * @param {string} wahlID 
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlvorschlaege(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<WahlvorschlaegeDTO> {
            return localVarFp.getWahlvorschlaege(wahlID, wahlbezirkID, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahlvorschlaegeControllerApi - object-oriented interface
 * @export
 * @class WahlvorschlaegeControllerApi
 * @extends {BaseAPI}
 */
export class WahlvorschlaegeControllerApi extends BaseAPI {
    /**
     * Laden der Wahlvorschlaege des Wahllokals {wahlbezirkID} für die Wahl {wahlID}.
     * @param {string} wahlID 
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlvorschlaegeControllerApi
     */
    public getWahlvorschlaege(wahlID: string, wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return WahlvorschlaegeControllerApiFp(this.configuration).getWahlvorschlaege(wahlID, wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }
}



