name: wls

services:
  ### WLS-Backend Services
  wls-broadcast-service:
    container_name: wls-broadcast-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-broadcast-service:latest-dev@sha256:1da808b189f4159cd18ac960583130a505e6881d67a757a2826728cd760c10bf
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8200:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-infomanagement-service:
    container_name: wls-infomanagement-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-infomanagement-service:latest-dev@sha256:227a1e004e50654f1cbfcecd910aefb1b97b8ac10b3519a43b94660f51c7ee22
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8201:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-briefwahl-service:
    container_name: wls-briefwahl-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-briefwahl-service:latest-dev@sha256:3167a29164d8b28c8093f94117b08bbba800c7243c1abda9635adfd8746b153a
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8202:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-wahlvorbereitung-service:
    container_name: wls-wahlvorbereitung-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-wahlvorbereitung-service:latest-dev@sha256:5ed0ba831972501281c458131ee0b6c8fa9f737993f0ac5933cf62f8bec87de5
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8203:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-vorfaelleundvorkommnisse-service:
    container_name: wls-vorfaelleundvorkommnisse-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-vorfaelleundvorkommnisse-service:latest-dev@sha256:e8b8526c02616ce3dceeb05cf314bde22ec0fda270f150bdaafd8ab402615810
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8204:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-basisdaten-service:
    container_name: wls-basisdaten-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-basisdaten-service:latest-dev@sha256:31e6c09b3f3dbac75b61f070d13ff95490589ec864ec947d4d8fb67959b468d2
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - SERVICE_CONFIG_CLIENTS_EAI_BASEPATH=http://kubernetes.docker.internal:8300
      - SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH=http://kubernetes.docker.internal:8201
    ports:
      - 8205:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-monitoring-service:
    container_name: wls-monitoring-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-monitoring-service:latest-dev@sha256:c3d3ed0bee03506184f945989ae18e4a50c1b05331b705be189fa22eef252a6d
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - APP_CLIENTS_EAI_BASEPATH=http://kubernetes.docker.internal:8300
    ports:
      - 8206:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-wahlvorstand-service:
    container_name: wls-wahlvorstand-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-wahlvorstand-service:latest-dev@sha256:777218fc01e502c787ffd18a4886f3e5b83406af3fd4c66b1af5f7b756826b79
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - APP_CLIENTS_EAI_BASEPATH=http://kubernetes.docker.internal:8300
      - APP_CLIENTS_INFOMANAGEMENT_BASEPATH=http://kubernetes.docker.internal:8201
      - APP_CLIENTS_BASISDATEN_BASEPATH=http://kubernetes.docker.internal:8205
    ports:
      - 8207:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-ergebnismeldung-service:
    container_name: wls-ergebnismeldung-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-ergebnismeldung-service:latest-dev@sha256:02d7a5373f02d49ef773c66d9ea7e1c1819f5681086268614dfb1b72be1e1c9c
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - SERVICE_CONFIG_CLIENTS_EAI_BASEPATH=http://kubernetes.docker.internal:8300
      - SERVICE_CONFIG_CLIENTS_MONITORING_BASEPATH=http://kubernetes.docker.internal:8206
      - SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH=http://kubernetes.docker.internal:8201
      - SERVICE_CONFIG_CLIENTS_BASISDATEN_BASEPATH=http://kubernetes.docker.internal:8205
      - SERVICE_CONFIG_CLIENTS_BRIEFWAHL_BASEPATH=http://kubernetes.docker.internal:8202
      - SERVICE_CONFIG_CLIENTS_WAHLVORBEREITUNG_BASEPATH=http://kubernetes.docker.internal:8203
    ports:
      - 8208:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-admin-service:
    container_name: wls-admin-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-admin-service:latest-dev@sha256:04abfa7637428cba443dcded4b6bb0d3df6b7eb3d7ea1e833f517a15945dd3ca
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - SERVICE_CONFIG_CLIENTS_AUTH_BASEPATH=http://kubernetes.docker.internal:8100
      - SERVICE_CONFIG_CLIENTS_BASISDATEN_BASEPATH=http://kubernetes.docker.internal:8205
      - SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH=http://kubernetes.docker.internal:8201
      - SERVICE_CONFIG_CLIENTS_ERGEBNISMELDUNG_BASEPATH=http://kubernetes.docker.internal:8208
    ports:
      - 8209:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-eai-service:
    container_name: wls-eai-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-eai-service:latest-dev@sha256:7d42dbbb4feb1a125ce2a1a56f976196f01175bb20c3e61dfd39d723b4059335
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,db-dummydata,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8300:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  ### Infrastruktur erfassen
  wls-db-oracle:
    container_name: wls-db-oracle
    image: gvenzl/oracle-xe:21-faststart@sha256:62b2c30de9d5b76f8083688e3124db0691073d16fa072a5efe9c7d90c4962f1a
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: secret
      APP_USER: app_user
      APP_USER_PASSWORD: secret
    volumes:
      - './oracle-database:/container-entrypoint-startdb.d'
    networks:
      - services

  refarch-gateway-wls:
    container_name: wls-refarch-gateway-wls
    image: ghcr.io/it-at-m/refarch/refarch-gateway:1.6.0@sha256:df27f73a72c42f15e7d37267b2b726e70cc917bcf8b03f0b275787715477acae
    env_file:
      - .env
    ports:
      - "8083:8080"
    environment:
      - ALLOWED_ORIGINS_PUBLIC=http://localhost:*
      - ALLOWED_ORIGINS_CLIENTS=http://localhost:*
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/config/application-routes.yml
      - SPRING_PROFILES_ACTIVE=hazelcast-local
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=${SSO_USER_INFO_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_ISSUERURI=http://kubernetes.docker.internal:8100
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=${SSO_CLIENT_ID_WLS}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=${SSO_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=openid
    volumes:
      - './gateway_config_wls:/config'
    networks:
      - services
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    healthcheck:
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s
      test: [ "CMD-SHELL", "curl http://localhost:8080/actuator/health/liveness" ]
    security_opt:
      - no-new-privileges:true

  refarch-gateway-admin:
    container_name: wls-refarch-gateway-admin
    image: ghcr.io/it-at-m/refarch/refarch-gateway:1.6.0@sha256:df27f73a72c42f15e7d37267b2b726e70cc917bcf8b03f0b275787715477acae
    env_file:
      - .env
    ports:
      - "8084:8080"
    environment:
      - ALLOWED_ORIGINS_PUBLIC=http://localhost:*
      - ALLOWED_ORIGINS_CLIENTS=http://localhost:*
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/config/application-routes.yml
      - SPRING_PROFILES_ACTIVE=hazelcast-local
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=${SSO_USER_INFO_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SSO_ISSUERURI=http://kubernetes.docker.internal:8100
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=${SSO_CLIENT_ID_ADMIN}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=${SSO_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=openid
    volumes:
      - './gateway_config_admin:/config'
    networks:
      - services
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    healthcheck:
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 60s
      test: [ "CMD-SHELL", "curl http://localhost:8080/actuator/health/liveness" ]
    security_opt:
      - no-new-privileges:true

  wls-auth-service:
    container_name: wls-auth-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-auth-service:latest-dev@sha256:bca4f28304508cef77abb25b23ee81aa0171b0acf6153173cb674eeae1649473
    depends_on:
      - wls-db-oracle
    env_file:
      - .env
    environment:
      SERVICE_CONFIG_CRYPTO_KEY: please change me
      SERVICE_CONFIG_OAUTH2_CLIENTS_WAHLLOKALGUI_ID: ${SSO_CLIENT_ID_WLS}
      SERVICE_CONFIG_OAUTH2_JWK_RSA_INIT_SEED: change_me
      SPRING_PROFILES_ACTIVE: db-oracle,db-dummydata,dummy.ldap,plainTextLogging
      SPRING_DATASOURCE_URL: ${WLS_SERVICE_DB_URL}
      SERVER_PORT: 8080
      SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH: http://kubernetes.docker.internal:8201
      SERVICE_CONFIG_RSA_RSA_KEY_SETTING: STATIC_KEY
      SERVICE_CONFIG_RSA_PRIVATE-KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6pKOIWBSnplTN
        hDITf3SYDeJAkW5iK9cAGSPvPxnaQ+WilW3wKwYSe+Nbz0FiNU8MODfdzI5zShcV
        PmR7rIMybKtK5SIfcI5/hL3aJjoOvG/Ds+RIv2Ux6Em92w+lMNn+SpJz6SH6EHJ9
        ppPhcOahYPfZXE9dZk0y5KC2+RauQyKSp8v7e6W67Y297w+UBnl325Yy3MKY92n8
        WR1hwwUcaqA+k7dXBR29tooSdWPIXvBZ8zJoi6iKCkMURGjLUx1dk2owJenV3a7z
        tnVu2uoqGlIPxWXPAiMuy1eu0j+mbEdHBTbo81X5dHZ/nUOLTVocOJbjJ6eLhqiH
        0SqlsyyJAgMBAAECggEAIX6EPmaYJlHqLAuKNQeNc/Ah5zZyGboGVmUslrW7PPks
        T5YDabM+3rhO3938vNQWQHoiRHJ+KeBk7hIJVExsKvNndgRSsFOxrt6yd2Ce0KAu
        am9xC0EVtvQZr7GNSDbRGBpn19dBmq+y7CulpDJvoQxWzjILqBZAyl5PHSbsVA83
        UD+YV70zOs82QrPH5AtFnyqTjn+4M897dkC/gVsL+Il73mzLwnM++XzDDL1iyhDk
        eOf4Tkt0DT7fE6Rx2EmFoA/+kZF8xXyMgKx7Qcz/8GxKKkXHs1oUt3xeewEvTY9M
        suwZJQ+8DbhZz/n/9Q14P2bGit5bwj1usSLmT3He1QKBgQDzTzItxacAVhFyYYYX
        iR4wr3QtjXLD1hLTY2kqd/en0a9LGb3y2DcnIzoUALA5RgxxnLmvTDrYrevcEN1D
        3igAjLMdSaqjED5spZusUTtIkzZ6PRcbMPQyEq8hlE39yNlzqlkoGbpiDKxsvfz0
        Kuk7yT/7dlPQHGcc6ROUpERdFwKBgQDEYM2byXEQObrjnjBGbcpn2zpbf1Dni9n1
        yiXImKKyYzs5zoPVRbAtTzNKhlgPHdTjewWjGiTsJDvpRtjX/IcfewOi0ti8Zo8s
        bK/6Jnoh8Ho3rAYqNCRF7EPIwrHUlGbqz4Yd4/J4IH2bCwGhkSlMQUYveCBs6nM3
        +rx3VB8HXwKBgAQHMqB5XjtuMVnAbZTkK0DJFtZOOjEt0R/4zFvsoof/u7Q1l+R2
        Wetm9OYx4LkCBOC4pIZXb734mygIi3E9M1JXAfwhJRcQBMiNsVcX/TBFZ6h8bG6B
        z/koQAgBSY1DDv6QOmukiWZoKU6fkpmEQFpCCbIjEl4mqjpbTXyvf4Y/AoGAa0v5
        C4WlIRhp5LQp7FFQpi5CVHvb2KexD3rD6jZ7rrxJP+x2W7EX8am0fKOquZezGhe9
        nMBMLDogAfWTxW9U5P5xniVWBpqC3+MCw8sCMEkUfhafx691oj7VSnwWbfAny2RY
        Azzo3nniJzR8T6rgxalkj8sy7E+tZIi7MPflfEECgYATgg1iL4MECbv/UFEKLMOy
        kJIWk11TLC3OTsRQklaFDyJBwWfaGIXHxJthTlpNvg9iHTwv50vTGmodsMEYBOKa
        9WdmYw4OypqD46w5BU5jhJCraKe0aAKErzWmY+19B5dDWqjztfz07hVd2bCDn9v5
        249bUkZF/ppDXUlAaHxqhw==
        -----END PRIVATE KEY-----
      SERVICE_CONFIG_RSA_PUBLIC-KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuqSjiFgUp6ZUzYQyE390
        mA3iQJFuYivXABkj7z8Z2kPlopVt8CsGEnvjW89BYjVPDDg33cyOc0oXFT5ke6yD
        MmyrSuUiH3COf4S92iY6Drxvw7PkSL9lMehJvdsPpTDZ/kqSc+kh+hByfaaT4XDm
        oWD32VxPXWZNMuSgtvkWrkMikqfL+3uluu2Nve8PlAZ5d9uWMtzCmPdp/FkdYcMF
        HGqgPpO3VwUdvbaKEnVjyF7wWfMyaIuoigpDFERoy1MdXZNqMCXp1d2u87Z1btrq
        KhpSD8VlzwIjLstXrtI/pmxHRwU26PNV+XR2f51Di01aHDiW4yeni4aoh9EqpbMs
        iQIDAQAB
        -----END PUBLIC KEY-----
    ports:
      - 8100:8080
    networks:
      - services

  wls-gui-wahllokalsystem:
    container_name: wls-gui-wahllokalsystem
    image: ghcr.io/it-at-m/wahllokalsystem-wls-gui-wahllokalsystem:latest-dev@sha256:6e54ac66f8e8bf41fdebeaeaad760988fee888c027655826a85419c7bf68781d
    ports:
      - 8400:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

  wls-gui-admintool:
    container_name: wls-gui-admintool
    image: ghcr.io/it-at-m/wahllokalsystem-wls-gui-admintool:latest-dev@sha256:bb3a9ee9615048e8ef19a4112a9c282370086cd59b527cc635bc2a3148e8c5fe
    ports:
      - 8401:8080
    extra_hosts:
      - "kubernetes.docker.internal:host-gateway"
    networks:
      - services

networks:
  internal:
  services: