name: wls

services:
  ### WLS-Backend Services
  wls-broadcast-service:
    container_name: wls-broadcast-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-broadcast-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8200:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-infomanagement-service:
    container_name: wls-infomanagement-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-infomanagement-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8201:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-briefwahl-service:
    container_name: wls-briefwahl-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-briefwahl-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8202:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-wahlvorbereitung-service:
    container_name: wls-wahlvorbereitung-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-wahlvorbereitung-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8203:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-vorfaelleundvorkommnisse-service:
    container_name: wls-vorfaelleundvorkommnisse-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-vorfaelleundvorkommnisse-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8204:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-basisdaten-service:
    container_name: wls-basisdaten-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-basisdaten-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - SERVICE_CONFIG_CLIENTS_EAI_BASEPATH=http://host.docker.internal:8300
      - SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH=http://host.docker.internal:8201
    ports:
      - 8205:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-monitoring-service:
    container_name: wls-monitoring-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-monitoring-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - APP_CLIENTS_EAI_BASEPATH=http://host.docker.internal:8300
    ports:
      - 8206:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-wahlvorstand-service:
    container_name: wls-wahlvorstand-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-wahlvorstand-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - APP_CLIENTS_EAI_BASEPATH=http://host.docker.internal:8300
      - APP_CLIENTS_INFOMANAGEMENT_BASEPATH=http://host.docker.internal:8201
      - APP_CLIENTS_BASISDATEN_BASEPATH=http://host.docker.internal:8205
    ports:
      - 8207:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-ergebnismeldung-service:
    container_name: wls-ergebnismeldung-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-ergebnismeldung-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - SERVICE_CONFIG_CLIENTS_EAI_BASEPATH=http://host.docker.internal:8300
      - SERVICE_CONFIG_CLIENTS_MONITORING_BASEPATH=http://host.docker.internal:8206
      - SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH=http://host.docker.internal:8201
      - SERVICE_CONFIG_CLIENTS_BASISDATEN_BASEPATH=http://host.docker.internal:8205
      - SERVICE_CONFIG_CLIENTS_BRIEFWAHL_BASEPATH=http://host.docker.internal:8202
      - SERVICE_CONFIG_CLIENTS_WAHLVORBEREITUNG_BASEPATH=http://host.docker.internal:8203
    ports:
      - 8208:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-admin-service:
    container_name: wls-admin-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-admin-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
      - SERVICE_CONFIG_CLIENTS_AUTH_BASEPATH=http://host.docker.internal:8100
      - SERVICE_CONFIG_CLIENTS_BASISDATEN_BASEPATH=http://host.docker.internal:8205
      - SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH=http://host.docker.internal:8201
      - SERVICE_CONFIG_CLIENTS_ERGEBNISMELDUNG_BASEPATH=http://host.docker.internal:8208
    ports:
      - 8209:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-eai-service:
    container_name: wls-eai-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-eai-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=db-oracle,db-dummydata,plainTextLogging
      - SPRING_DATASOURCE_URL=${WLS_SERVICE_DB_URL}
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=${SSO_JWK_URI}
      - SECURITY_OAUTH2_RESOURCE_USER-INFO-URI=${SSO_USER_INFO_URI}
      - SERVER_PORT=8080
    ports:
      - 8300:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  ### Infrastruktur erfassen
  wls-db-oracle:
    container_name: wls-db-oracle
    image: gvenzl/oracle-xe:21-faststart@sha256:62b2c30de9d5b76f8083688e3124db0691073d16fa072a5efe9c7d90c4962f1a
    ports:
      - 1521:1521
    environment:
      ORACLE_PASSWORD: secret
      APP_USER: app_user
      APP_USER_PASSWORD: secret
    volumes:
      - './oracle-database:/container-entrypoint-startdb.d'
    networks:
      - services
    healthcheck:
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 120s
      test: [ "CMD-SHELL", "/opt/oracle/healthcheck.sh" ]

  refarch-gateway-wls:
    container_name: wls-refarch-gateway-wls
    image: ghcr.io/it-at-m/wahllokalsystem-wls-api-gateway:latest
    depends_on:
      wls-auth-service:
        condition: service_healthy
      wls-auth-service-reverse-proxy:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8083:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/config/application-routes.yml
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=${SSO_USER_INFO_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=${SSO_CLIENT_ID_WLS}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=${SSO_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=openid
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/config_ssl/truststore.p12 -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStoreType=PKCS12 -Dserver.ssl.enabled=false
    volumes:
      - './gateway_config_wls:/config'
      - './reverse-proxy-auth-service/ssl:/config_ssl' # Pfad zum Reverseproxy da dort die Certs und der Truststore liegen (siehe JAVA_TOOL_OPTIONS)
    networks:
      - services
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "gui.wls.host.docker.internal:host-gateway"
      - "auth.wls.host.docker.internal:host-gateway"
    healthcheck:
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 120s
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health" ]
    security_opt:
      - no-new-privileges:true

  refarch-gateway-admin:
    container_name: wls-refarch-gateway-admin
    image: ghcr.io/it-at-m/wahllokalsystem-wls-api-gateway:latest
    depends_on:
      wls-auth-service:
        condition: service_healthy
      wls-auth-service-reverse-proxy:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8084:8080"
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_CONFIG_ADDITIONAL_LOCATION=/config/application-routes.yml
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=${SSO_USER_INFO_URI}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_PROVIDER=sso
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTID=${SSO_CLIENT_ID_ADMIN}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_CLIENTSECRET=${SSO_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_SSO_SCOPE=openid
      - JAVA_TOOL_OPTIONS=-Djavax.net.ssl.trustStore=/config_ssl/truststore.p12 -Djavax.net.ssl.trustStorePassword=changeit -Djavax.net.ssl.trustStoreType=PKCS12 -Dserver.ssl.enabled=false
    volumes:
      - './gateway_config_admin:/config'
      - './reverse-proxy-auth-service/ssl:/config_ssl' # Pfad zum Reverseproxy da dort die Certs und der Truststore liegen (siehe JAVA_TOOL_OPTIONS)
    networks:
      - services
    extra_hosts:
      - "host.docker.internal:host-gateway"
      - "gui.wls.host.docker.internal:host-gateway"
      - "auth.wls.host.docker.internal:host-gateway"
    healthcheck:
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 120s
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health" ]
    security_opt:
      - no-new-privileges:true

  wls-auth-service:
    container_name: wls-auth-service
    image: ghcr.io/it-at-m/wahllokalsystem-wls-auth-service:latest
    depends_on:
      wls-db-oracle:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SERVICE_CONFIG_CRYPTO_KEY: please change me
      SERVICE_CONFIG_OAUTH2_CLIENTS_WAHLLOKALGUI_ID: ${SSO_CLIENT_ID_WLS}
      SERVICE_CONFIG_OAUTH2_JWK_RSA_INIT_SEED: change_me
      SPRING_LDAP_EMBEDDED_LDIF: file:/configLdap/users.ldif
      SPRING_PROFILES_ACTIVE: db-oracle,db-dummydata,dummy.ldap,plainTextLogging
      SPRING_DATASOURCE_URL: ${WLS_SERVICE_DB_URL}
      SERVER_PORT: 8080
      SERVICE_CONFIG_CLIENTS_INFOMANAGEMENT_BASEPATH: http://host.docker.internal:8201
      SERVICE_CONFIG_RSA_RSA_KEY_SETTING: STATIC_KEY
      SERVICE_CONFIG_RSA_PRIVATE-KEY: |
        -----BEGIN PRIVATE KEY-----
        MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQC6pKOIWBSnplTN
        hDITf3SYDeJAkW5iK9cAGSPvPxnaQ+WilW3wKwYSe+Nbz0FiNU8MODfdzI5zShcV
        PmR7rIMybKtK5SIfcI5/hL3aJjoOvG/Ds+RIv2Ux6Em92w+lMNn+SpJz6SH6EHJ9
        ppPhcOahYPfZXE9dZk0y5KC2+RauQyKSp8v7e6W67Y297w+UBnl325Yy3MKY92n8
        WR1hwwUcaqA+k7dXBR29tooSdWPIXvBZ8zJoi6iKCkMURGjLUx1dk2owJenV3a7z
        tnVu2uoqGlIPxWXPAiMuy1eu0j+mbEdHBTbo81X5dHZ/nUOLTVocOJbjJ6eLhqiH
        0SqlsyyJAgMBAAECggEAIX6EPmaYJlHqLAuKNQeNc/Ah5zZyGboGVmUslrW7PPks
        T5YDabM+3rhO3938vNQWQHoiRHJ+KeBk7hIJVExsKvNndgRSsFOxrt6yd2Ce0KAu
        am9xC0EVtvQZr7GNSDbRGBpn19dBmq+y7CulpDJvoQxWzjILqBZAyl5PHSbsVA83
        UD+YV70zOs82QrPH5AtFnyqTjn+4M897dkC/gVsL+Il73mzLwnM++XzDDL1iyhDk
        eOf4Tkt0DT7fE6Rx2EmFoA/+kZF8xXyMgKx7Qcz/8GxKKkXHs1oUt3xeewEvTY9M
        suwZJQ+8DbhZz/n/9Q14P2bGit5bwj1usSLmT3He1QKBgQDzTzItxacAVhFyYYYX
        iR4wr3QtjXLD1hLTY2kqd/en0a9LGb3y2DcnIzoUALA5RgxxnLmvTDrYrevcEN1D
        3igAjLMdSaqjED5spZusUTtIkzZ6PRcbMPQyEq8hlE39yNlzqlkoGbpiDKxsvfz0
        Kuk7yT/7dlPQHGcc6ROUpERdFwKBgQDEYM2byXEQObrjnjBGbcpn2zpbf1Dni9n1
        yiXImKKyYzs5zoPVRbAtTzNKhlgPHdTjewWjGiTsJDvpRtjX/IcfewOi0ti8Zo8s
        bK/6Jnoh8Ho3rAYqNCRF7EPIwrHUlGbqz4Yd4/J4IH2bCwGhkSlMQUYveCBs6nM3
        +rx3VB8HXwKBgAQHMqB5XjtuMVnAbZTkK0DJFtZOOjEt0R/4zFvsoof/u7Q1l+R2
        Wetm9OYx4LkCBOC4pIZXb734mygIi3E9M1JXAfwhJRcQBMiNsVcX/TBFZ6h8bG6B
        z/koQAgBSY1DDv6QOmukiWZoKU6fkpmEQFpCCbIjEl4mqjpbTXyvf4Y/AoGAa0v5
        C4WlIRhp5LQp7FFQpi5CVHvb2KexD3rD6jZ7rrxJP+x2W7EX8am0fKOquZezGhe9
        nMBMLDogAfWTxW9U5P5xniVWBpqC3+MCw8sCMEkUfhafx691oj7VSnwWbfAny2RY
        Azzo3nniJzR8T6rgxalkj8sy7E+tZIi7MPflfEECgYATgg1iL4MECbv/UFEKLMOy
        kJIWk11TLC3OTsRQklaFDyJBwWfaGIXHxJthTlpNvg9iHTwv50vTGmodsMEYBOKa
        9WdmYw4OypqD46w5BU5jhJCraKe0aAKErzWmY+19B5dDWqjztfz07hVd2bCDn9v5
        249bUkZF/ppDXUlAaHxqhw==
        -----END PRIVATE KEY-----
      SERVICE_CONFIG_RSA_PUBLIC-KEY: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuqSjiFgUp6ZUzYQyE390
        mA3iQJFuYivXABkj7z8Z2kPlopVt8CsGEnvjW89BYjVPDDg33cyOc0oXFT5ke6yD
        MmyrSuUiH3COf4S92iY6Drxvw7PkSL9lMehJvdsPpTDZ/kqSc+kh+hByfaaT4XDm
        oWD32VxPXWZNMuSgtvkWrkMikqfL+3uluu2Nve8PlAZ5d9uWMtzCmPdp/FkdYcMF
        HGqgPpO3VwUdvbaKEnVjyF7wWfMyaIuoigpDFERoy1MdXZNqMCXp1d2u87Z1btrq
        KhpSD8VlzwIjLstXrtI/pmxHRwU26PNV+XR2f51Di01aHDiW4yeni4aoh9EqpbMs
        iQIDAQAB
        -----END PUBLIC KEY-----
    volumes:
      - './ldap:/configLdap'
    ports:
      - 8100:8080
    networks:
      - services
    healthcheck:
      interval: 30s
      timeout: 60s
      retries: 3
      start_period: 120s
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/actuator/health" ]

  wls-gui-wahllokalsystem:
    container_name: wls-gui-wahllokalsystem
    image: ghcr.io/it-at-m/wahllokalsystem-wls-gui-wahllokalsystem:latest
    ports:
      - 8400:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-gui-admintool:
    container_name: wls-gui-admintool
    image: ghcr.io/it-at-m/wahllokalsystem-wls-gui-admintool:latest
    ports:
      - 8401:8080
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - services

  wls-refarch-gateway-wls-reverse-proxy:
    container_name: wls-refarch-gateway-wls-reverse-proxy
    image: nginx:alpine@sha256:e7257f1ef28ba17cf7c248cb8ccf6f0c6e0228ab9c315c152f9c203cd34cf6d1
    ports:
      - "58083:443"
    volumes:
      - ./reverse-proxy-gui-wls/ssl:/etc/nginx/ssl
      - ./reverse-proxy-gui-wls/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always

  wls-auth-service-reverse-proxy:
    container_name: wls-auth-service-reverse-proxy
    image: nginx:alpine@sha256:e7257f1ef28ba17cf7c248cb8ccf6f0c6e0228ab9c315c152f9c203cd34cf6d1
    ports:
      - "58100:443"
    volumes:
      - ./reverse-proxy-auth-service/ssl:/etc/nginx/ssl
      - ./reverse-proxy-auth-service/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    healthcheck:
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
      test: [ "CMD-SHELL", "curl -f --insecure https://localhost:443/nginx-health" ]

networks:
  internal:
  services: