### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get Konfigurierte Wahltage (needs profile 'dummy.clients' to make this work because of internal calls to other services)
GET {{ WLS_ADMIN_SERVICE_URL }}/businessActions/konfigurierteWahltage
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json