### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

###
GET {{ WLS_BRIEFWAHL_SERVICE_URL }}/businessActions/beanstandeteWahlbriefe/wbz-1/1
Authorization: Bearer {{$auth.token("auth-service")}}

###
POST {{ WLS_BRIEFWAHL_SERVICE_URL }}/businessActions/beanstandeteWahlbriefe/wbz-1/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "beanstandeteWahlbriefe": {
    "wahl1": [
      "ZUGELASSEN",
      "KEIN_ORIGINAL_SCHEIN",
      "UNTERSCHRIFT_FEHLT"
    ]
  }
}

###
POST {{ WLS_BRIEFWAHL_SERVICE_URL }}/businessActions/beanstandeteWahlbriefe/wbz-1/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "beanstandeteWahlbriefe": {
    "wahl2": [
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN"
    ],
    "wahl3": [
      "ZUGELASSEN",
      "UNTERSCHRIFT_FEHLT",
      "ZUGELASSEN",
      "UNTERSCHRIFT_FEHLT"
    ]
  }
}