GET http://localhost:39146/businessActions/beanstandeteWahlbriefe/wbz-1/1

###
POST http://localhost:39146/businessActions/beanstandeteWahlbriefe/wbz-1/1
Content-Type: application/json

{
  "beanstandeteWahlbriefe": {
    "wahl1": [
      "ZUGELASSEN",
      "KEIN_ORIGINAL_SCHEIN",
      "UNTERSCHRIFT_FEHLT"
    ]
  }
}

###
POST http://localhost:39146/businessActions/beanstandeteWahlbriefe/wbz-1/1
Content-Type: application/json

{
  "beanstandeteWahlbriefe": {
    "wahl2": [
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN",
      "ZUGELASSEN"
    ],
    "wahl3": [
      "ZUGELASSEN",
      "UNTERSCHRIFT_FEHLT",
      "ZUGELASSEN",
      "UNTERSCHRIFT_FEHLT"
    ]
  }
}