### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wahlbriefdaten wbz-1
POST {{ WLS_BRIEFWAHL_SERVICE_URL }}/businessActions/wahlbriefdaten/wbz-1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "nachtraege": 12,
  "nachtraeglichUeberbrachte": 1,
  "verzeichnisseUngueltige": 5,
  "wahlbriefe": 23,
  "zeitNachtraeglichUeberbrachte": "2024-06-09T23:59:12.123"
}

### GET wahlbriefdaten wbz-1
GET {{ WLS_BRIEFWAHL_SERVICE_URL }}/businessActions/wahlbriefdaten/wbz-1
Authorization: Bearer {{$auth.token("auth-service")}}