### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlbezirkID | user wls_all_bwb
GET {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/briefwahlvorbereitung/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wahlbezirkID | user wls_all_bwb
POST {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/briefwahlvorbereitung/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "urnenAnzahl": [
    {
      "anzahl": 1,
      "urneVersiegelt": true,
      "wahlID": "28039463-3d3d-4ce5-acc1-0bef931a4409"
    }
  ]
}
