### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wbzID-1
GET {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/fortsetzungsUhrzeit/wbzID-1
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wbzID-1
POST {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/fortsetzungsUhrzeit/wbzID-1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "fortsetzungsUhrzeit": "2024-06-10T17:05:33.505"
}