### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlbezirkID | user wls_all_uwb
GET {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/urnenwahlVorbereitung/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wahlbezirkID | user wls_all_uwb
POST {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/urnenwahlVorbereitung/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "anzahlNebenraeume": 10,
  "anzahlWahlkabinen": 12,
  "anzahlWahltische": 21,
  "urnenAnzahl": [
    {
      "anzahl": 1,
      "urneVersiegelt": true,
      "wahlID": "28039463-3d3d-4ce5-acc1-0bef931a4409"
    }
  ]
}
