### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlbezirkID | user wls_all_uwb
GET {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/urnenwahlSchliessungsUhrzeit/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wahlbezirkID | user wls_all_uwb
POST {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/urnenwahlSchliessungsUhrzeit/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "schliessungsuhrzeit": "2024-06-10T18:05:33.505"
}
