### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlbezirkID
GET {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/waehlerverzeichnis/wahlbezirkID/1
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wbzID-1/2
GET {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/waehlerverzeichnis/wbzID-1/2
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wahlbezirkID/1
POST {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/waehlerverzeichnis/wahlbezirkID/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "verzeichnisLagVor": true,
  "berichtigungVorBeginnDerAbstimmung": true,
  "nachtraeglicheBerichtigung": true,
  "mitteilungUeberUngueltigeWahlscheineErhalten": true
}

### POST wahlbezirkID/2
POST {{ WLS_WAHLVORBEREITUNG_SERVICE_URL }}/businessActions/waehlerverzeichnis/wahlbezirkID/2
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "verzeichnisLagVor": false,
  "berichtigungVorBeginnDerAbstimmung": false,
  "nachtraeglicheBerichtigung": true,
  "mitteilungUeberUngueltigeWahlscheineErhalten": true
}