### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Ausdruck for Meldungsart "V1" for wahlID and wahlbezirkID
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/ausdruck/wahlID/wahlbezirkID/V1/html
Authorization: Bearer {{$auth.token("auth-service")}}

### GET all Ausdrucke for wahlID and wahlbezirkID
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/ausdruck/wahlID/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}

### POST Ausdruck for Meldungsart "V1" for wahlID and wahlbezirkID
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/ausdruck/wahlID/wahlbezirkID/V1/html
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-service")}}

{
  "content": "Testcontent1"
}

### POST Ausdruck for Meldungsart "V3" for wahlID and wahlbezirkID
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/ausdruck/wahlID/wahlbezirkID/V3/html
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-service")}}

{
  "content": "Testcontent2"
}