### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET A-Werte (needs profile 'dummy.clients')
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/awerte/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}

### Initialisiere A-Werte (needs profile 'dummy.clients', stores AWerte entity in local DB retrieved from DummyClient )
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/awerte/init
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

[
  "wahlbezirkID",
  "wahlbezirkIDXYZ"
]
