### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET A-Werte (needs profile 'dummy.clients') | user wls_all_uwb
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/awerte/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

### Initialisiere A-Werte (needs profile 'dummy.clients', stores AWerte entity in local DB retrieved from DummyClient ) | user wls_all_uwb
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/awerte/init
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

[
  "9899cae4-df9a-4ffc-a940-f20cf2280171"
]

### GET A-Werte (needs profile 'dummy.clients') | user wls_all_bwb
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/awerte/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

### Initialisiere A-Werte (needs profile 'dummy.clients', stores AWerte entity in local DB retrieved from DummyClient ) | user wls_all_bwb
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/awerte/init
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

[
  "9081145c-dc16-4a9b-8255-5c49ddb98c14"
]
