### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET status wahlID/wahlbezirkID
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/status/wahlID/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}

### POST status with all done
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/status/wahlID/wahlbezirkID
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-service")}}

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID",
    "wahlbezirkID": "wahlbezirkID"
  },
  "niederschrift": {
    "gedruckt": true,
    "sendeuhrzeit": "2024-12-03T11:12:13",
    "uebermittelt": true,
    "validierungsstatus": "VALIDE"
  },
  "schnellmeldung": {
    "validierungsstatus": "VALIDE",
    "uebermittelt": true,
    "sendeuhrzeit": "2024-12-03T09:10:11",
    "gedruckt": true
  }
}

### POST status with schnellmeldung done
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/status/wahlID/wahlbezirkID
Content-Type: application/json
Authorization: Bearer {{$auth.token("auth-service")}}

{
  "bezirkUndWahlID": {
    "wahlID": "wahlID",
    "wahlbezirkID": "wahlbezirkID"
  },
  "niederschrift": {
    "validierungsstatus": "NICHT_GESENDET",
    "gedruckt": false
  },
  "schnellmeldung": {
    "validierungsstatus": "VALIDE",
    "uebermittelt": true,
    "sendeuhrzeit": "2024-12-03T09:10:11",
    "gedruckt": true
  }
}