### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get stimmabgabevermerke wahlbezirkID1 wvznr1 | user wls_all_uwb
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/9899cae4-df9a-4ffc-a940-f20cf2280171/1
Authorization: Bearer {{$auth.token("auth-service")}}

### POST stimmabgabevermerke - 1 Wahldaten | user wls_all_uwb
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/9899cae4-df9a-4ffc-a940-f20cf2280171/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "9899cae4-df9a-4ffc-a940-f20cf2280171",
  "waehlerverzeichnisNummer": 1,
  "anzahlBlaetter": 2,
  "wahldaten": [
    {
      "waehlerverzeichnisNummer": 1,
      "wahlbezirkID": "9899cae4-df9a-4ffc-a940-f20cf2280171",
      "wahlID": "28039463-3d3d-4ce5-acc1-0bef931a4409",
      "eingenommeneWahlscheine": [
        {
          "anzahl": 2,
          "stimmzettelart": "KLEIN"
        },
        {
          "anzahl": 4,
          "stimmzettelart": "BEIDE"
        },
        {
          "anzahl": 12,
          "stimmzettelart": "GROSS"
        }
      ],
      "vermerke": [
        {
          "blattnummer": 2,
          "stimmzettel": [
            {
              "anzahl": 1,
              "stimmzettelart": "GROSS"
            },
            {
              "anzahl": 1,
              "stimmzettelart": "KLEIN"
            }
          ]
        }
      ]
    }
  ]
}

### Get stimmabgabevermerke wahlbezirkID1 wvznr1 | user wls_all_bwb
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/9081145c-dc16-4a9b-8255-5c49ddb98c14/1
Authorization: Bearer {{$auth.token("auth-service")}}

### POST stimmabgabevermerke - 1 Wahldaten | user wls_all_bwb
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/9081145c-dc16-4a9b-8255-5c49ddb98c14/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "9081145c-dc16-4a9b-8255-5c49ddb98c14",
  "waehlerverzeichnisNummer": 1,
  "anzahlBlaetter": 2,
  "wahldaten": [
    {
      "waehlerverzeichnisNummer": 1,
      "wahlbezirkID": "9081145c-dc16-4a9b-8255-5c49ddb98c14",
      "wahlID": "28039463-3d3d-4ce5-acc1-0bef931a4409",
      "eingenommeneWahlscheine": [
        {
          "anzahl": 2,
          "stimmzettelart": "KLEIN"
        },
        {
          "anzahl": 4,
          "stimmzettelart": "BEIDE"
        },
        {
          "anzahl": 12,
          "stimmzettelart": "GROSS"
        }
      ],
      "vermerke": [
        {
          "blattnummer": 2,
          "stimmzettel": [
            {
              "anzahl": 1,
              "stimmzettelart": "GROSS"
            },
            {
              "anzahl": 1,
              "stimmzettelart": "KLEIN"
            }
          ]
        }
      ]
    }
  ]
}
