### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get stimmabgabevermerke wahlbezirkID1 wvznr1
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/wahlbezirkID1/1
Authorization: Bearer {{$auth.token("auth-service")}}

### POST stimmabgabevermerke - 2 Wahldaten
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/wahlbezirkID/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "wahlbezirkID",
  "waehlerverzeichnisNummer": 1,
  "anzahlBlaetter": 2,
  "wahldaten": [
    {
      "waehlerverzeichnisNummer": 1,
      "wahlbezirkID": "wahlbezirkID",
      "wahlID": "wahlID1",
      "eingenommeneWahlscheine": [
        {
          "anzahl": 2,
          "stimmzettelart": "KLEIN"
        },
        {
          "anzahl": 4,
          "stimmzettelart": "BEIDE"
        },
        {
          "anzahl": 12,
          "stimmzettelart": "GROSS"
        }
      ],
      "vermerke": [
        {
          "blattnummer": 1,
          "stimmzettel": [
            {
              "anzahl": 1,
              "stimmzettelart": "GROSS"
            },
            {
              "anzahl": 1,
              "stimmzettelart": "KLEIN"
            }
          ]
        }
      ]
    },
    {
      "waehlerverzeichnisNummer": 1,
      "wahlbezirkID": "wahlbezirkID",
      "wahlID": "wahlID2",
      "eingenommeneWahlscheine": [
        {
          "anzahl": 2,
          "stimmzettelart": "KLEIN"
        },
        {
          "anzahl": 4,
          "stimmzettelart": "BEIDE"
        },
        {
          "anzahl": 12,
          "stimmzettelart": "GROSS"
        }
      ],
      "vermerke": [
        {
          "blattnummer": 1,
          "stimmzettel": [
            {
              "anzahl": 1,
              "stimmzettelart": "GROSS"
            },
            {
              "anzahl": 1,
              "stimmzettelart": "KLEIN"
            }
          ]
        }
      ]
    }
  ]
}

### POST stimmabgabevermerke - 1 Wahldaten
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/businessActions/stimmabgabevermerke/wahlbezirkID1/1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "wahlbezirkID1",
  "waehlerverzeichnisNummer": 1,
  "anzahlBlaetter": 2,
  "wahldaten": [
    {
      "waehlerverzeichnisNummer": 1,
      "wahlbezirkID": "wahlbezirkID1",
      "wahlID": "other Wahl",
      "eingenommeneWahlscheine": [
        {
          "anzahl": 2,
          "stimmzettelart": "KLEIN"
        },
        {
          "anzahl": 4,
          "stimmzettelart": "BEIDE"
        },
        {
          "anzahl": 12,
          "stimmzettelart": "GROSS"
        }
      ],
      "vermerke": [
        {
          "blattnummer": 1,
          "stimmzettel": [
            {
              "anzahl": 1,
              "stimmzettelart": "GROSS"
            },
            {
              "anzahl": 1,
              "stimmzettelart": "KLEIN"
            }
          ]
        }
      ]
    }
  ]
}