### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get stimmabgabevermerke wahlbezirkID1 wvznr1 | user wls_all_uwb
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/wahl/b2c3d4e5-f6a7-4b8c-9d0e-1f2a3b4c5d6e/wahlbezirk/d4e5f6a7-b8c9-4d0e-1f2a-3b4c5d6e7f8a/wvz/1/stimmabgabevermerke
Authorization: Bearer {{$auth.token("auth-service")}}

### Get stimmabgabevermerke beispieldaten
GET {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/wahl/wahlID/wahlbezirk/wahlbezirkID/wvz/0/stimmabgabevermerke
Authorization: Bearer {{$auth.token("auth-service")}}

### Post Wahldaten
POST {{ WLS_ERGEBNISMELDUNG_SERVICE_URL }}/wahl/wahlID/wahlbezirk/wahlbezirkID/wvz/0/stimmabgabevermerke
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "waehlerverzeichnisNummer": 42,
  "wahlbezirkID": "9899cae4-df9a-4ffc-a940-f20cf2280171",
  "wahlID": "28039463-3d3d-4ce5-acc1-0bef931a4409",
  "eingenommeneWahlscheine": [
    {
      "anzahl": 21,
      "stimmzettelart": "KLEIN"
    },
    {
      "anzahl": 41,
      "stimmzettelart": "BEIDE"
    },
    {
      "anzahl": 121,
      "stimmzettelart": "GROSS"
    }
  ],
  "vermerke": [
    {
      "blattnummer": 11,
      "stimmzettel": [
        {
          "anzahl": 11,
          "stimmzettelart": "GROSS"
        },
        {
          "anzahl": 21,
          "stimmzettelart": "KLEIN"
        }
      ]
    }
  ]
}
