/* tslint:disable */
/* eslint-disable */
/**
 * Briefwahl Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BeanstandeteWahlbriefeCreateDTO
 */
export interface BeanstandeteWahlbriefeCreateDTO {
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof BeanstandeteWahlbriefeCreateDTO
     */
    'beanstandeteWahlbriefe': { [key: string]: Array<string>; };
}

export const BeanstandeteWahlbriefeCreateDTOBeanstandeteWahlbriefeEnum = {
    Zugelassen: 'ZUGELASSEN',
    ScheinUngueltig: 'SCHEIN_UNGUELTIG',
    KeinOriginalSchein: 'KEIN_ORIGINAL_SCHEIN',
    UnterschriftFehlt: 'UNTERSCHRIFT_FEHLT',
    UmschlagFehlt: 'UMSCHLAG_FEHLT',
    LoseStimmzettel: 'LOSE_STIMMZETTEL',
    WahlbriefUndUmschlagOffen: 'WAHLBRIEF_UND_UMSCHLAG_OFFEN',
    ScheineUngleichUmschlaege: 'SCHEINE_UNGLEICH_UMSCHLAEGE',
    UmschlagNichtAmtlich: 'UMSCHLAG_NICHT_AMTLICH',
    UmschlagGefaehrdetWahlgeheimnis: 'UMSCHLAG_GEFAEHRDET_WAHLGEHEIMNIS',
    GegenstandImUmschlag: 'GEGENSTAND_IM_UMSCHLAG',
    NichtWahlberechtigt: 'NICHT_WAHLBERECHTIGT'
} as const;

export type BeanstandeteWahlbriefeCreateDTOBeanstandeteWahlbriefeEnum = typeof BeanstandeteWahlbriefeCreateDTOBeanstandeteWahlbriefeEnum[keyof typeof BeanstandeteWahlbriefeCreateDTOBeanstandeteWahlbriefeEnum];

/**
 * 
 * @export
 * @interface BeanstandeteWahlbriefeDTO
 */
export interface BeanstandeteWahlbriefeDTO {
    /**
     * 
     * @type {string}
     * @memberof BeanstandeteWahlbriefeDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {number}
     * @memberof BeanstandeteWahlbriefeDTO
     */
    'waehlerverzeichnisNummer': number;
    /**
     * 
     * @type {{ [key: string]: Array<string>; }}
     * @memberof BeanstandeteWahlbriefeDTO
     */
    'beanstandeteWahlbriefe': { [key: string]: Array<string>; };
}

export const BeanstandeteWahlbriefeDTOBeanstandeteWahlbriefeEnum = {
    Zugelassen: 'ZUGELASSEN',
    ScheinUngueltig: 'SCHEIN_UNGUELTIG',
    KeinOriginalSchein: 'KEIN_ORIGINAL_SCHEIN',
    UnterschriftFehlt: 'UNTERSCHRIFT_FEHLT',
    UmschlagFehlt: 'UMSCHLAG_FEHLT',
    LoseStimmzettel: 'LOSE_STIMMZETTEL',
    WahlbriefUndUmschlagOffen: 'WAHLBRIEF_UND_UMSCHLAG_OFFEN',
    ScheineUngleichUmschlaege: 'SCHEINE_UNGLEICH_UMSCHLAEGE',
    UmschlagNichtAmtlich: 'UMSCHLAG_NICHT_AMTLICH',
    UmschlagGefaehrdetWahlgeheimnis: 'UMSCHLAG_GEFAEHRDET_WAHLGEHEIMNIS',
    GegenstandImUmschlag: 'GEGENSTAND_IM_UMSCHLAG',
    NichtWahlberechtigt: 'NICHT_WAHLBERECHTIGT'
} as const;

export type BeanstandeteWahlbriefeDTOBeanstandeteWahlbriefeEnum = typeof BeanstandeteWahlbriefeDTOBeanstandeteWahlbriefeEnum[keyof typeof BeanstandeteWahlbriefeDTOBeanstandeteWahlbriefeEnum];

/**
 * 
 * @export
 * @interface WahlbriefdatenDTO
 */
export interface WahlbriefdatenDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlbriefdatenDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenDTO
     */
    'wahlbriefe'?: number;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenDTO
     */
    'verzeichnisseUngueltige'?: number;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenDTO
     */
    'nachtraege'?: number;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenDTO
     */
    'nachtraeglichUeberbrachte'?: number;
    /**
     * 
     * @type {string}
     * @memberof WahlbriefdatenDTO
     */
    'zeitNachtraeglichUeberbrachte'?: string;
}
/**
 * 
 * @export
 * @interface WahlbriefdatenWriteDTO
 */
export interface WahlbriefdatenWriteDTO {
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenWriteDTO
     */
    'wahlbriefe'?: number;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenWriteDTO
     */
    'verzeichnisseUngueltige'?: number;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenWriteDTO
     */
    'nachtraege'?: number;
    /**
     * 
     * @type {number}
     * @memberof WahlbriefdatenWriteDTO
     */
    'nachtraeglichUeberbrachte'?: number;
    /**
     * 
     * @type {string}
     * @memberof WahlbriefdatenWriteDTO
     */
    'zeitNachtraeglichUeberbrachte'?: string;
}
/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * BeanstandeteWahlbriefeControllerApi - axios parameter creator
 * @export
 */
export const BeanstandeteWahlbriefeControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Beanstandeten Wahlbriefe mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
         * @param {string} wahlbezirkID 
         * @param {number} waehlerverzeichnisNummer 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeanstandeteWahlbriefe: async (wahlbezirkID: string, waehlerverzeichnisNummer: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getBeanstandeteWahlbriefe', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'waehlerverzeichnisNummer' is not null or undefined
            assertParamExists('getBeanstandeteWahlbriefe', 'waehlerverzeichnisNummer', waehlerverzeichnisNummer)
            const localVarPath = `/businessActions/beanstandeteWahlbriefe/{wahlbezirkID}/{waehlerverzeichnisNummer}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)))
                .replace(`{${"waehlerverzeichnisNummer"}}`, encodeURIComponent(String(waehlerverzeichnisNummer)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern von Beanstandeten Wahlbriefen mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
         * @param {string} wahlbezirkID 
         * @param {number} waehlerverzeichnisNummer 
         * @param {BeanstandeteWahlbriefeCreateDTO} beanstandeteWahlbriefeCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setBeanstandeteWahlbriefe: async (wahlbezirkID: string, waehlerverzeichnisNummer: number, beanstandeteWahlbriefeCreateDTO: BeanstandeteWahlbriefeCreateDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('setBeanstandeteWahlbriefe', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'waehlerverzeichnisNummer' is not null or undefined
            assertParamExists('setBeanstandeteWahlbriefe', 'waehlerverzeichnisNummer', waehlerverzeichnisNummer)
            // verify required parameter 'beanstandeteWahlbriefeCreateDTO' is not null or undefined
            assertParamExists('setBeanstandeteWahlbriefe', 'beanstandeteWahlbriefeCreateDTO', beanstandeteWahlbriefeCreateDTO)
            const localVarPath = `/businessActions/beanstandeteWahlbriefe/{wahlbezirkID}/{waehlerverzeichnisNummer}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)))
                .replace(`{${"waehlerverzeichnisNummer"}}`, encodeURIComponent(String(waehlerverzeichnisNummer)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(beanstandeteWahlbriefeCreateDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BeanstandeteWahlbriefeControllerApi - functional programming interface
 * @export
 */
export const BeanstandeteWahlbriefeControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BeanstandeteWahlbriefeControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Beanstandeten Wahlbriefe mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
         * @param {string} wahlbezirkID 
         * @param {number} waehlerverzeichnisNummer 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBeanstandeteWahlbriefe(wahlbezirkID: string, waehlerverzeichnisNummer: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BeanstandeteWahlbriefeDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBeanstandeteWahlbriefe(wahlbezirkID, waehlerverzeichnisNummer, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BeanstandeteWahlbriefeControllerApi.getBeanstandeteWahlbriefe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern von Beanstandeten Wahlbriefen mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
         * @param {string} wahlbezirkID 
         * @param {number} waehlerverzeichnisNummer 
         * @param {BeanstandeteWahlbriefeCreateDTO} beanstandeteWahlbriefeCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setBeanstandeteWahlbriefe(wahlbezirkID: string, waehlerverzeichnisNummer: number, beanstandeteWahlbriefeCreateDTO: BeanstandeteWahlbriefeCreateDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setBeanstandeteWahlbriefe(wahlbezirkID, waehlerverzeichnisNummer, beanstandeteWahlbriefeCreateDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BeanstandeteWahlbriefeControllerApi.setBeanstandeteWahlbriefe']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BeanstandeteWahlbriefeControllerApi - factory interface
 * @export
 */
export const BeanstandeteWahlbriefeControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BeanstandeteWahlbriefeControllerApiFp(configuration)
    return {
        /**
         * Laden der Beanstandeten Wahlbriefe mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
         * @param {string} wahlbezirkID 
         * @param {number} waehlerverzeichnisNummer 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBeanstandeteWahlbriefe(wahlbezirkID: string, waehlerverzeichnisNummer: number, options?: RawAxiosRequestConfig): AxiosPromise<BeanstandeteWahlbriefeDTO> {
            return localVarFp.getBeanstandeteWahlbriefe(wahlbezirkID, waehlerverzeichnisNummer, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern von Beanstandeten Wahlbriefen mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
         * @param {string} wahlbezirkID 
         * @param {number} waehlerverzeichnisNummer 
         * @param {BeanstandeteWahlbriefeCreateDTO} beanstandeteWahlbriefeCreateDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setBeanstandeteWahlbriefe(wahlbezirkID: string, waehlerverzeichnisNummer: number, beanstandeteWahlbriefeCreateDTO: BeanstandeteWahlbriefeCreateDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setBeanstandeteWahlbriefe(wahlbezirkID, waehlerverzeichnisNummer, beanstandeteWahlbriefeCreateDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BeanstandeteWahlbriefeControllerApi - object-oriented interface
 * @export
 * @class BeanstandeteWahlbriefeControllerApi
 * @extends {BaseAPI}
 */
export class BeanstandeteWahlbriefeControllerApi extends BaseAPI {
    /**
     * Laden der Beanstandeten Wahlbriefe mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
     * @param {string} wahlbezirkID 
     * @param {number} waehlerverzeichnisNummer 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BeanstandeteWahlbriefeControllerApi
     */
    public getBeanstandeteWahlbriefe(wahlbezirkID: string, waehlerverzeichnisNummer: number, options?: RawAxiosRequestConfig) {
        return BeanstandeteWahlbriefeControllerApiFp(this.configuration).getBeanstandeteWahlbriefe(wahlbezirkID, waehlerverzeichnisNummer, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern von Beanstandeten Wahlbriefen mit { wahlbezirkID} und { waehlerverzeichnisNummer }.
     * @param {string} wahlbezirkID 
     * @param {number} waehlerverzeichnisNummer 
     * @param {BeanstandeteWahlbriefeCreateDTO} beanstandeteWahlbriefeCreateDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BeanstandeteWahlbriefeControllerApi
     */
    public setBeanstandeteWahlbriefe(wahlbezirkID: string, waehlerverzeichnisNummer: number, beanstandeteWahlbriefeCreateDTO: BeanstandeteWahlbriefeCreateDTO, options?: RawAxiosRequestConfig) {
        return BeanstandeteWahlbriefeControllerApiFp(this.configuration).setBeanstandeteWahlbriefe(wahlbezirkID, waehlerverzeichnisNummer, beanstandeteWahlbriefeCreateDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WahlbriefdatenControllerApi - axios parameter creator
 * @export
 */
export const WahlbriefdatenControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Wahlbriefdaten mit { wahlbezirkID }.
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlbriefdaten: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getWahlbriefdaten', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/wahlbriefdaten/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern der Wahlbriefdaten mit { wahlbezirkID }.
         * @param {string} wahlbezirkID 
         * @param {WahlbriefdatenWriteDTO} wahlbriefdatenWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlbriefdaten: async (wahlbezirkID: string, wahlbriefdatenWriteDTO: WahlbriefdatenWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postWahlbriefdaten', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'wahlbriefdatenWriteDTO' is not null or undefined
            assertParamExists('postWahlbriefdaten', 'wahlbriefdatenWriteDTO', wahlbriefdatenWriteDTO)
            const localVarPath = `/businessActions/wahlbriefdaten/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(wahlbriefdatenWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WahlbriefdatenControllerApi - functional programming interface
 * @export
 */
export const WahlbriefdatenControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WahlbriefdatenControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Wahlbriefdaten mit { wahlbezirkID }.
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWahlbriefdaten(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WahlbriefdatenDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWahlbriefdaten(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlbriefdatenControllerApi.getWahlbriefdaten']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern der Wahlbriefdaten mit { wahlbezirkID }.
         * @param {string} wahlbezirkID 
         * @param {WahlbriefdatenWriteDTO} wahlbriefdatenWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWahlbriefdaten(wahlbezirkID: string, wahlbriefdatenWriteDTO: WahlbriefdatenWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postWahlbriefdaten(wahlbezirkID, wahlbriefdatenWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WahlbriefdatenControllerApi.postWahlbriefdaten']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WahlbriefdatenControllerApi - factory interface
 * @export
 */
export const WahlbriefdatenControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WahlbriefdatenControllerApiFp(configuration)
    return {
        /**
         * Laden der Wahlbriefdaten mit { wahlbezirkID }.
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWahlbriefdaten(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<WahlbriefdatenDTO> {
            return localVarFp.getWahlbriefdaten(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern der Wahlbriefdaten mit { wahlbezirkID }.
         * @param {string} wahlbezirkID 
         * @param {WahlbriefdatenWriteDTO} wahlbriefdatenWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWahlbriefdaten(wahlbezirkID: string, wahlbriefdatenWriteDTO: WahlbriefdatenWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postWahlbriefdaten(wahlbezirkID, wahlbriefdatenWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WahlbriefdatenControllerApi - object-oriented interface
 * @export
 * @class WahlbriefdatenControllerApi
 * @extends {BaseAPI}
 */
export class WahlbriefdatenControllerApi extends BaseAPI {
    /**
     * Laden der Wahlbriefdaten mit { wahlbezirkID }.
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlbriefdatenControllerApi
     */
    public getWahlbriefdaten(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return WahlbriefdatenControllerApiFp(this.configuration).getWahlbriefdaten(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern der Wahlbriefdaten mit { wahlbezirkID }.
     * @param {string} wahlbezirkID 
     * @param {WahlbriefdatenWriteDTO} wahlbriefdatenWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WahlbriefdatenControllerApi
     */
    public postWahlbriefdaten(wahlbezirkID: string, wahlbriefdatenWriteDTO: WahlbriefdatenWriteDTO, options?: RawAxiosRequestConfig) {
        return WahlbriefdatenControllerApiFp(this.configuration).postWahlbriefdaten(wahlbezirkID, wahlbriefdatenWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



