import TheStimmzettelContent from "@/components/dse/TheStimmzettelContent.vue";

export default {
  title: "components/dse/TheStimmzettelContent",
  component: TheStimmzettelContent,
};

const sampleWahlvorschlaege = [
  {
    identifikator: "Partei A",
    ordnungszahl: 1,
    kurzname: "A",
    erhaeltStimmen: true,
    gueltigeStimmen: 0,
    ungueltigeStimmen: 0,
    kandidaten: [
      {
        identifikator: "101",
        name: "Alice Müller",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 1,
      },
      {
        identifikator: "101",
        name: "Alice Müller",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 2,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 1,
      },
      {
        identifikator: "102",
        name: "Bernd Schmidt",
        listenposition: 2,
        anzahlNennungen: 1,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 1,
      },
    ],
  },
  {
    identifikator: "Partei B",
    ordnungszahl: 2,
    kurzname: "B",
    erhaeltStimmen: false,
    gueltigeStimmen: 3,
    ungueltigeStimmen: 0,
    kandidaten: [
      {
        identifikator: "201",
        name: "Albert Tester",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 1,
        durchgestrichen: true,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "201",
        name: "Albert Tester",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 2,
        durchgestrichen: true,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "202",
        name: "Bine Meier",
        listenposition: 2,
        anzahlNennungen: 1,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
    ],
  },
  {
    identifikator: "Partei C",
    ordnungszahl: 3,
    kurzname: "C",
    erhaeltStimmen: false,
    gueltigeStimmen: 12,
    ungueltigeStimmen: 3,
    kandidaten: [
      {
        identifikator: "301",
        name: "Amina Raab",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "301",
        name: "Amina Raab",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 2,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
      {
        identifikator: "302",
        name: "Birgit Tenner",
        listenposition: 2,
        anzahlNennungen: 1,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "303",
        name: "Christa Haas",
        listenposition: 3,
        anzahlNennungen: 1,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "304",
        name: "Dominik Mausmann",
        listenposition: 4,
        anzahlNennungen: 1,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
    ],
  },
  {
    identifikator: "Partei D",
    ordnungszahl: 4,
    kurzname: "D",
    erhaeltStimmen: false,
    gueltigeStimmen: 0,
    ungueltigeStimmen: 9,
    kandidaten: [
      {
        identifikator: "401",
        name: "Adam Labert",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 1,
        durchgestrichen: true,
        gesamtStimmen: 3,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
      {
        identifikator: "401",
        name: "Adam Labert",
        listenposition: 1,
        anzahlNennungen: 2,
        nennungsposition: 2,
        durchgestrichen: true,
        gesamtStimmen: 3,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
      {
        identifikator: "402",
        name: "Bianca Bohnert",
        listenposition: 2,
        anzahlNennungen: 1,
        nennungsposition: 1,
        durchgestrichen: true,
        gesamtStimmen: 3,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
    ],
  },
  {
    identifikator: "Partei E",
    ordnungszahl: 5,
    kurzname: "E",
    erhaeltStimmen: false,
    gueltigeStimmen: 9,
    ungueltigeStimmen: 10,
    kandidaten: [
      {
        identifikator: "501",
        name: "Rosalia Mint",
        listenposition: 1,
        anzahlNennungen: 3,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 6,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
      {
        identifikator: "501",
        name: "Rosalia Mint",
        listenposition: 1,
        anzahlNennungen: 3,
        nennungsposition: 2,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "501",
        name: "Rosalia Mint",
        listenposition: 1,
        anzahlNennungen: 3,
        nennungsposition: 3,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "502",
        name: "Sabine Meier",
        listenposition: 2,
        anzahlNennungen: 3,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 6,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
      {
        identifikator: "502",
        name: "Sabine Meier",
        listenposition: 2,
        anzahlNennungen: 3,
        nennungsposition: 2,
        durchgestrichen: false,
        gesamtStimmen: 3,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 3,
        restStimmen: 0,
      },
      {
        identifikator: "502",
        name: "Sabine Meier",
        listenposition: 2,
        anzahlNennungen: 3,
        nennungsposition: 3,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "503",
        name: "Thomas Maier",
        listenposition: 3,
        anzahlNennungen: 3,
        nennungsposition: 1,
        durchgestrichen: false,
        gesamtStimmen: 4,
        gueltigeStimmen: 3,
        ungueltigeStimmen: 1,
        restStimmen: 0,
      },
      {
        identifikator: "503",
        name: "Thomas Maier",
        listenposition: 3,
        anzahlNennungen: 3,
        nennungsposition: 2,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
      {
        identifikator: "503",
        name: "Thomas Maier",
        listenposition: 3,
        anzahlNennungen: 3,
        nennungsposition: 3,
        durchgestrichen: false,
        gesamtStimmen: 0,
        gueltigeStimmen: 0,
        ungueltigeStimmen: 0,
        restStimmen: 0,
      },
    ],
  },
];

// Story: Anzeige des Stimmzettels mit Beispiel-Daten
export const Default = {
  args: {
    wahlvorschlaege: sampleWahlvorschlaege,
    maximalErlaubteStimmenProWahlvorschlag: 3,
    activeWahlvorschlagId: sampleWahlvorschlaege[4].identifikator,
    activeKandidatId: "503",
  },
};
