/* tslint:disable */
/* eslint-disable */
/**
 * Vorfälle und Vorkommnisse Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.5.0-SNAPSHOT
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface EreignisDTO
 */
export interface EreignisDTO {
    /**
     * 
     * @type {string}
     * @memberof EreignisDTO
     */
    'beschreibung'?: string;
    /**
     * 
     * @type {string}
     * @memberof EreignisDTO
     */
    'uhrzeit'?: string;
    /**
     * 
     * @type {string}
     * @memberof EreignisDTO
     */
    'ereignisart': EreignisDTOEreignisartEnum;
}

export const EreignisDTOEreignisartEnum = {
    Vorfall: 'VORFALL',
    Vorkommnis: 'VORKOMMNIS'
} as const;

export type EreignisDTOEreignisartEnum = typeof EreignisDTOEreignisartEnum[keyof typeof EreignisDTOEreignisartEnum];

/**
 * 
 * @export
 * @interface EreignisseWriteDTO
 */
export interface EreignisseWriteDTO {
    /**
     * 
     * @type {boolean}
     * @memberof EreignisseWriteDTO
     */
    'keineVorfaelle'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EreignisseWriteDTO
     */
    'keineVorkommnisse'?: boolean;
    /**
     * 
     * @type {Array<EreignisDTO>}
     * @memberof EreignisseWriteDTO
     */
    'ereigniseintraege'?: Array<EreignisDTO>;
}
/**
 * 
 * @export
 * @interface WahlbezirkEreignisseDTO
 */
export interface WahlbezirkEreignisseDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlbezirkEreignisseDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {boolean}
     * @memberof WahlbezirkEreignisseDTO
     */
    'keineVorfaelle'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WahlbezirkEreignisseDTO
     */
    'keineVorkommnisse'?: boolean;
    /**
     * 
     * @type {Array<EreignisDTO>}
     * @memberof WahlbezirkEreignisseDTO
     */
    'ereigniseintraege'?: Array<EreignisDTO>;
}
/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * EreignisControllerApi - axios parameter creator
 * @export
 */
export const EreignisControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Ereignisse des Wahllokals {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEreignisse: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getEreignisse', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/ereignisse/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern der Ereignisse des Wahllokals {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {EreignisseWriteDTO} ereignisseWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEreignisse: async (wahlbezirkID: string, ereignisseWriteDTO: EreignisseWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postEreignisse', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'ereignisseWriteDTO' is not null or undefined
            assertParamExists('postEreignisse', 'ereignisseWriteDTO', ereignisseWriteDTO)
            const localVarPath = `/businessActions/ereignisse/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(ereignisseWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EreignisControllerApi - functional programming interface
 * @export
 */
export const EreignisControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EreignisControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Ereignisse des Wahllokals {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEreignisse(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WahlbezirkEreignisseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEreignisse(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EreignisControllerApi.getEreignisse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern der Ereignisse des Wahllokals {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {EreignisseWriteDTO} ereignisseWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEreignisse(wahlbezirkID: string, ereignisseWriteDTO: EreignisseWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WahlbezirkEreignisseDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postEreignisse(wahlbezirkID, ereignisseWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EreignisControllerApi.postEreignisse']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EreignisControllerApi - factory interface
 * @export
 */
export const EreignisControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EreignisControllerApiFp(configuration)
    return {
        /**
         * Laden der Ereignisse des Wahllokals {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEreignisse(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<WahlbezirkEreignisseDTO> {
            return localVarFp.getEreignisse(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern der Ereignisse des Wahllokals {wahlbezirkID}.
         * @param {string} wahlbezirkID 
         * @param {EreignisseWriteDTO} ereignisseWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEreignisse(wahlbezirkID: string, ereignisseWriteDTO: EreignisseWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<WahlbezirkEreignisseDTO> {
            return localVarFp.postEreignisse(wahlbezirkID, ereignisseWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EreignisControllerApi - object-oriented interface
 * @export
 * @class EreignisControllerApi
 * @extends {BaseAPI}
 */
export class EreignisControllerApi extends BaseAPI {
    /**
     * Laden der Ereignisse des Wahllokals {wahlbezirkID}.
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EreignisControllerApi
     */
    public getEreignisse(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return EreignisControllerApiFp(this.configuration).getEreignisse(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern der Ereignisse des Wahllokals {wahlbezirkID}.
     * @param {string} wahlbezirkID 
     * @param {EreignisseWriteDTO} ereignisseWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EreignisControllerApi
     */
    public postEreignisse(wahlbezirkID: string, ereignisseWriteDTO: EreignisseWriteDTO, options?: RawAxiosRequestConfig) {
        return EreignisControllerApiFp(this.configuration).postEreignisse(wahlbezirkID, ereignisseWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



