### Get token wls_all
POST {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

password = test &
grant_type = password &
client_secret = top-secret &
client_id = wls &
username = wls_all

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}

### get userinfo with auth_token
GET {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/userinfo
Authorization: {{ token_type }} {{ auth_token }}

### GET Ereignisse
GET {{ WLS_VORFAELLEUNDVORKOMMNISSE_SERVICE_URL }}//businessActions/ereignisse/wahlbezirkID
Authorization: {{ token_type }} {{ auth_token }}

### POST Ereignisse
POST {{ WLS_VORFAELLEUNDVORKOMMNISSE_SERVICE_URL }}//businessActions/ereignisse/wahlbezirkID
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

{
  "beschreibung": "beschreibung",
  "uhrzeit": "2024-06-09T23:59:12.123",
  "ereignisart": "VORFALL"
}
