### get user
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET Role Mappings
GET {{ WLS_AUTH_SERVICE }}/roles/mappings
Authorization: Bearer {{$auth.token("auth-service")}}
