### get user "wls_all"
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### unlock user "wls_test"; dummy data are prepared that this works for the first time only
POST {{ WLS_AUTH_SERVICE }}/user/wls_test/unlock
Authorization: Bearer {{$auth.token("auth-service")}}