### get user
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

// !! OVERRIDES user wls_all_uwb
### create Users for wahltagID 827e9e6a-ebe9-483f-a9cd-162b26f348e8 | user wls_all_uwb
POST {{ WLS_AUTH_SERVICE }}/generateAndExportWahllokalbenutzer/827e9e6a-ebe9-483f-a9cd-162b26f348e8
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

[
  {
    "wahlbezirknummer": "9012",
    "wahltag": "2026-01-01",
    "wahlbezirkID": "9899cae4-df9a-4ffc-a940-f20cf2280171",
    "wahlbezirksart": "UWB",
    "wbid_wahlnummer": "{'wbid_wahlnummer': [{'wahlbezirkID': '9899cae4-df9a-4ffc-a940-f20cf2280171', 'wahlnummer': '0', 'wahlID': '28039463-3d3d-4ce5-acc1-0bef931a4409'}]}"
  }
]

### get users of wahltagID 827e9e6a-ebe9-483f-a9cd-162b26f348e8 | user wls_all_uwb
GET {{ WLS_AUTH_SERVICE }}/exportWahllokalbenutzer/827e9e6a-ebe9-483f-a9cd-162b26f348e8
Authorization: Bearer {{$auth.token("auth-service")}}

### delete users of wahltagID 827e9e6a-ebe9-483f-a9cd-162b26f348e8 | user wls_all_uwb
DELETE {{ WLS_AUTH_SERVICE }}/deleteWahllokalbenutzer/827e9e6a-ebe9-483f-a9cd-162b26f348e8
Authorization: Bearer {{$auth.token("auth-service")}}

// !! OVERRIDES user wls_all_bwb
### create Users for wahltagID 827e9e6a-ebe9-483f-a9cd-162b26f348e8 | user wls_all_bwb
POST {{ WLS_AUTH_SERVICE }}/generateAndExportWahllokalbenutzer/827e9e6a-ebe9-483f-a9cd-162b26f348e8
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

[
  {
    "wahlbezirknummer": "5678",
    "wahltag": "2026-01-01",
    "wahlbezirkID": "9081145c-dc16-4a9b-8255-5c49ddb98c14",
    "wahlbezirksart": "BWB",
    "wbid_wahlnummer": "{'wbid_wahlnummer': [{'wahlbezirkID': '9081145c-dc16-4a9b-8255-5c49ddb98c14', 'wahlnummer': '0', 'wahlID': '28039463-3d3d-4ce5-acc1-0bef931a4409'}]}"
  }
]

### get users of wahltagID 827e9e6a-ebe9-483f-a9cd-162b26f348e8 | user wls_all_bwb
GET {{ WLS_AUTH_SERVICE }}/exportWahllokalbenutzer/827e9e6a-ebe9-483f-a9cd-162b26f348e8
Authorization: Bearer {{$auth.token("auth-service")}}

### delete users of wahltagID 827e9e6a-ebe9-483f-a9cd-162b26f348e8 | user wls_all_bwb
DELETE {{ WLS_AUTH_SERVICE }}/deleteWahllokalbenutzer/827e9e6a-ebe9-483f-a9cd-162b26f348e8
Authorization: Bearer {{$auth.token("auth-service")}}