### get user "wls_all"
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### create Users wahltagID1
POST {{ WLS_AUTH_SERVICE }}/generateAndExportWahllokalbenutzer/wahltagID1
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

[
  {
    "wahlbezirknummer": "1001",
    "wahltag": "2024-10-29",
    "wahlbezirkID": "wbzID-1",
    "wahlbezirksart": "UWB",
    "wbid_wahlnummer": "0"
  },
  {
    "wahlbezirknummer": "1002",
    "wahltag": "2024-10-29",
    "wahlbezirkID": "wbzID-2",
    "wahlbezirksart": "UWB",
    "wbid_wahlnummer": "0"
  },
  {
    "wahlbezirknummer": "1003",
    "wahltag": "2024-10-29",
    "wahlbezirkID": "wbzID-3",
    "wahlbezirksart": "UWB",
    "wbid_wahlnummer": "0"
  }
]

### get users of wahltagID1
GET {{ WLS_AUTH_SERVICE }}/exportWahllokalbenutzer/wahltagID1
Authorization: Bearer {{$auth.token("auth-service")}}

### delete users of wahltagID1
DELETE {{ WLS_AUTH_SERVICE }}/deleteWahllokalbenutzer/wahltagID1
Authorization: Bearer {{$auth.token("auth-service")}}