spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: sso
              uri: http://host.docker.internal:8100/
              predicates:
                - Path=/api/sso/userinfo
              filters:
                - RewritePath=/api/sso/userinfo, /user
                - RemoveRequestHeader=Cookie
                - RemoveResponseHeader=Set-Cookie
            - id: admin-service
              uri: http://host.docker.internal:8209/
              predicates:
                - Path=/api/admin-service/**
              filters:
                - RewritePath=/api/admin-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: auth-service
              uri: http://host.docker.internal:8100/
              predicates:
                - Path=/api/auth-service/**
              filters:
                - RewritePath=/api/auth-service/(?<urlsegments>.*), /$\{urlsegments}
                - RemoveRequestHeader=Cookie
                - RemoveResponseHeader=Set-Cookie
            - id: basisdaten-service
              uri: http://host.docker.internal:8205/
              predicates:
                - Path=/api/basisdaten-service/**
              filters:
                - RewritePath=/api/basisdaten-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: broadcast-service
              uri: http://host.docker.internal:8200/
              predicates:
                - Path=/api/broadcast-service/**
              filters:
                - RewritePath=/api/broadcast-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: ergebnismeldung-service
              uri: http://host.docker.internal:8208/
              predicates:
                - Path=/api/ergebnismeldung-service/**
              filters:
                - RewritePath=/api/ergebnismeldung-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: infomanagement-service
              uri: http://host.docker.internal:8201/
              predicates:
                - Path=/api/infomanagement-service/**
              filters:
                - RewritePath=/api/infomanagement-service/(?<urlsegments>.*), /$\{urlsegments}
            - id: frontend-admintool
              uri: http://host.docker.internal:8401/
              predicates:
                - Path=/**