mapping:
  UWB:
    BTW:
      W: "Wahlvorsteher*in"
      SB: "Schriftführer*in"
      SWB: "Stellvertretung Wahlvorsteher*in"
      SSB: "Stellvertretung Schriftführer*in"
      B: "Beisitzer*in"
    BEB:
      W: "Wahlvorsteher*in"
      SB: ${mapping.UWB.BTW.SB}
      SWB: "Stellvertretung Wahlvorsteher*in"
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}
    BAW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: "Stellvertretung Wahlvorsteher*in"
      SSB: "Stellvertretung Schriftführer*in"
      B: ${mapping.UWB.BTW.B}
    BZW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BTW.SWB}
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}
    EUW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BTW.SWB}
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}
    LTW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BTW.SWB}
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}
    MBW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BTW.SWB}
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}
    OBW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BAW.SWB}
      SSB: ${mapping.UWB.BAW.SSB}
      B: ${mapping.UWB.BTW.B}
    SRW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BAW.SWB}
      SSB: ${mapping.UWB.BAW.SSB}
      B: ${mapping.UWB.BTW.B}
    SVW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BAW.SWB}
      SSB: ${mapping.UWB.BAW.SSB}
      B: ${mapping.UWB.BTW.B}
    VE:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BTW.SWB}
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}

  BWB:
    BTW:
      W: ${mapping.UWB.BTW.W}
      SB: ${mapping.UWB.BTW.SB}
      SWB: ${mapping.UWB.BTW.SWB}
      SSB: ${mapping.UWB.BTW.SSB}
      B: ${mapping.UWB.BTW.B}
    BEB:
      W: "Briefwahlvorsteher*in"
      SB: ${mapping.UWB.BEB.SB}
      SWB: "Stellvertretung Briefwahlvorsteher*in"
      SSB: ${mapping.UWB.BEB.SSB}
      B: ${mapping.UWB.BEB.B}
    BAW:
      W: ${mapping.UWB.BAW.W}
      SB: ${mapping.UWB.BAW.SB}
      SWB: ${mapping.UWB.BAW.SWB}
      SSB: ${mapping.UWB.BAW.SSB}
      B: ${mapping.UWB.BAW.B}
    BZW:
      W: ${mapping.UWB.BZW.W}
      SB: ${mapping.UWB.BZW.SB}
      SWB: ${mapping.UWB.BZW.SWB}
      SSB: ${mapping.UWB.BZW.SSB}
      B: ${mapping.UWB.BZW.B}
    EUW:
      W: ${mapping.UWB.EUW.W}
      SB: ${mapping.UWB.EUW.SB}
      SWB: ${mapping.UWB.EUW.SWB}
      SSB: ${mapping.UWB.EUW.SSB}
      B: ${mapping.UWB.EUW.B}
    LTW:
      W: ${mapping.UWB.LTW.W}
      SB: ${mapping.UWB.LTW.SB}
      SWB: ${mapping.UWB.LTW.SWB}
      SSB: ${mapping.UWB.LTW.SSB}
      B: ${mapping.UWB.LTW.B}
    MBW:
      W: ${mapping.UWB.MBW.W}
      SB: ${mapping.UWB.MBW.SB}
      SWB: ${mapping.UWB.MBW.SWB}
      SSB: ${mapping.UWB.MBW.SSB}
      B: ${mapping.UWB.MBW.B}
    OBW:
      W: ${mapping.UWB.OBW.W}
      SB: ${mapping.UWB.OBW.SB}
      SWB: ${mapping.UWB.OBW.SWB}
      SSB: ${mapping.UWB.OBW.SSB}
      B: ${mapping.UWB.OBW.B}
    SRW:
      W: ${mapping.UWB.SRW.W}
      SB: ${mapping.UWB.SRW.SB}
      SWB: ${mapping.UWB.SRW.SWB}
      SSB: ${mapping.UWB.SRW.SSB}
      B: ${mapping.UWB.SRW.B}
    SVW:
      W: ${mapping.UWB.SVW.W}
      SB: ${mapping.UWB.SVW.SB}
      SWB: ${mapping.UWB.SVW.SWB}
      SSB: ${mapping.UWB.SVW.SSB}
      B: ${mapping.UWB.SVW.B}
    VE:
      W: ${mapping.UWB.VE.W}
      SB: ${mapping.UWB.VE.SB}
      SWB: ${mapping.UWB.VE.SWB}
      SSB: ${mapping.UWB.VE.SSB}
      B: ${mapping.UWB.VE.B}