spring:
  application.name: @project.artifactId@
  banner.location: banner.txt
  profiles:
    group:
      local:
        - db-h2
  flyway:
    locations:
      - classpath:db/migrations/{vendor}
  h2.console.enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://kubernetes.docker.internal:8100/auth/realms/${realm}/protocol/openid-connect/certs



security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all
  oauth2:
    resource.user-info-uri: http://kubernetes.docker.internal:8100/auth/realms/${realm}/protocol/openid-connect/userinfo

service:
  info:
    oid: WLS-WAHLVORSTAND

# Define the local keycloak realm here
realm: wls_realm

server:
  shutdown: "graceful"
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  max-http-request-header-size: 32KB

# Config for spring actuator endpoints
management:
  server.port: ${server.port}
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
      path-mapping:
        prometheus: metrics
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
  info:
    env:
      enabled: true
info.application.name: @project.artifactId@
info.application.version: @project.version@

app:
  clients:
    eai:
      basePath: http://localhost:39149
    infomanagement:
      basePath: http://localhost:39148
    basisdaten:
      basePath: http://localhost:39151


# todo: ggf auslagern in eigenes file und dann einbinden 端ber profiles include
---
uwbFunktion:
  BTW:
    W: "Wahlvorsteher*in"
    SB: "Schriftf端hrer*in"
    SWB: "Stellvertretung Wahlvorsteher*in"
    SSB: "Stellvertretung Schriftf端hrer*in"
    B: "Beisitzer*in"
  BEB:
    W: "Wahlvorsteher*in"
    SB: ${uwbFunktion.BTW.SB}
    SWB: "Stellvertretung Wahlvorsteher*in"
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}
  BAW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: "Stellvertretung Wahlvorsteher*in"
    SSB: "Stellvertretung Schriftf端hrer*in"
    B: ${uwbFunktion.BTW.B}
  BZW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BTW.SWB}
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}
  EUW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BTW.SWB}
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}
  LTW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BTW.SWB}
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}
  MBW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BTW.SWB}
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}
  OBW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BAW.SWB}
    SSB: ${uwbFunktion.BAW.SSB}
    B: ${uwbFunktion.BTW.B}
  SRW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BAW.SWB}
    SSB: ${uwbFunktion.BAW.SSB}
    B: ${uwbFunktion.BTW.B}
  SVW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BAW.SWB}
    SSB: ${uwbFunktion.BAW.SSB}
    B: ${uwbFunktion.BTW.B}
  VE:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BTW.SWB}
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}

bwbFunktion:
  BTW:
    W: ${uwbFunktion.BTW.W}
    SB: ${uwbFunktion.BTW.SB}
    SWB: ${uwbFunktion.BTW.SWB}
    SSB: ${uwbFunktion.BTW.SSB}
    B: ${uwbFunktion.BTW.B}
  BEB:
    W: "Briefwahlvorsteher*in"
    SB: ${uwbFunktion.BEB.SB}
    SWB: "Stellvertretung Briefwahlvorsteher*in"
    SSB: ${uwbFunktion.BEB.SSB}
    B: ${uwbFunktion.BEB.B}
  BAW:
    W: ${uwbFunktion.BAW.W}
    SB: ${uwbFunktion.BAW.SB}
    SWB: ${uwbFunktion.BAW.SWB}
    SSB: ${uwbFunktion.BAW.SSB}
    B: ${uwbFunktion.BAW.B}
  BZW:
    W: ${uwbFunktion.BZW.W}
    SB: ${uwbFunktion.BZW.SB}
    SWB: ${uwbFunktion.BZW.SWB}
    SSB: ${uwbFunktion.BZW.SSB}
    B: ${uwbFunktion.BZW.B}
  EUW:
    W: ${uwbFunktion.EUW.W}
    SB: ${uwbFunktion.EUW.SB}
    SWB: ${uwbFunktion.EUW.SWB}
    SSB: ${uwbFunktion.EUW.SSB}
    B: ${uwbFunktion.EUW.B}
  LTW:
    W: ${uwbFunktion.LTW.W}
    SB: ${uwbFunktion.LTW.SB}
    SWB: ${uwbFunktion.LTW.SWB}
    SSB: ${uwbFunktion.LTW.SSB}
    B: ${uwbFunktion.LTW.B}
  MBW:
    W: ${uwbFunktion.MBW.W}
    SB: ${uwbFunktion.MBW.SB}
    SWB: ${uwbFunktion.MBW.SWB}
    SSB: ${uwbFunktion.MBW.SSB}
    B: ${uwbFunktion.MBW.B}
  OBW:
    W: ${uwbFunktion.OBW.W}
    SB: ${uwbFunktion.OBW.SB}
    SWB: ${uwbFunktion.OBW.SWB}
    SSB: ${uwbFunktion.OBW.SSB}
    B: ${uwbFunktion.OBW.B}
  SRW:
    W: ${uwbFunktion.SRW.W}
    SB: ${uwbFunktion.SRW.SB}
    SWB: ${uwbFunktion.SRW.SWB}
    SSB: ${uwbFunktion.SRW.SSB}
    B: ${uwbFunktion.SRW.B}
  SVW:
    W: ${uwbFunktion.SVW.W}
    SB: ${uwbFunktion.SVW.SB}
    SWB: ${uwbFunktion.SVW.SWB}
    SSB: ${uwbFunktion.SVW.SSB}
    B: ${uwbFunktion.SVW.B}
  VE:
    W: ${uwbFunktion.VE.W}
    SB: ${uwbFunktion.VE.SB}
    SWB: ${uwbFunktion.VE.SWB}
    SSB: ${uwbFunktion.VE.SSB}
    B: ${uwbFunktion.VE.B}