UPDATE Wahl SET r = 0 WHERE r IS NULL;
UPDATE Wahl SET g = 0 WHERE g IS NULL;
UPDATE Wahl SET b = 0 WHERE b IS NULL;

ALTER TABLE Wahl MODIFY r NOT NULL;

ALTER TABLE Wahl MODIFY g NOT NULL;

ALTER TABLE Wahl MODIFY b NOT NULL;