### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlvorstand fallback - working with dummy.client | user wls_all_uwb
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlvorstand forceUpdate=true - working with dummy.client | user wls_all_uwb
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}
ForceUpdate: true

### POST wahlvorstand | user wls_all_uwb
POST {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/9899cae4-df9a-4ffc-a940-f20cf2280171
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "anwesenheitBeginn": "2024-06-09T23:59:12.123",
  "wahlvorstandsmitglieder": [
    {
      "identifikator": "identifikator",
      "familienname": "name",
      "vorname": "vorname",
      "funktion": "SB",
      "funktionsname": "Name",
      "anwesend": true
    },
    {
      "identifikator": "identifikator2",
      "familienname": "name2",
      "vorname": "vorname2",
      "funktion": "SWB",
      "funktionsname": "anderer Name",
      "anwesend": false
    }
  ]
}

### GET wahlvorstand fallback - working with dummy.client | user wls_all_bwb
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlvorstand forceUpdate=true - working with dummy.client | user wls_all_bwb
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}
ForceUpdate: true

### POST wahlvorstand | user wls_all_bwb
POST {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/9081145c-dc16-4a9b-8255-5c49ddb98c14
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "anwesenheitBeginn": "2024-06-09T23:59:12.123",
  "wahlvorstandsmitglieder": [
    {
      "identifikator": "identifikator",
      "familienname": "name",
      "vorname": "vorname",
      "funktion": "SB",
      "funktionsname": "Name",
      "anwesend": true
    },
    {
      "identifikator": "identifikator2",
      "familienname": "name2",
      "vorname": "vorname2",
      "funktion": "SWB",
      "funktionsname": "anderer Name",
      "anwesend": false
    }
  ]
}
