### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlvorstand fallback - working with dummy.client
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/wahlbezirkID1
Authorization: Bearer {{$auth.token("auth-service")}}

### POST wahlvorstand
POST {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json

{
  "wahlbezirkID": "wahlbezirkID",
  "anwesenheitBeginn": "2024-06-09T23:59:12.123",
  "wahlvorstandsmitglieder": [
    {
      "identifikator": "identifikator",
      "familienname": "name",
      "vorname": "vorname",
      "funktion": "SB",
      "funktionsname": "Name",
      "anwesend": true
    },
    {
      "identifikator": "identifikator2",
      "familienname": "name2",
      "vorname": "vorname2",
      "funktion": "SWB",
      "funktionsname": "anderer Name",
      "anwesend": false
    }
  ]
}

### GET wahlvorstand - working with dummy.client
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}

### GET wahlvorstand forceUpdate=true - working with dummy.client
GET {{ WLS_WAHLVORSTAND_SERVICE_URL }}/businessActions/wahlvorstand/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}
ForceUpdate: true