/* tslint:disable */
/* eslint-disable */
/**
 * Wahlvorbereitung Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.2.0
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface BezirkIDUndWaehlerverzeichnisNummer
 */
export interface BezirkIDUndWaehlerverzeichnisNummer {
    /**
     * 
     * @type {string}
     * @memberof BezirkIDUndWaehlerverzeichnisNummer
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {number}
     * @memberof BezirkIDUndWaehlerverzeichnisNummer
     */
    'waehlerverzeichnisNummer': number;
}
/**
 * 
 * @export
 * @interface BriefwahlvorbereitungDTO
 */
export interface BriefwahlvorbereitungDTO {
    /**
     * 
     * @type {string}
     * @memberof BriefwahlvorbereitungDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {Array<WahlurneDTO>}
     * @memberof BriefwahlvorbereitungDTO
     */
    'urnenAnzahl': Array<WahlurneDTO>;
}
/**
 * 
 * @export
 * @interface BriefwahlvorbereitungWriteDTO
 */
export interface BriefwahlvorbereitungWriteDTO {
    /**
     * 
     * @type {Array<WahlurneDTO>}
     * @memberof BriefwahlvorbereitungWriteDTO
     */
    'urnenAnzahl': Array<WahlurneDTO>;
}
/**
 * 
 * @export
 * @interface EroeffnungsUhrzeitDTO
 */
export interface EroeffnungsUhrzeitDTO {
    /**
     * 
     * @type {string}
     * @memberof EroeffnungsUhrzeitDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof EroeffnungsUhrzeitDTO
     */
    'eroeffnungsuhrzeit': string;
}
/**
 * 
 * @export
 * @interface EroeffnungsUhrzeitWriteDTO
 */
export interface EroeffnungsUhrzeitWriteDTO {
    /**
     * 
     * @type {string}
     * @memberof EroeffnungsUhrzeitWriteDTO
     */
    'eroeffnungsuhrzeit': string;
}
/**
 * 
 * @export
 * @interface FortsetzungsUhrzeitDTO
 */
export interface FortsetzungsUhrzeitDTO {
    /**
     * 
     * @type {string}
     * @memberof FortsetzungsUhrzeitDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof FortsetzungsUhrzeitDTO
     */
    'fortsetzungsUhrzeit': string;
}
/**
 * 
 * @export
 * @interface FortsetzungsUhrzeitWriteDTO
 */
export interface FortsetzungsUhrzeitWriteDTO {
    /**
     * 
     * @type {string}
     * @memberof FortsetzungsUhrzeitWriteDTO
     */
    'fortsetzungsUhrzeit': string;
}
/**
 * 
 * @export
 * @interface UnterbrechungsUhrzeitDTO
 */
export interface UnterbrechungsUhrzeitDTO {
    /**
     * 
     * @type {string}
     * @memberof UnterbrechungsUhrzeitDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof UnterbrechungsUhrzeitDTO
     */
    'unterbrechungsUhrzeit': string;
}
/**
 * 
 * @export
 * @interface UnterbrechungsUhrzeitWriteDTO
 */
export interface UnterbrechungsUhrzeitWriteDTO {
    /**
     * 
     * @type {string}
     * @memberof UnterbrechungsUhrzeitWriteDTO
     */
    'unterbrechungsUhrzeit': string;
}
/**
 * 
 * @export
 * @interface UrnenwahlSchliessungsUhrzeitDTO
 */
export interface UrnenwahlSchliessungsUhrzeitDTO {
    /**
     * 
     * @type {string}
     * @memberof UrnenwahlSchliessungsUhrzeitDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {string}
     * @memberof UrnenwahlSchliessungsUhrzeitDTO
     */
    'schliessungsuhrzeit': string;
}
/**
 * 
 * @export
 * @interface UrnenwahlSchliessungsUhrzeitWriteDTO
 */
export interface UrnenwahlSchliessungsUhrzeitWriteDTO {
    /**
     * 
     * @type {string}
     * @memberof UrnenwahlSchliessungsUhrzeitWriteDTO
     */
    'schliessungsuhrzeit': string;
}
/**
 * 
 * @export
 * @interface UrnenwahlvorbereitungDTO
 */
export interface UrnenwahlvorbereitungDTO {
    /**
     * 
     * @type {string}
     * @memberof UrnenwahlvorbereitungDTO
     */
    'wahlbezirkID': string;
    /**
     * 
     * @type {number}
     * @memberof UrnenwahlvorbereitungDTO
     */
    'anzahlWahlkabinen': number;
    /**
     * 
     * @type {number}
     * @memberof UrnenwahlvorbereitungDTO
     */
    'anzahlWahltische': number;
    /**
     * 
     * @type {number}
     * @memberof UrnenwahlvorbereitungDTO
     */
    'anzahlNebenraeume': number;
    /**
     * 
     * @type {Array<WahlurneDTO>}
     * @memberof UrnenwahlvorbereitungDTO
     */
    'urnenAnzahl': Array<WahlurneDTO>;
}
/**
 * 
 * @export
 * @interface UrnenwahlvorbereitungWriteDTO
 */
export interface UrnenwahlvorbereitungWriteDTO {
    /**
     * 
     * @type {number}
     * @memberof UrnenwahlvorbereitungWriteDTO
     */
    'anzahlWahlkabinen': number;
    /**
     * 
     * @type {number}
     * @memberof UrnenwahlvorbereitungWriteDTO
     */
    'anzahlWahltische': number;
    /**
     * 
     * @type {number}
     * @memberof UrnenwahlvorbereitungWriteDTO
     */
    'anzahlNebenraeume': number;
    /**
     * 
     * @type {Array<WahlurneDTO>}
     * @memberof UrnenwahlvorbereitungWriteDTO
     */
    'urnenAnzahl': Array<WahlurneDTO>;
}
/**
 * 
 * @export
 * @interface WaehlerverzeichnisDTO
 */
export interface WaehlerverzeichnisDTO {
    /**
     * 
     * @type {BezirkIDUndWaehlerverzeichnisNummer}
     * @memberof WaehlerverzeichnisDTO
     */
    'bezirkIDUndWaehlerverzeichnisNummer': BezirkIDUndWaehlerverzeichnisNummer;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisDTO
     */
    'verzeichnisLagVor'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisDTO
     */
    'berichtigungVorBeginnDerAbstimmung'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisDTO
     */
    'nachtraeglicheBerichtigung'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisDTO
     */
    'mitteilungUeberUngueltigeWahlscheineErhalten'?: boolean;
}
/**
 * 
 * @export
 * @interface WaehlerverzeichnisWriteDTO
 */
export interface WaehlerverzeichnisWriteDTO {
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisWriteDTO
     */
    'verzeichnisLagVor'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisWriteDTO
     */
    'berichtigungVorBeginnDerAbstimmung'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisWriteDTO
     */
    'nachtraeglicheBerichtigung'?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof WaehlerverzeichnisWriteDTO
     */
    'mitteilungUeberUngueltigeWahlscheineErhalten'?: boolean;
}
/**
 * 
 * @export
 * @interface WahlurneDTO
 */
export interface WahlurneDTO {
    /**
     * 
     * @type {string}
     * @memberof WahlurneDTO
     */
    'wahlID': string;
    /**
     * 
     * @type {number}
     * @memberof WahlurneDTO
     */
    'anzahl': number;
    /**
     * 
     * @type {boolean}
     * @memberof WahlurneDTO
     */
    'urneVersiegelt'?: boolean;
}
/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * BriefwahlvorbereitungControllerApi - axios parameter creator
 * @export
 */
export const BriefwahlvorbereitungControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBriefwahlvorbereitung: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getBriefwahlvorbereitung', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/briefwahlvorbereitung/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisiert die Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {BriefwahlvorbereitungWriteDTO} briefwahlvorbereitungWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postBriefwahlvorbereitung: async (wahlbezirkID: string, briefwahlvorbereitungWriteDTO: BriefwahlvorbereitungWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postBriefwahlvorbereitung', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'briefwahlvorbereitungWriteDTO' is not null or undefined
            assertParamExists('postBriefwahlvorbereitung', 'briefwahlvorbereitungWriteDTO', briefwahlvorbereitungWriteDTO)
            const localVarPath = `/businessActions/briefwahlvorbereitung/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(briefwahlvorbereitungWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BriefwahlvorbereitungControllerApi - functional programming interface
 * @export
 */
export const BriefwahlvorbereitungControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BriefwahlvorbereitungControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getBriefwahlvorbereitung(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<BriefwahlvorbereitungDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getBriefwahlvorbereitung(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BriefwahlvorbereitungControllerApi.getBriefwahlvorbereitung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisiert die Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {BriefwahlvorbereitungWriteDTO} briefwahlvorbereitungWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postBriefwahlvorbereitung(wahlbezirkID: string, briefwahlvorbereitungWriteDTO: BriefwahlvorbereitungWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postBriefwahlvorbereitung(wahlbezirkID, briefwahlvorbereitungWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['BriefwahlvorbereitungControllerApi.postBriefwahlvorbereitung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * BriefwahlvorbereitungControllerApi - factory interface
 * @export
 */
export const BriefwahlvorbereitungControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BriefwahlvorbereitungControllerApiFp(configuration)
    return {
        /**
         * Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getBriefwahlvorbereitung(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<BriefwahlvorbereitungDTO> {
            return localVarFp.getBriefwahlvorbereitung(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisiert die Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {BriefwahlvorbereitungWriteDTO} briefwahlvorbereitungWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postBriefwahlvorbereitung(wahlbezirkID: string, briefwahlvorbereitungWriteDTO: BriefwahlvorbereitungWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postBriefwahlvorbereitung(wahlbezirkID, briefwahlvorbereitungWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * BriefwahlvorbereitungControllerApi - object-oriented interface
 * @export
 * @class BriefwahlvorbereitungControllerApi
 * @extends {BaseAPI}
 */
export class BriefwahlvorbereitungControllerApi extends BaseAPI {
    /**
     * Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BriefwahlvorbereitungControllerApi
     */
    public getBriefwahlvorbereitung(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return BriefwahlvorbereitungControllerApiFp(this.configuration).getBriefwahlvorbereitung(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisiert die Wahlvorbereitungsdaten des Briefwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {BriefwahlvorbereitungWriteDTO} briefwahlvorbereitungWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BriefwahlvorbereitungControllerApi
     */
    public postBriefwahlvorbereitung(wahlbezirkID: string, briefwahlvorbereitungWriteDTO: BriefwahlvorbereitungWriteDTO, options?: RawAxiosRequestConfig) {
        return BriefwahlvorbereitungControllerApiFp(this.configuration).postBriefwahlvorbereitung(wahlbezirkID, briefwahlvorbereitungWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * EroeffnungsUhrzeitControllerApi - axios parameter creator
 * @export
 */
export const EroeffnungsUhrzeitControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEroeffnungsuhrzeit: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getEroeffnungsuhrzeit', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/eroeffnungsuhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisiert die Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {EroeffnungsUhrzeitWriteDTO} eroeffnungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEroeffnungsuhrzeit: async (wahlbezirkID: string, eroeffnungsUhrzeitWriteDTO: EroeffnungsUhrzeitWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postEroeffnungsuhrzeit', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'eroeffnungsUhrzeitWriteDTO' is not null or undefined
            assertParamExists('postEroeffnungsuhrzeit', 'eroeffnungsUhrzeitWriteDTO', eroeffnungsUhrzeitWriteDTO)
            const localVarPath = `/businessActions/eroeffnungsuhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(eroeffnungsUhrzeitWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * EroeffnungsUhrzeitControllerApi - functional programming interface
 * @export
 */
export const EroeffnungsUhrzeitControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = EroeffnungsUhrzeitControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getEroeffnungsuhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<EroeffnungsUhrzeitDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getEroeffnungsuhrzeit(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EroeffnungsUhrzeitControllerApi.getEroeffnungsuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisiert die Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {EroeffnungsUhrzeitWriteDTO} eroeffnungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postEroeffnungsuhrzeit(wahlbezirkID: string, eroeffnungsUhrzeitWriteDTO: EroeffnungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postEroeffnungsuhrzeit(wahlbezirkID, eroeffnungsUhrzeitWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['EroeffnungsUhrzeitControllerApi.postEroeffnungsuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * EroeffnungsUhrzeitControllerApi - factory interface
 * @export
 */
export const EroeffnungsUhrzeitControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = EroeffnungsUhrzeitControllerApiFp(configuration)
    return {
        /**
         * Laden der Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getEroeffnungsuhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<EroeffnungsUhrzeitDTO> {
            return localVarFp.getEroeffnungsuhrzeit(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisiert die Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {EroeffnungsUhrzeitWriteDTO} eroeffnungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postEroeffnungsuhrzeit(wahlbezirkID: string, eroeffnungsUhrzeitWriteDTO: EroeffnungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postEroeffnungsuhrzeit(wahlbezirkID, eroeffnungsUhrzeitWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * EroeffnungsUhrzeitControllerApi - object-oriented interface
 * @export
 * @class EroeffnungsUhrzeitControllerApi
 * @extends {BaseAPI}
 */
export class EroeffnungsUhrzeitControllerApi extends BaseAPI {
    /**
     * Laden der Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EroeffnungsUhrzeitControllerApi
     */
    public getEroeffnungsuhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return EroeffnungsUhrzeitControllerApiFp(this.configuration).getEroeffnungsuhrzeit(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisiert die Eroeffnungsuhrzeit des Wahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {EroeffnungsUhrzeitWriteDTO} eroeffnungsUhrzeitWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof EroeffnungsUhrzeitControllerApi
     */
    public postEroeffnungsuhrzeit(wahlbezirkID: string, eroeffnungsUhrzeitWriteDTO: EroeffnungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig) {
        return EroeffnungsUhrzeitControllerApiFp(this.configuration).postEroeffnungsuhrzeit(wahlbezirkID, eroeffnungsUhrzeitWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * FortsetzungsUhrzeitControllerApi - axios parameter creator
 * @export
 */
export const FortsetzungsUhrzeitControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Fortsetzungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFortsetzungsUhrzeit: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getFortsetzungsUhrzeit', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/fortsetzungsUhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisiert die FortsetzungsUhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {FortsetzungsUhrzeitWriteDTO} fortsetzungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postFortsetzungsUhrzeit: async (wahlbezirkID: string, fortsetzungsUhrzeitWriteDTO: FortsetzungsUhrzeitWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postFortsetzungsUhrzeit', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'fortsetzungsUhrzeitWriteDTO' is not null or undefined
            assertParamExists('postFortsetzungsUhrzeit', 'fortsetzungsUhrzeitWriteDTO', fortsetzungsUhrzeitWriteDTO)
            const localVarPath = `/businessActions/fortsetzungsUhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(fortsetzungsUhrzeitWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * FortsetzungsUhrzeitControllerApi - functional programming interface
 * @export
 */
export const FortsetzungsUhrzeitControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = FortsetzungsUhrzeitControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Fortsetzungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getFortsetzungsUhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<FortsetzungsUhrzeitDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getFortsetzungsUhrzeit(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FortsetzungsUhrzeitControllerApi.getFortsetzungsUhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisiert die FortsetzungsUhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {FortsetzungsUhrzeitWriteDTO} fortsetzungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postFortsetzungsUhrzeit(wahlbezirkID: string, fortsetzungsUhrzeitWriteDTO: FortsetzungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postFortsetzungsUhrzeit(wahlbezirkID, fortsetzungsUhrzeitWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['FortsetzungsUhrzeitControllerApi.postFortsetzungsUhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * FortsetzungsUhrzeitControllerApi - factory interface
 * @export
 */
export const FortsetzungsUhrzeitControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = FortsetzungsUhrzeitControllerApiFp(configuration)
    return {
        /**
         * Laden der Fortsetzungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getFortsetzungsUhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<FortsetzungsUhrzeitDTO> {
            return localVarFp.getFortsetzungsUhrzeit(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisiert die FortsetzungsUhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {FortsetzungsUhrzeitWriteDTO} fortsetzungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postFortsetzungsUhrzeit(wahlbezirkID: string, fortsetzungsUhrzeitWriteDTO: FortsetzungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postFortsetzungsUhrzeit(wahlbezirkID, fortsetzungsUhrzeitWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * FortsetzungsUhrzeitControllerApi - object-oriented interface
 * @export
 * @class FortsetzungsUhrzeitControllerApi
 * @extends {BaseAPI}
 */
export class FortsetzungsUhrzeitControllerApi extends BaseAPI {
    /**
     * Laden der Fortsetzungsuhrzeit des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FortsetzungsUhrzeitControllerApi
     */
    public getFortsetzungsUhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return FortsetzungsUhrzeitControllerApiFp(this.configuration).getFortsetzungsUhrzeit(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisiert die FortsetzungsUhrzeit des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {FortsetzungsUhrzeitWriteDTO} fortsetzungsUhrzeitWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof FortsetzungsUhrzeitControllerApi
     */
    public postFortsetzungsUhrzeit(wahlbezirkID: string, fortsetzungsUhrzeitWriteDTO: FortsetzungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig) {
        return FortsetzungsUhrzeitControllerApiFp(this.configuration).postFortsetzungsUhrzeit(wahlbezirkID, fortsetzungsUhrzeitWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UnterbrechungsUhrzeitControllerApi - axios parameter creator
 * @export
 */
export const UnterbrechungsUhrzeitControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnterbrechungsuhrzeit: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getUnterbrechungsuhrzeit', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/unterbrechungsUhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisiert die Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UnterbrechungsUhrzeitWriteDTO} unterbrechungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUnterbrechungsuhrzeit: async (wahlbezirkID: string, unterbrechungsUhrzeitWriteDTO: UnterbrechungsUhrzeitWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postUnterbrechungsuhrzeit', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'unterbrechungsUhrzeitWriteDTO' is not null or undefined
            assertParamExists('postUnterbrechungsuhrzeit', 'unterbrechungsUhrzeitWriteDTO', unterbrechungsUhrzeitWriteDTO)
            const localVarPath = `/businessActions/unterbrechungsUhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(unterbrechungsUhrzeitWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UnterbrechungsUhrzeitControllerApi - functional programming interface
 * @export
 */
export const UnterbrechungsUhrzeitControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UnterbrechungsUhrzeitControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUnterbrechungsuhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UnterbrechungsUhrzeitDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUnterbrechungsuhrzeit(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UnterbrechungsUhrzeitControllerApi.getUnterbrechungsuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisiert die Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UnterbrechungsUhrzeitWriteDTO} unterbrechungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUnterbrechungsuhrzeit(wahlbezirkID: string, unterbrechungsUhrzeitWriteDTO: UnterbrechungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUnterbrechungsuhrzeit(wahlbezirkID, unterbrechungsUhrzeitWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UnterbrechungsUhrzeitControllerApi.postUnterbrechungsuhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UnterbrechungsUhrzeitControllerApi - factory interface
 * @export
 */
export const UnterbrechungsUhrzeitControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UnterbrechungsUhrzeitControllerApiFp(configuration)
    return {
        /**
         * Laden der Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUnterbrechungsuhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<UnterbrechungsUhrzeitDTO> {
            return localVarFp.getUnterbrechungsuhrzeit(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisiert die Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UnterbrechungsUhrzeitWriteDTO} unterbrechungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUnterbrechungsuhrzeit(wahlbezirkID: string, unterbrechungsUhrzeitWriteDTO: UnterbrechungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postUnterbrechungsuhrzeit(wahlbezirkID, unterbrechungsUhrzeitWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UnterbrechungsUhrzeitControllerApi - object-oriented interface
 * @export
 * @class UnterbrechungsUhrzeitControllerApi
 * @extends {BaseAPI}
 */
export class UnterbrechungsUhrzeitControllerApi extends BaseAPI {
    /**
     * Laden der Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UnterbrechungsUhrzeitControllerApi
     */
    public getUnterbrechungsuhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return UnterbrechungsUhrzeitControllerApiFp(this.configuration).getUnterbrechungsuhrzeit(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisiert die Unterbrechungsuhrzeit des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {UnterbrechungsUhrzeitWriteDTO} unterbrechungsUhrzeitWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UnterbrechungsUhrzeitControllerApi
     */
    public postUnterbrechungsuhrzeit(wahlbezirkID: string, unterbrechungsUhrzeitWriteDTO: UnterbrechungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig) {
        return UnterbrechungsUhrzeitControllerApiFp(this.configuration).postUnterbrechungsuhrzeit(wahlbezirkID, unterbrechungsUhrzeitWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UrnenwahlSchliessungsUhrzeitControllerApi - axios parameter creator
 * @export
 */
export const UrnenwahlSchliessungsUhrzeitControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUrnenwahlSchliessungsUhrzeit: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getUrnenwahlSchliessungsUhrzeit', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/urnenwahlSchliessungsUhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisiert die Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UrnenwahlSchliessungsUhrzeitWriteDTO} urnenwahlSchliessungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUrnenwahlSchliessungsUhrzeit: async (wahlbezirkID: string, urnenwahlSchliessungsUhrzeitWriteDTO: UrnenwahlSchliessungsUhrzeitWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postUrnenwahlSchliessungsUhrzeit', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'urnenwahlSchliessungsUhrzeitWriteDTO' is not null or undefined
            assertParamExists('postUrnenwahlSchliessungsUhrzeit', 'urnenwahlSchliessungsUhrzeitWriteDTO', urnenwahlSchliessungsUhrzeitWriteDTO)
            const localVarPath = `/businessActions/urnenwahlSchliessungsUhrzeit/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(urnenwahlSchliessungsUhrzeitWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UrnenwahlSchliessungsUhrzeitControllerApi - functional programming interface
 * @export
 */
export const UrnenwahlSchliessungsUhrzeitControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UrnenwahlSchliessungsUhrzeitControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUrnenwahlSchliessungsUhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UrnenwahlSchliessungsUhrzeitDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUrnenwahlSchliessungsUhrzeit(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UrnenwahlSchliessungsUhrzeitControllerApi.getUrnenwahlSchliessungsUhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisiert die Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UrnenwahlSchliessungsUhrzeitWriteDTO} urnenwahlSchliessungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUrnenwahlSchliessungsUhrzeit(wahlbezirkID: string, urnenwahlSchliessungsUhrzeitWriteDTO: UrnenwahlSchliessungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUrnenwahlSchliessungsUhrzeit(wahlbezirkID, urnenwahlSchliessungsUhrzeitWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UrnenwahlSchliessungsUhrzeitControllerApi.postUrnenwahlSchliessungsUhrzeit']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UrnenwahlSchliessungsUhrzeitControllerApi - factory interface
 * @export
 */
export const UrnenwahlSchliessungsUhrzeitControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UrnenwahlSchliessungsUhrzeitControllerApiFp(configuration)
    return {
        /**
         * Laden der Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUrnenwahlSchliessungsUhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<UrnenwahlSchliessungsUhrzeitDTO> {
            return localVarFp.getUrnenwahlSchliessungsUhrzeit(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisiert die Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UrnenwahlSchliessungsUhrzeitWriteDTO} urnenwahlSchliessungsUhrzeitWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUrnenwahlSchliessungsUhrzeit(wahlbezirkID: string, urnenwahlSchliessungsUhrzeitWriteDTO: UrnenwahlSchliessungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postUrnenwahlSchliessungsUhrzeit(wahlbezirkID, urnenwahlSchliessungsUhrzeitWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UrnenwahlSchliessungsUhrzeitControllerApi - object-oriented interface
 * @export
 * @class UrnenwahlSchliessungsUhrzeitControllerApi
 * @extends {BaseAPI}
 */
export class UrnenwahlSchliessungsUhrzeitControllerApi extends BaseAPI {
    /**
     * Laden der Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UrnenwahlSchliessungsUhrzeitControllerApi
     */
    public getUrnenwahlSchliessungsUhrzeit(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return UrnenwahlSchliessungsUhrzeitControllerApiFp(this.configuration).getUrnenwahlSchliessungsUhrzeit(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisiert die Urnenwahlschliessungsuhrzeit des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {UrnenwahlSchliessungsUhrzeitWriteDTO} urnenwahlSchliessungsUhrzeitWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UrnenwahlSchliessungsUhrzeitControllerApi
     */
    public postUrnenwahlSchliessungsUhrzeit(wahlbezirkID: string, urnenwahlSchliessungsUhrzeitWriteDTO: UrnenwahlSchliessungsUhrzeitWriteDTO, options?: RawAxiosRequestConfig) {
        return UrnenwahlSchliessungsUhrzeitControllerApiFp(this.configuration).postUrnenwahlSchliessungsUhrzeit(wahlbezirkID, urnenwahlSchliessungsUhrzeitWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * UrnenwahlvorbereitungControllerApi - axios parameter creator
 * @export
 */
export const UrnenwahlvorbereitungControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Laden der Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUrnenwahlVorbereitung: async (wahlbezirkID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getUrnenwahlVorbereitung', 'wahlbezirkID', wahlbezirkID)
            const localVarPath = `/businessActions/urnenwahlVorbereitung/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Aktualisiert die Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UrnenwahlvorbereitungWriteDTO} urnenwahlvorbereitungWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUrnenwahlvorbereitung: async (wahlbezirkID: string, urnenwahlvorbereitungWriteDTO: UrnenwahlvorbereitungWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postUrnenwahlvorbereitung', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'urnenwahlvorbereitungWriteDTO' is not null or undefined
            assertParamExists('postUrnenwahlvorbereitung', 'urnenwahlvorbereitungWriteDTO', urnenwahlvorbereitungWriteDTO)
            const localVarPath = `/businessActions/urnenwahlVorbereitung/{wahlbezirkID}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(urnenwahlvorbereitungWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UrnenwahlvorbereitungControllerApi - functional programming interface
 * @export
 */
export const UrnenwahlvorbereitungControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UrnenwahlvorbereitungControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Laden der Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUrnenwahlVorbereitung(wahlbezirkID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UrnenwahlvorbereitungDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUrnenwahlVorbereitung(wahlbezirkID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UrnenwahlvorbereitungControllerApi.getUrnenwahlVorbereitung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Aktualisiert die Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UrnenwahlvorbereitungWriteDTO} urnenwahlvorbereitungWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postUrnenwahlvorbereitung(wahlbezirkID: string, urnenwahlvorbereitungWriteDTO: UrnenwahlvorbereitungWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postUrnenwahlvorbereitung(wahlbezirkID, urnenwahlvorbereitungWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UrnenwahlvorbereitungControllerApi.postUrnenwahlvorbereitung']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UrnenwahlvorbereitungControllerApi - factory interface
 * @export
 */
export const UrnenwahlvorbereitungControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UrnenwahlvorbereitungControllerApiFp(configuration)
    return {
        /**
         * Laden der Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUrnenwahlVorbereitung(wahlbezirkID: string, options?: RawAxiosRequestConfig): AxiosPromise<UrnenwahlvorbereitungDTO> {
            return localVarFp.getUrnenwahlVorbereitung(wahlbezirkID, options).then((request) => request(axios, basePath));
        },
        /**
         * Aktualisiert die Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {UrnenwahlvorbereitungWriteDTO} urnenwahlvorbereitungWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postUrnenwahlvorbereitung(wahlbezirkID: string, urnenwahlvorbereitungWriteDTO: UrnenwahlvorbereitungWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postUrnenwahlvorbereitung(wahlbezirkID, urnenwahlvorbereitungWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UrnenwahlvorbereitungControllerApi - object-oriented interface
 * @export
 * @class UrnenwahlvorbereitungControllerApi
 * @extends {BaseAPI}
 */
export class UrnenwahlvorbereitungControllerApi extends BaseAPI {
    /**
     * Laden der Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UrnenwahlvorbereitungControllerApi
     */
    public getUrnenwahlVorbereitung(wahlbezirkID: string, options?: RawAxiosRequestConfig) {
        return UrnenwahlvorbereitungControllerApiFp(this.configuration).getUrnenwahlVorbereitung(wahlbezirkID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Aktualisiert die Wahlvorbereitungsdaten des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {UrnenwahlvorbereitungWriteDTO} urnenwahlvorbereitungWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UrnenwahlvorbereitungControllerApi
     */
    public postUrnenwahlvorbereitung(wahlbezirkID: string, urnenwahlvorbereitungWriteDTO: UrnenwahlvorbereitungWriteDTO, options?: RawAxiosRequestConfig) {
        return UrnenwahlvorbereitungControllerApiFp(this.configuration).postUrnenwahlvorbereitung(wahlbezirkID, urnenwahlvorbereitungWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * WaehlerverzeichnisControllerApi - axios parameter creator
 * @export
 */
export const WaehlerverzeichnisControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {number} wvzNummer 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWaehlerverzeichnis: async (wahlbezirkID: string, wvzNummer: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('getWaehlerverzeichnis', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'wvzNummer' is not null or undefined
            assertParamExists('getWaehlerverzeichnis', 'wvzNummer', wvzNummer)
            const localVarPath = `/businessActions/waehlerverzeichnis/{wahlbezirkID}/{wvzNummer}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)))
                .replace(`{${"wvzNummer"}}`, encodeURIComponent(String(wvzNummer)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichern der Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}. Wird je aktivem Wählerverzeichnis einmal gespeichert und per wvzNummer dem jeweiligen zugeordnet.
         * @param {string} wahlbezirkID 
         * @param {number} wvzNummer 
         * @param {WaehlerverzeichnisWriteDTO} waehlerverzeichnisWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWaehlerverzeichnis: async (wahlbezirkID: string, wvzNummer: number, waehlerverzeichnisWriteDTO: WaehlerverzeichnisWriteDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahlbezirkID' is not null or undefined
            assertParamExists('postWaehlerverzeichnis', 'wahlbezirkID', wahlbezirkID)
            // verify required parameter 'wvzNummer' is not null or undefined
            assertParamExists('postWaehlerverzeichnis', 'wvzNummer', wvzNummer)
            // verify required parameter 'waehlerverzeichnisWriteDTO' is not null or undefined
            assertParamExists('postWaehlerverzeichnis', 'waehlerverzeichnisWriteDTO', waehlerverzeichnisWriteDTO)
            const localVarPath = `/businessActions/waehlerverzeichnis/{wahlbezirkID}/{wvzNummer}`
                .replace(`{${"wahlbezirkID"}}`, encodeURIComponent(String(wahlbezirkID)))
                .replace(`{${"wvzNummer"}}`, encodeURIComponent(String(wvzNummer)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(waehlerverzeichnisWriteDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WaehlerverzeichnisControllerApi - functional programming interface
 * @export
 */
export const WaehlerverzeichnisControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WaehlerverzeichnisControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {number} wvzNummer 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWaehlerverzeichnis(wahlbezirkID: string, wvzNummer: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WaehlerverzeichnisDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWaehlerverzeichnis(wahlbezirkID, wvzNummer, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WaehlerverzeichnisControllerApi.getWaehlerverzeichnis']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichern der Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}. Wird je aktivem Wählerverzeichnis einmal gespeichert und per wvzNummer dem jeweiligen zugeordnet.
         * @param {string} wahlbezirkID 
         * @param {number} wvzNummer 
         * @param {WaehlerverzeichnisWriteDTO} waehlerverzeichnisWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postWaehlerverzeichnis(wahlbezirkID: string, wvzNummer: number, waehlerverzeichnisWriteDTO: WaehlerverzeichnisWriteDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postWaehlerverzeichnis(wahlbezirkID, wvzNummer, waehlerverzeichnisWriteDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WaehlerverzeichnisControllerApi.postWaehlerverzeichnis']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WaehlerverzeichnisControllerApi - factory interface
 * @export
 */
export const WaehlerverzeichnisControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WaehlerverzeichnisControllerApiFp(configuration)
    return {
        /**
         * Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}
         * @param {string} wahlbezirkID 
         * @param {number} wvzNummer 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWaehlerverzeichnis(wahlbezirkID: string, wvzNummer: number, options?: RawAxiosRequestConfig): AxiosPromise<WaehlerverzeichnisDTO> {
            return localVarFp.getWaehlerverzeichnis(wahlbezirkID, wvzNummer, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichern der Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}. Wird je aktivem Wählerverzeichnis einmal gespeichert und per wvzNummer dem jeweiligen zugeordnet.
         * @param {string} wahlbezirkID 
         * @param {number} wvzNummer 
         * @param {WaehlerverzeichnisWriteDTO} waehlerverzeichnisWriteDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postWaehlerverzeichnis(wahlbezirkID: string, wvzNummer: number, waehlerverzeichnisWriteDTO: WaehlerverzeichnisWriteDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postWaehlerverzeichnis(wahlbezirkID, wvzNummer, waehlerverzeichnisWriteDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WaehlerverzeichnisControllerApi - object-oriented interface
 * @export
 * @class WaehlerverzeichnisControllerApi
 * @extends {BaseAPI}
 */
export class WaehlerverzeichnisControllerApi extends BaseAPI {
    /**
     * Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}
     * @param {string} wahlbezirkID 
     * @param {number} wvzNummer 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WaehlerverzeichnisControllerApi
     */
    public getWaehlerverzeichnis(wahlbezirkID: string, wvzNummer: number, options?: RawAxiosRequestConfig) {
        return WaehlerverzeichnisControllerApiFp(this.configuration).getWaehlerverzeichnis(wahlbezirkID, wvzNummer, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichern der Angaben über das Wählerverzeichnis des Urnenwahllokals {wahlbezirkID}. Wird je aktivem Wählerverzeichnis einmal gespeichert und per wvzNummer dem jeweiligen zugeordnet.
     * @param {string} wahlbezirkID 
     * @param {number} wvzNummer 
     * @param {WaehlerverzeichnisWriteDTO} waehlerverzeichnisWriteDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WaehlerverzeichnisControllerApi
     */
    public postWaehlerverzeichnis(wahlbezirkID: string, wvzNummer: number, waehlerverzeichnisWriteDTO: WaehlerverzeichnisWriteDTO, options?: RawAxiosRequestConfig) {
        return WaehlerverzeichnisControllerApiFp(this.configuration).postWaehlerverzeichnis(wahlbezirkID, wvzNummer, waehlerverzeichnisWriteDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



