spring:
  application:
    name: "@project.artifactId@"
    group: "@project.groupId@"
    version: "@project.version@"
  banner.location: banner.txt
  profiles:
    group:
      local:
        - plainTextLogging
      standalone:
        - db-h2
        - dummy.clients
        - dummy.nobezirkid.check

  flyway:
    locations:
      - classpath:db/migrations/{vendor}
  h2.console.enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://host.docker.internal:8100/uaa/oauth2/jwks
  jpa:
    hibernate:
      ddl-auto: validate
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

security:
  # possible values: none, all, changing (With changing, only changing requests such as POST, PUT, DELETE are logged)
  logging.requests: all
  oauth2:
    resource.user-info-uri: http://host.docker.internal:8100/uaa/user

service:
  info:
    oid: WLS-MONITORING

server:
  shutdown: "graceful"
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    whitelabel:
      enabled: false
  max-http-request-header-size: 32KB

# Config for spring actuator endpoints
management:
  server.port: ${server.port}
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, livenessstate, readinessstate
      path-mapping:
        prometheus: metrics
    access:
      default: none
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
  info:
    env:
      enabled: true
info.application.name: @project.artifactId@
info.application.version: @project.version@

app:
  clients:
    eai:
      basePath: http://localhost:8300
