### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST Handbuch
POST {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/handbuch/wahlID1/UWB
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="helloWorld.pdf"

< ./attachements/helloWorld.pdf
--boundary

### GET Handbuch
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/handbuch/wahlID1/UWB
Authorization: Bearer {{$auth.token("auth-service")}}