### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST Handbuch | user wls_all_uwb
POST {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/handbuch/d8d2dd22-cbf6-488e-b9bc-b8c2b0ab31a1/UWB
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="helloWorld.pdf"

< ./attachements/helloWorld.pdf
--boundary

### GET Handbuch | user wls_all_uwb
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/handbuch/d8d2dd22-cbf6-488e-b9bc-b8c2b0ab31a1/UWB
Authorization: Bearer {{$auth.token("auth-service")}}

### POST Handbuch | user wls_all_bwb
POST {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/handbuch/28039463-3d3d-4ce5-acc1-0bef931a4409/BWB
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="helloWorld.pdf"

< ./attachements/helloWorld.pdf
--boundary

### GET Handbuch | user wls_all_bwb
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/handbuch/28039463-3d3d-4ce5-acc1-0bef931a4409/BWB
Authorization: Bearer {{$auth.token("auth-service")}}