### Get token wls_all
POST {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

password = test &
grant_type = password &
client_secret = top-secret &
client_id = wls &
username = wls_all

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}

### get userinfo with auth_token
GET {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/userinfo
Authorization: {{ token_type }} {{ auth_token }}

### Get Basisdaten - working with dummy.client
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/kopfdaten/wahlID1/wahlbezirkID1_1
Authorization: {{ token_type }} {{ auth_token }}