### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### get vorlagen
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/referendumvorlagen/wahl1/wbz1
Authorization: Bearer {{$auth.token("auth-service")}}