### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST RESET WAHLEN
POST {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/resetWahlen
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: application/json
