### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### POST ungueltige Wahlscheine
POST {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/ungueltigews/wahlID1/UWB
Authorization: Bearer {{$auth.token("auth-service")}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="ungueltigeWahlscheine.csv"

< ./attachements/ungueltigeWahlscheine.csv
--boundary

### GET ungueltige Wahlscheine
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/ungueltigews/wahlID1/UWB
Authorization: Bearer {{$auth.token("auth-service")}}