### Get token wls_all
POST {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

password = test &
grant_type = password &
client_secret = top-secret &
client_id = wls &
username = wls_all

> {%
    client.global.set("auth_token", response.body.access_token);
    client.global.set("token_type", response.body.token_type);
%}

### get userinfo with auth_token
GET {{ SSO_URL }}/auth/realms/wls_realm/protocol/openid-connect/userinfo
Authorization: {{ token_type }} {{ auth_token }}

### POST Wahlen
## If you want to POST Wahlen to override existing Wahlen with the intention to find them later with getWahlen
## please take account of the value of posted properties "wahltag", because getWahlen is searching by wahltagID and
## the date of the wahltag corresponding to this wahltagID is the search parameter for the Wahl in Repo. If there is no
## Wahl with this "wahltag", then you will recive the response from remote client, so you could think that the old Wahl
## could have not been overwritten in the step before. Actualy they were replaced, but if they do not have the date of
## the Wahltag, than indeed is the expected response, the response from remote client.
POST {{ WLS_BASISDATEN_SERVICE_URL }}//businessActions/wahlen/wahltagID1
Authorization: {{ token_type }} {{ auth_token }}
Content-Type: application/json

[
  {
    "wahlID": "wahl1",
    "name": "aName_1",
    "reihenfolge": 1,
    "waehlerverzeichnisnummer": 1,
    "wahltag": "2024-07-20",
    "wahlart": "BTW",
    "farbe": {
      "r": 0,
      "g": 1,
      "b": 2
    },
    "nummer": "1"
  },
  {
    "wahlID": "wahl2",
    "name": "1",
    "reihenfolge": 2,
    "waehlerverzeichnisnummer": 1,
    "wahltag": "2024-06-06",
    "wahlart": "EUW",
    "farbe": {
      "r": 3,
      "g": 4,
      "b": 5
    },
    "nummer": "1"
  },
  {
    "wahlID": "wahl3",
    "name": "2-",
    "reihenfolge": 3,
    "waehlerverzeichnisnummer": 1,
    "wahltag": "2024-06-06",
    "wahlart": "LTW",
    "farbe": {
      "r": 6,
      "g": 7,
      "b": 8
    },
    "nummer": "1"
  }
]

### GET Wahlen
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/wahlen/wahltagID1
Authorization: {{ token_type }} {{ auth_token }}