### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get Basisdaten - working with dummy.client
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/wahlvorschlaege/wahlID/wahlbezirkID
Authorization: Bearer {{$auth.token("auth-service")}}