### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get Wahlbezirke - working with dummy.client
## If No Wahltag for requested wahltagID than "Es wurde kein Wahltag zu dieser WahltagID gefunden. Bitte legen Sie die Basisdaten an."
## To create a Wahltag go to next call
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/wahlbezirke/wahltagID1
Authorization: Bearer {{$auth.token("auth-service")}}

### Get Wahltage - working with dummy.client
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/wahltage
Authorization: Bearer {{$auth.token("auth-service")}}