### get userinfo with auth_token
GET {{ WLS_AUTH_SERVICE }}/user
Authorization: Bearer {{$auth.token("auth-service")}}

### Get Wahltage - working with dummy.client
GET {{ WLS_BASISDATEN_SERVICE_URL }}/businessActions/wahltage
Authorization: Bearer {{$auth.token("auth-service")}}