/* tslint:disable */
/* eslint-disable */
/**
 * Infomanagement Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.4.1
 * Contact: Your E-Mail-Address
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface KennbuchstabenDTO
 */
export interface KennbuchstabenDTO {
    /**
     * 
     * @type {Array<string>}
     * @memberof KennbuchstabenDTO
     */
    'kennbuchstaben'?: Array<string>;
}
/**
 * 
 * @export
 * @interface KennbuchstabenListeDTO
 */
export interface KennbuchstabenListeDTO {
    /**
     * 
     * @type {Array<KennbuchstabenDTO>}
     * @memberof KennbuchstabenListeDTO
     */
    'kennbuchstabenListe'?: Array<KennbuchstabenDTO>;
}
/**
 * 
 * @export
 * @interface KennbuchstabenListenDTO
 */
export interface KennbuchstabenListenDTO {
    /**
     * 
     * @type {Array<KennbuchstabenListeDTO>}
     * @memberof KennbuchstabenListenDTO
     */
    'kennbuchstabenListen'?: Array<KennbuchstabenListeDTO>;
}
/**
 * 
 * @export
 * @interface KonfigurationDTO
 */
export interface KonfigurationDTO {
    /**
     * 
     * @type {string}
     * @memberof KonfigurationDTO
     */
    'schluessel': string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurationDTO
     */
    'wert'?: string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurationDTO
     */
    'beschreibung'?: string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurationDTO
     */
    'standardwert'?: string;
}
/**
 * 
 * @export
 * @interface KonfigurationSetDTO
 */
export interface KonfigurationSetDTO {
    /**
     * 
     * @type {string}
     * @memberof KonfigurationSetDTO
     */
    'wert'?: string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurationSetDTO
     */
    'beschreibung'?: string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurationSetDTO
     */
    'standardwert'?: string;
}
/**
 * 
 * @export
 * @interface KonfigurierterWahltagDTO
 */
export interface KonfigurierterWahltagDTO {
    /**
     * 
     * @type {string}
     * @memberof KonfigurierterWahltagDTO
     */
    'wahltag': string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurierterWahltagDTO
     */
    'wahltagID': string;
    /**
     * 
     * @type {string}
     * @memberof KonfigurierterWahltagDTO
     */
    'wahltagStatus': KonfigurierterWahltagDTOWahltagStatusEnum;
    /**
     * 
     * @type {string}
     * @memberof KonfigurierterWahltagDTO
     */
    'nummer': string;
}

export const KonfigurierterWahltagDTOWahltagStatusEnum = {
    Aktiv: 'AKTIV',
    Inaktiv: 'INAKTIV'
} as const;

export type KonfigurierterWahltagDTOWahltagStatusEnum = typeof KonfigurierterWahltagDTOWahltagStatusEnum[keyof typeof KonfigurierterWahltagDTOWahltagStatusEnum];

/**
 * 
 * @export
 * @interface WlsExceptionDTO
 */
export interface WlsExceptionDTO {
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'category': WlsExceptionDTOCategoryEnum;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'code': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'service': string;
    /**
     * 
     * @type {string}
     * @memberof WlsExceptionDTO
     */
    'message': string;
}

export const WlsExceptionDTOCategoryEnum = {
    F: 'F',
    T: 'T',
    S: 'S',
    I: 'I'
} as const;

export type WlsExceptionDTOCategoryEnum = typeof WlsExceptionDTOCategoryEnum[keyof typeof WlsExceptionDTOCategoryEnum];


/**
 * KonfigurationControllerApi - axios parameter creator
 * @export
 */
export const KonfigurationControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Gibt die Objekt mit einer Liste aller Kennbuchstaben zurück.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKennbuchstabenListen: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/kennbuchstaben`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gibt die Konfiguration { key } zurück.
         * @param {GetKonfigurationKeyEnum} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfiguration: async (key: GetKonfigurationKeyEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('getKonfiguration', 'key', key)
            const localVarPath = `/businessActions/konfiguration/{key}`
                .replace(`{${"key"}}`, encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gibt eine Konfiguration anhand der Loginzeit { key } zurück.
         * @param {GetKonfigurationUnauthorizedKeyEnum} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurationUnauthorized: async (key: GetKonfigurationUnauthorizedKeyEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('getKonfigurationUnauthorized', 'key', key)
            const localVarPath = `/businessActions/konfigurationUnauthorized/{key}`
                .replace(`{${"key"}}`, encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Gibt alle Konfigurationen zurück.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurations: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/konfiguration`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichert die Konfiguration { key }.
         * @param {PostKonfigurationKeyEnum} key 
         * @param {KonfigurationSetDTO} konfigurationSetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postKonfiguration: async (key: PostKonfigurationKeyEnum, konfigurationSetDTO: KonfigurationSetDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'key' is not null or undefined
            assertParamExists('postKonfiguration', 'key', key)
            // verify required parameter 'konfigurationSetDTO' is not null or undefined
            assertParamExists('postKonfiguration', 'konfigurationSetDTO', konfigurationSetDTO)
            const localVarPath = `/businessActions/konfiguration/{key}`
                .replace(`{${"key"}}`, encodeURIComponent(String(key)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(konfigurationSetDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KonfigurationControllerApi - functional programming interface
 * @export
 */
export const KonfigurationControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KonfigurationControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Gibt die Objekt mit einer Liste aller Kennbuchstaben zurück.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKennbuchstabenListen(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KennbuchstabenListenDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKennbuchstabenListen(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurationControllerApi.getKennbuchstabenListen']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gibt die Konfiguration { key } zurück.
         * @param {GetKonfigurationKeyEnum} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKonfiguration(key: GetKonfigurationKeyEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KonfigurationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKonfiguration(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurationControllerApi.getKonfiguration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gibt eine Konfiguration anhand der Loginzeit { key } zurück.
         * @param {GetKonfigurationUnauthorizedKeyEnum} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKonfigurationUnauthorized(key: GetKonfigurationUnauthorizedKeyEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KonfigurationDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKonfigurationUnauthorized(key, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurationControllerApi.getKonfigurationUnauthorized']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gibt alle Konfigurationen zurück.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKonfigurations(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<KonfigurationDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKonfigurations(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurationControllerApi.getKonfigurations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichert die Konfiguration { key }.
         * @param {PostKonfigurationKeyEnum} key 
         * @param {KonfigurationSetDTO} konfigurationSetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async postKonfiguration(key: PostKonfigurationKeyEnum, konfigurationSetDTO: KonfigurationSetDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.postKonfiguration(key, konfigurationSetDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurationControllerApi.postKonfiguration']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * KonfigurationControllerApi - factory interface
 * @export
 */
export const KonfigurationControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KonfigurationControllerApiFp(configuration)
    return {
        /**
         * Gibt die Objekt mit einer Liste aller Kennbuchstaben zurück.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKennbuchstabenListen(options?: RawAxiosRequestConfig): AxiosPromise<KennbuchstabenListenDTO> {
            return localVarFp.getKennbuchstabenListen(options).then((request) => request(axios, basePath));
        },
        /**
         * Gibt die Konfiguration { key } zurück.
         * @param {GetKonfigurationKeyEnum} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfiguration(key: GetKonfigurationKeyEnum, options?: RawAxiosRequestConfig): AxiosPromise<KonfigurationDTO> {
            return localVarFp.getKonfiguration(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Gibt eine Konfiguration anhand der Loginzeit { key } zurück.
         * @param {GetKonfigurationUnauthorizedKeyEnum} key 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurationUnauthorized(key: GetKonfigurationUnauthorizedKeyEnum, options?: RawAxiosRequestConfig): AxiosPromise<KonfigurationDTO> {
            return localVarFp.getKonfigurationUnauthorized(key, options).then((request) => request(axios, basePath));
        },
        /**
         * Gibt alle Konfigurationen zurück.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurations(options?: RawAxiosRequestConfig): AxiosPromise<Array<KonfigurationDTO>> {
            return localVarFp.getKonfigurations(options).then((request) => request(axios, basePath));
        },
        /**
         * Speichert die Konfiguration { key }.
         * @param {PostKonfigurationKeyEnum} key 
         * @param {KonfigurationSetDTO} konfigurationSetDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        postKonfiguration(key: PostKonfigurationKeyEnum, konfigurationSetDTO: KonfigurationSetDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.postKonfiguration(key, konfigurationSetDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * KonfigurationControllerApi - object-oriented interface
 * @export
 * @class KonfigurationControllerApi
 * @extends {BaseAPI}
 */
export class KonfigurationControllerApi extends BaseAPI {
    /**
     * Gibt die Objekt mit einer Liste aller Kennbuchstaben zurück.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurationControllerApi
     */
    public getKennbuchstabenListen(options?: RawAxiosRequestConfig) {
        return KonfigurationControllerApiFp(this.configuration).getKennbuchstabenListen(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gibt die Konfiguration { key } zurück.
     * @param {GetKonfigurationKeyEnum} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurationControllerApi
     */
    public getKonfiguration(key: GetKonfigurationKeyEnum, options?: RawAxiosRequestConfig) {
        return KonfigurationControllerApiFp(this.configuration).getKonfiguration(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gibt eine Konfiguration anhand der Loginzeit { key } zurück.
     * @param {GetKonfigurationUnauthorizedKeyEnum} key 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurationControllerApi
     */
    public getKonfigurationUnauthorized(key: GetKonfigurationUnauthorizedKeyEnum, options?: RawAxiosRequestConfig) {
        return KonfigurationControllerApiFp(this.configuration).getKonfigurationUnauthorized(key, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gibt alle Konfigurationen zurück.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurationControllerApi
     */
    public getKonfigurations(options?: RawAxiosRequestConfig) {
        return KonfigurationControllerApiFp(this.configuration).getKonfigurations(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichert die Konfiguration { key }.
     * @param {PostKonfigurationKeyEnum} key 
     * @param {KonfigurationSetDTO} konfigurationSetDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurationControllerApi
     */
    public postKonfiguration(key: PostKonfigurationKeyEnum, konfigurationSetDTO: KonfigurationSetDTO, options?: RawAxiosRequestConfig) {
        return KonfigurationControllerApiFp(this.configuration).postKonfiguration(key, konfigurationSetDTO, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetKonfigurationKeyEnum = {
    WlkTimeOut: 'WLK_TIME_OUT',
    Willkommenstext: 'WILLKOMMENSTEXT',
    Abschlusstext: 'ABSCHLUSSTEXT',
    WahllokalfinderUrl: 'WAHLLOKALFINDER_URL',
    FruehesteLoginUhrzeit: 'FRUEHESTE_LOGIN_UHRZEIT',
    SpaetesteLoginUhrzeit: 'SPAETESTE_LOGIN_UHRZEIT',
    FruehesteEroeffnungszeitUw: 'FRUEHESTE_EROEFFNUNGSZEIT_UW',
    SpaetesteEroeffnungszeitUw: 'SPAETESTE_EROEFFNUNGSZEIT_UW',
    FruehesteSchliessungszeitUw: 'FRUEHESTE_SCHLIESSUNGSZEIT_UW',
    FruehesteEroeffnungszeitBw: 'FRUEHESTE_EROEFFNUNGSZEIT_BW',
    SpaetesteEroeffnungszeitBw: 'SPAETESTE_EROEFFNUNGSZEIT_BW',
    FruehesteSchliessungszeitBw: 'FRUEHESTE_SCHLIESSUNGSZEIT_BW',
    MeldungszeitWahlSchliessen: 'MELDUNGSZEIT_WAHL_SCHLIESSEN',
    MeldungszeitAnwesenheitCheck: 'MELDUNGSZEIT_ANWESENHEIT_CHECK',
    Kennbuchstaben: 'KENNBUCHSTABEN',
    FruehesteEroeffnungszeit: 'FRUEHESTE_EROEFFNUNGSZEIT',
    SpaetesteEroeffnungszeit: 'SPAETESTE_EROEFFNUNGSZEIT',
    FruehesteSchliessungszeit: 'FRUEHESTE_SCHLIESSUNGSZEIT'
} as const;
export type GetKonfigurationKeyEnum = typeof GetKonfigurationKeyEnum[keyof typeof GetKonfigurationKeyEnum];
/**
 * @export
 */
export const GetKonfigurationUnauthorizedKeyEnum = {
    WlkTimeOut: 'WLK_TIME_OUT',
    Willkommenstext: 'WILLKOMMENSTEXT',
    Abschlusstext: 'ABSCHLUSSTEXT',
    WahllokalfinderUrl: 'WAHLLOKALFINDER_URL',
    FruehesteLoginUhrzeit: 'FRUEHESTE_LOGIN_UHRZEIT',
    SpaetesteLoginUhrzeit: 'SPAETESTE_LOGIN_UHRZEIT',
    FruehesteEroeffnungszeitUw: 'FRUEHESTE_EROEFFNUNGSZEIT_UW',
    SpaetesteEroeffnungszeitUw: 'SPAETESTE_EROEFFNUNGSZEIT_UW',
    FruehesteSchliessungszeitUw: 'FRUEHESTE_SCHLIESSUNGSZEIT_UW',
    FruehesteEroeffnungszeitBw: 'FRUEHESTE_EROEFFNUNGSZEIT_BW',
    SpaetesteEroeffnungszeitBw: 'SPAETESTE_EROEFFNUNGSZEIT_BW',
    FruehesteSchliessungszeitBw: 'FRUEHESTE_SCHLIESSUNGSZEIT_BW',
    MeldungszeitWahlSchliessen: 'MELDUNGSZEIT_WAHL_SCHLIESSEN',
    MeldungszeitAnwesenheitCheck: 'MELDUNGSZEIT_ANWESENHEIT_CHECK',
    Kennbuchstaben: 'KENNBUCHSTABEN',
    FruehesteEroeffnungszeit: 'FRUEHESTE_EROEFFNUNGSZEIT',
    SpaetesteEroeffnungszeit: 'SPAETESTE_EROEFFNUNGSZEIT',
    FruehesteSchliessungszeit: 'FRUEHESTE_SCHLIESSUNGSZEIT'
} as const;
export type GetKonfigurationUnauthorizedKeyEnum = typeof GetKonfigurationUnauthorizedKeyEnum[keyof typeof GetKonfigurationUnauthorizedKeyEnum];
/**
 * @export
 */
export const PostKonfigurationKeyEnum = {
    WlkTimeOut: 'WLK_TIME_OUT',
    Willkommenstext: 'WILLKOMMENSTEXT',
    Abschlusstext: 'ABSCHLUSSTEXT',
    WahllokalfinderUrl: 'WAHLLOKALFINDER_URL',
    FruehesteLoginUhrzeit: 'FRUEHESTE_LOGIN_UHRZEIT',
    SpaetesteLoginUhrzeit: 'SPAETESTE_LOGIN_UHRZEIT',
    FruehesteEroeffnungszeitUw: 'FRUEHESTE_EROEFFNUNGSZEIT_UW',
    SpaetesteEroeffnungszeitUw: 'SPAETESTE_EROEFFNUNGSZEIT_UW',
    FruehesteSchliessungszeitUw: 'FRUEHESTE_SCHLIESSUNGSZEIT_UW',
    FruehesteEroeffnungszeitBw: 'FRUEHESTE_EROEFFNUNGSZEIT_BW',
    SpaetesteEroeffnungszeitBw: 'SPAETESTE_EROEFFNUNGSZEIT_BW',
    FruehesteSchliessungszeitBw: 'FRUEHESTE_SCHLIESSUNGSZEIT_BW',
    MeldungszeitWahlSchliessen: 'MELDUNGSZEIT_WAHL_SCHLIESSEN',
    MeldungszeitAnwesenheitCheck: 'MELDUNGSZEIT_ANWESENHEIT_CHECK',
    Kennbuchstaben: 'KENNBUCHSTABEN',
    FruehesteEroeffnungszeit: 'FRUEHESTE_EROEFFNUNGSZEIT',
    SpaetesteEroeffnungszeit: 'SPAETESTE_EROEFFNUNGSZEIT',
    FruehesteSchliessungszeit: 'FRUEHESTE_SCHLIESSUNGSZEIT'
} as const;
export type PostKonfigurationKeyEnum = typeof PostKonfigurationKeyEnum[keyof typeof PostKonfigurationKeyEnum];


/**
 * KonfigurierterWahltagControllerApi - axios parameter creator
 * @export
 */
export const KonfigurierterWahltagControllerApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Löscht den Konfigurierten Wahltag anhand der { wahltagID }.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteKonfigurierterWahltag: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('deleteKonfigurierterWahltag', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/konfigurierterWahltag/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sucht alle Konfigurierten Wahltage.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurierteWahltage: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/konfigurierteWahltage`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Sucht den Konfigurierten Wahltag.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurierterWahltag: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/businessActions/konfigurierterWahltag`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Überprüft ob ein Wahltag { wahltagID } aktiv ist.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isWahltagActive: async (wahltagID: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'wahltagID' is not null or undefined
            assertParamExists('isWahltagActive', 'wahltagID', wahltagID)
            const localVarPath = `/businessActions/loginCheck/{wahltagID}`
                .replace(`{${"wahltagID"}}`, encodeURIComponent(String(wahltagID)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Speichert den Konfigurierten Wahltag.
         * @param {KonfigurierterWahltagDTO} konfigurierterWahltagDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setKonfigurierterWahltag: async (konfigurierterWahltagDTO: KonfigurierterWahltagDTO, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'konfigurierterWahltagDTO' is not null or undefined
            assertParamExists('setKonfigurierterWahltag', 'konfigurierterWahltagDTO', konfigurierterWahltagDTO)
            const localVarPath = `/businessActions/konfigurierterWahltag`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(konfigurierterWahltagDTO, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * KonfigurierterWahltagControllerApi - functional programming interface
 * @export
 */
export const KonfigurierterWahltagControllerApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = KonfigurierterWahltagControllerApiAxiosParamCreator(configuration)
    return {
        /**
         * Löscht den Konfigurierten Wahltag anhand der { wahltagID }.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteKonfigurierterWahltag(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteKonfigurierterWahltag(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurierterWahltagControllerApi.deleteKonfigurierterWahltag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sucht alle Konfigurierten Wahltage.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKonfigurierteWahltage(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<KonfigurierterWahltagDTO>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKonfigurierteWahltage(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurierterWahltagControllerApi.getKonfigurierteWahltage']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Sucht den Konfigurierten Wahltag.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getKonfigurierterWahltag(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<KonfigurierterWahltagDTO>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getKonfigurierterWahltag(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurierterWahltagControllerApi.getKonfigurierterWahltag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Überprüft ob ein Wahltag { wahltagID } aktiv ist.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async isWahltagActive(wahltagID: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<boolean>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.isWahltagActive(wahltagID, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurierterWahltagControllerApi.isWahltagActive']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Speichert den Konfigurierten Wahltag.
         * @param {KonfigurierterWahltagDTO} konfigurierterWahltagDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async setKonfigurierterWahltag(konfigurierterWahltagDTO: KonfigurierterWahltagDTO, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setKonfigurierterWahltag(konfigurierterWahltagDTO, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['KonfigurierterWahltagControllerApi.setKonfigurierterWahltag']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * KonfigurierterWahltagControllerApi - factory interface
 * @export
 */
export const KonfigurierterWahltagControllerApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = KonfigurierterWahltagControllerApiFp(configuration)
    return {
        /**
         * Löscht den Konfigurierten Wahltag anhand der { wahltagID }.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteKonfigurierterWahltag(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteKonfigurierterWahltag(wahltagID, options).then((request) => request(axios, basePath));
        },
        /**
         * Sucht alle Konfigurierten Wahltage.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurierteWahltage(options?: RawAxiosRequestConfig): AxiosPromise<Array<KonfigurierterWahltagDTO>> {
            return localVarFp.getKonfigurierteWahltage(options).then((request) => request(axios, basePath));
        },
        /**
         * Sucht den Konfigurierten Wahltag.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getKonfigurierterWahltag(options?: RawAxiosRequestConfig): AxiosPromise<KonfigurierterWahltagDTO> {
            return localVarFp.getKonfigurierterWahltag(options).then((request) => request(axios, basePath));
        },
        /**
         * Überprüft ob ein Wahltag { wahltagID } aktiv ist.
         * @param {string} wahltagID 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        isWahltagActive(wahltagID: string, options?: RawAxiosRequestConfig): AxiosPromise<boolean> {
            return localVarFp.isWahltagActive(wahltagID, options).then((request) => request(axios, basePath));
        },
        /**
         * Speichert den Konfigurierten Wahltag.
         * @param {KonfigurierterWahltagDTO} konfigurierterWahltagDTO 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        setKonfigurierterWahltag(konfigurierterWahltagDTO: KonfigurierterWahltagDTO, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.setKonfigurierterWahltag(konfigurierterWahltagDTO, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * KonfigurierterWahltagControllerApi - object-oriented interface
 * @export
 * @class KonfigurierterWahltagControllerApi
 * @extends {BaseAPI}
 */
export class KonfigurierterWahltagControllerApi extends BaseAPI {
    /**
     * Löscht den Konfigurierten Wahltag anhand der { wahltagID }.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurierterWahltagControllerApi
     */
    public deleteKonfigurierterWahltag(wahltagID: string, options?: RawAxiosRequestConfig) {
        return KonfigurierterWahltagControllerApiFp(this.configuration).deleteKonfigurierterWahltag(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sucht alle Konfigurierten Wahltage.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurierterWahltagControllerApi
     */
    public getKonfigurierteWahltage(options?: RawAxiosRequestConfig) {
        return KonfigurierterWahltagControllerApiFp(this.configuration).getKonfigurierteWahltage(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Sucht den Konfigurierten Wahltag.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurierterWahltagControllerApi
     */
    public getKonfigurierterWahltag(options?: RawAxiosRequestConfig) {
        return KonfigurierterWahltagControllerApiFp(this.configuration).getKonfigurierterWahltag(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Überprüft ob ein Wahltag { wahltagID } aktiv ist.
     * @param {string} wahltagID 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurierterWahltagControllerApi
     */
    public isWahltagActive(wahltagID: string, options?: RawAxiosRequestConfig) {
        return KonfigurierterWahltagControllerApiFp(this.configuration).isWahltagActive(wahltagID, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Speichert den Konfigurierten Wahltag.
     * @param {KonfigurierterWahltagDTO} konfigurierterWahltagDTO 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof KonfigurierterWahltagControllerApi
     */
    public setKonfigurierterWahltag(konfigurierterWahltagDTO: KonfigurierterWahltagDTO, options?: RawAxiosRequestConfig) {
        return KonfigurierterWahltagControllerApiFp(this.configuration).setKonfigurierterWahltag(konfigurierterWahltagDTO, options).then((request) => request(this.axios, this.basePath));
    }
}



