log_format json_access escape=json
  '{'
    '"timestamp":"$time_iso8601",'
    '"appName":"wls-gui-admintool",'
    '"level":"INFO",'
    '"logger":"nginx.gui.admintool",'
    '"message":"$request",'
    '"remote_addr":"$remote_addr",'
    '"requestInfo": {'
        '"status":$status,'
        '"body_bytes_sent":$body_bytes_sent,'
        '"request_time":$request_time,'
        '"http_referer":"$http_referer",'
        '"http_user_agent":"$http_user_agent"'
    '}'
  '}';

error_log /dev/stdout log_format;
access_log /dev/stdout info;