name: build push dev broadcast-service

on:
  push:
#    branches:
#      - dev
#    paths:
#      - 'wls-broadcast-service/**'
#      - '.github/workflows/build_broadcast-service_push-dev.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f wls-broadcast-service/pom.xml package

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}-broadcast-service
          tags: |
            # set latest tag for default branch
            type=raw,value=latest,enable=true

      - name: Build and push untested Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: ./wls-broadcast-service
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}