name: verify pull request broadcast-service

on:
  pull_request:
    paths:
      - 'wls-broadcast-service/**'
      - '.github/workflows/build_broadcast-service_pull-request.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn -f wls-broadcast-service/pom.xml verify