name: callable run mvn verify

on:
  workflow_call:
    inputs:
      pom-dir:
        required: true
        type: string
      javaVersion:
        required: true
        type: string

jobs:
  checkout-and-verify:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Set up JDK
        uses: actions/setup-java@03ad4de0992f5dab5e18fcb136590ce7c4a0ac95 # v5.6.0
        with:
          java-version: '${{ inputs.javaVersion }}'
          distribution: 'temurin'
          cache: 'maven'
          cache-dependency-path: '${{ inputs.pom-dir }}/pom.xml'

      - name: Build with Maven
        run: mvn -B -ntp -f ${{ inputs.pom-dir }}/pom.xml verify