name: callable run npm build

on:
  workflow_call:
    inputs:
      package-dir:
        required: true
        type: string

jobs:
  checkout-and-verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './${{ inputs.package-dir }}'
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.14.0
          cache: npm
          cache-dependency-path: '${{ inputs.package-dir }}/package-lock.json'

      - run: npm ci

      - run: npm run lint

      - run: npm run test

      - run: npm run build
