name: callable build github release from tag
on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: 'tag that is used for build'
      service:
        required: true
        type: string
        description: 'name of service to use'
      files:
        required: true
        type: string
        description: 'Newline-delimited globs of paths to assets to upload for release'
      javaVersion:
        required: false
        default: '17'
        type: string
        description: 'java version to use for build'

env:
  REGISTRY: ghcr.io

jobs:
  create-github-release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          ref: ${{ inputs.tag }}

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          cache: 'maven'
          cache-dependency-path: '${{ inputs.service }}/pom.xml'
          java-version: ${{ inputs.javaVersion }}
          distribution: 'temurin'

      - name: build jar without tests
        run: mvn -B -ntp -DskipTests verify -f ${{ inputs.service }}/pom.xml

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: ${{ inputs.files }}
          tag_name: ${{ inputs.tag }}
          draft: false
          prerelease: false
          generate_release_notes: false