name: callable build github container image
on:
  workflow_call:
    inputs:
      tag:
        required: false
        default: ''
        type: string
        description: 'optional tag that is used for build; default: github.ref'
      service:
        required: true
        type: string
        description: 'name of service to use'

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish-image:
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:

      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag || github.ref}}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          cache: 'maven'
          cache-dependency-path: ${{ inputs.service }}/pom.xml
          java-version: '17'
          distribution: 'temurin'

      - name: build jar without tests
        run: mvn -B -ntp -DskipTests package -f ${{ inputs.service }}/pom.xml

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}-${{ inputs.service }}
          context: git
          # tags:
          # - Major
          # - Major.Minor
          # - Major.Minor.Patch
          # - full semver: 1.2.3-RC2
          # - latest
          tags: |
            type=match,pattern=(${{ inputs.service }})/(\d).\d.\d,group=2,enable=${{ inputs.tag != '' }}
            type=match,pattern=(${{ inputs.service }})/(\d.\d).\d,group=2,enable=${{ inputs.tag != '' }}
            type=match,pattern=(${{ inputs.service }})/(\d.\d.\d),group=2,enable=${{ inputs.tag != '' }}
            type=match,pattern=(${{ inputs.service }})/(.*),group=2,enable=${{ inputs.tag != '' }}
            type=raw,value=latest,enable=${{ inputs.tag != '' }}
            type=raw,value=latest-dev

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ inputs.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}