name: callable run npm build

on:
  workflow_call:
    inputs:
      package-dir:
        required: true
        type: string

jobs:
  checkout-and-verify:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: './${{ inputs.package-dir }}'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: '${{ inputs.package-dir }}/package-lock.json'

      - run: npm ci

      - run: npm run build

      - run: npm run test

      - run: npm run lint
