name: verify pull request docs

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  run-docs-build:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - id: build_docs
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-docs@b088b94cad35e50b197104c9e2ac8fb25a7116b3 # v1.0.33