name: verify pull request docs

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  run-docs-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - id: build_docs
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-docs@94f7e40aa557a2790abfa98a9cc9186d260b94f8 # v1.0.27