name: verify pull request docs

on:
  pull_request:
    paths:
      - 'docs/**'

jobs:
  run-docs-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docs
    steps:
      - id: build_docs
        uses: it-at-m/lhm_actions/action-templates/actions/action-build-docs@7cb754b2056cebda6c36db344434f85be398c493 # v1.0.25