name: verify pull request vorfaelleundvorkommnisse-service

on:
  pull_request:
    paths:
      - 'wls-vorfaelleundvorkommnisse-service/**'
      - '.github/workflows/wls-vorfaelleundvorkommnisse-service_pull-request.yml'

jobs:
  verify-pull-request:
    uses:
      ./.github/workflows/callable-run-mvn-verify.yml
    with:
      pom-dir: 'wls-vorfaelleundvorkommnisse-service'