name: verify pull request eai-service

on:
  pull_request:
    paths:
      - 'wls-eai-service/**'
      - '.github/workflows/wls-eai-service_pull-request.yml'

jobs:
  verify-pull-request:
    uses:
      ./.github/workflows/callable-run-mvn-verify.yml
    with:
      pom-dir: 'wls-eai-service'