name: verify pull request api-gateway

on:
  pull_request:
    paths:
      - 'wls-api-gateway/**'
      - '.github/workflows/wls-api-gateway_pull-request.yml'

jobs:
  verify-pull-request:
    permissions:
      contents: read
    uses:
      ./.github/workflows/callable-run-mvn-verify.yml
    with:
      pom-dir: 'wls-api-gateway'
      javaVersion: '21'
