name: build push dev monitoring-service

on:
  push:
    branches:
      - dev
    paths:
      - 'wls-monitoring-service/**'
      - '.github/workflows/wls-monitoring-service_push-dev.yml'

jobs:
  build-github-container-image:
    permissions:
      packages: write
    uses:
      ./.github/workflows/callable-create-github-container-image.yml
    with:
      service: 'wls-monitoring-service'