name: verify pull request gui-admintool

on:
  pull_request:
    paths:
      - 'wls-gui-admintool/**'
      - '.github/workflows/wls-gui-admintool_pull-request.yml'

jobs:
  verify-pull-request:
    uses:
      ./.github/workflows/callable-run-npm-build.yml
    with:
      package-dir: 'wls-gui-admintool'
